### ISSUE TITLE
Make Beta work with BRAT

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [scambier/obsidian-omnisearch#1]
Currently Omnisearch doesn't work with BRAT as it's missing a manifest.json
https://github.com/TfTHacker/obsidian42-brat

**Comment by franciskafieh** [comment]
^^ instead of zipping the main.js, style.css, and manifest.json, just upload them separately

**Comment by StefanoRausch** [comment]
I second @geoffreysflaminglasersword request.

**Comment by scambier** [comment]
Alright, I fixed the release process and tested installation with BRAT. Looks like it's working 👍
