### ISSUE TITLE
[Feature request] Make highlights more visible i.e. by allowing to customise their colour

### ISSUE THREAD

**Issue by beetrootpaul** [scambier/obsidian-omnisearch#103]
It is difficult for me to spot highlighted found occurrences of searched phrase inside a content snippet. Ideally, I would love to have some enhancement for title matches as well.

**Describe the solution you'd like**

One of solutions I imagine could be to allow user to define a highlight colour to i.e. make them appear in orange so they would be more visible according to personal perception needs.

**Additional context**

Below a screenshot of results in my vault when I typed `game` with an ellipse marker added by me to show where the phrase occurs but it's difficult for me to see it, even if it's bold. OFC this screenshot is not the best since "game" phrase occur in the note title as well, but I am sure I have cases where the keyword wouldn't appear in the note title. Also, as wrote at the beginning of this issue, titles are not so easy to visually parse for me as well, therefore would be good to be able too apply same enhancements for them as well.

BTW This screenshot is made under Minimal theme, but I checked – on the default one I would need some highlight enhancement as well.

<img width="729" alt="screenshot 2022-10-03 at 12 25 35" src="https://user-images.githubusercontent.com/92947323/193557048-5a106ee0-a31a-43d1-a92f-8f1e6051e9c9.png">

**Comment by scambier** [comment]
This highlighting is intentionally left neutral to allow for customization.

You can add this in a CSS Snippet file:
```css
.omnisearch-highlight {
    color: var(--text-normal);
    background-color: var(--text-highlight-bg);
}
```

Though I agree it's not super user-friendly, I should add an opt-out setting for this.

**Comment by beetrootpaul** [comment]
and now I see this was in README, sorry I missed that 🤦
