### ISSUE TITLE
[Feature request] Do not fill Omnisearch with the last executed search if the next one was typed later on but not executed

### ISSUE THREAD

**Issue by beetrootpaul** [scambier/obsidian-omnisearch#104]
**Is your feature request related to a problem? Please describe.**

I feel like I failed to explain it in the title 😅  Let's try do better here with these reproduction steps:

1. Open Omnisearch
2. Type "abc"
3. Select one of results and press Enter, you should end up on selected note, Omnisearch disappears
4. Open Omnisearch, "abc" is already typed and selected to type over it
5. Type "def"
6. Press Esc, because you got distracted or wanted to check something in the note you opened before or wahtever
7. Open Omnisearch, "abc" is already typed and selected to type over it, but **what I would expect would be to have "def" typed there (or nothing at all, in case of a potential feature like showing recently visited files)**

**Describe the solution you'd like**

(see step 7 of reproduction steps written above)

**Describe alternatives you've considered**

(see content within parentheses of step 7 of reproduction steps written above)

**Comment by scambier** [comment]
Related feature request: #99 (will probably fix both together)
