### ISSUE TITLE
[Feature request] OCR

### ISSUE THREAD

**Issue by qotbpaul** [scambier/obsidian-omnisearch#106]
**Obsidian doesn't have OCR in image search.**

**Would love to be able to search text within images.**

**Have used Evernote for years, and this is really the only thing I miss.**

**Comment by tekwizz123** [comment]
Isn't this already sort of done via plugins such as https://github.com/MohrJonas/obsidian-ocr? I imagine this could be integrated into the search features of this tool though, if that is specifically what you are looking for here.

**Comment by qotbpaul** [comment]
Thanks, I haven't tried that yet, as it's still in early development. Not great with code myself, so always a little reticent about installing plugins before they are officially 'ready.'

**Comment by tekwizz123** [comment]
> Thanks, I haven't tried that yet, as it's still in early development. Not great with code myself, so always a little reticent about installing plugins before they are officially 'ready.'

Yep understandable. I did install it but it seemed to immediately try load every PDF in my library at once which meant 800 or so subprocesses opening, so definitely still in the early stages of things 😓

**Comment by scambier** [comment]
First beta available in 1.8.0-beta.3. Only supports English at the moment (i.e. non-English images will be read as English, which may produce weird results).

Will be improved in the coming months

**Comment by qotbpaul** [comment]
Much appreciated. Look forward to using it when it gets updated in community plug ins.

Thanks again
