### ISSUE TITLE
Problem with additional navigation of search results

### ISSUE THREAD

**Issue by tonygrr** [scambier/obsidian-omnisearch#108]
- Problem description:
  - additional navigation through the search results with  `ctrl+j/k(n/p)` does not work when a keyboard layout other than English is active.
- More info:
  - system: Windows 11 21H2;
  - plugin version: 1.6.4;
  - second keyboard layout: Russian.

**Comment by scambier** [comment]
Sorry I can't reproduce. Did you enable both settings?

Omnisearch:
![image](https://user-images.githubusercontent.com/3216752/197325111-1b31e315-3310-44df-b54a-3717b907d707.png)

Obsidian:
![image](https://user-images.githubusercontent.com/3216752/197325131-ed400738-654f-4a10-9538-d05b0e0f6269.png)

**Comment by tonygrr** [comment]
- @scambier yes, I have these settings activated. 
    - ![image](https://user-images.githubusercontent.com/72566774/197511225-a8d3c922-a260-4e9e-973c-08b0c643dc75.png)
    - ![image](https://user-images.githubusercontent.com/72566774/197511295-a0d834a2-643f-4d95-aadb-68124a0defc0.png)
- I will attach a video to clarify the problem. Note the language toggle in the lower right corner.
    -  ![omnisearch](https://user-images.githubusercontent.com/72566774/197511366-5e8a8216-655e-40f9-a7f1-89437160155e.gif)

**Comment by scambier** [comment]
I must say that I don't use the vim mode at all... Do you use any other other community plugin that have similar shortcuts, so that I can take a look at how they do it?

**Comment by scambier** [comment]
With your cyrillic layout, can you use https://unixpapa.com/js/testkey.html to show me the keycodes your keyboard is for the equivalent of `ctrl+j/k`? Thank you.

```
keydown  keyCode=17        which=17        charCode=0        
keydown  keyCode=74  (J)   which=74  (J)   charCode=0        
keydown  keyCode=17        which=17        charCode=0        
keydown  keyCode=75  (K)   which=75  (K)   charCode=0        
```

**Comment by tonygrr** [comment]
Strangely enough, I got a similar result:

```
keydown  keyCode=17        which=17        charCode=0        
keydown  keyCode=74  (J)   which=74  (J)   charCode=0        
keydown  keyCode=17        which=17        charCode=0        
keydown  keyCode=75  (K)   which=75  (K)   charCode=0
```

The selected layout has no effect on the codes returned by the keyboard.

![test](https://user-images.githubusercontent.com/72566774/197579031-3433c3ab-6020-4569-b847-5d5fe1785cb8.gif)

I should also clarify that in v. 6.3.2 of the plugin "Another Quick Switcher" navigation of search results using shortcuts ctrl+j/k worked with any keyboard layout ([gif with demonstration](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/85#issuecomment-1289277089)).

**Comment by scambier** [comment]
Here's a test build to try to fix the problem. I slightly changed my code to better match AQS 6.3.2: [omnisearch vim.zip](https://github.com/scambier/obsidian-omnisearch/files/9891058/omnisearch.vim.zip)

You can unzip it in `.obsidian\plugins\omnisearch`

**Comment by tonygrr** [comment]
@scambier thank you very much for your work. Now the navigation works flawlessly <3

It would be great to make the function to toggle excerpt (`ctrl+h`) work in the same way. Now this option does not switch when the Russian keyboard layout is selected.
