### ISSUE TITLE
[Request] Allow Command + Enter to open file in new pane on Mac

### ISSUE THREAD

**Issue by christyray** [scambier/obsidian-omnisearch#11]
Thank you for the great plugin! I've been testing it out, and I especially appreciate that it functions similarly to the native Quick Switcher. 

Currently, the hotkey to "Open in a New Pane" is set to Ctrl + Return, but the Quick Switcher default on Mac for "Open in a New Pane" is Command (⌘) + Return. Would it be possible to have the option to use the Command key instead of Control?

Edited to Add: I think the [Better Command Palette plugin](https://github.com/AlexBieg/obsidian-better-command-palette) sets the hotkeys based on OS, but JavaScript is foreign to me so I'm not entirely sure how it does it.

**Comment by scambier** [comment]
I don't have a Mac to try, but this should fix it. It will be deployed with the next release in the coming days 👍
