### ISSUE TITLE
[BUG] Excess padding on prompt

### ISSUE THREAD

**Issue by kepano** [scambier/obsidian-omnisearch#113]
**Problem description:**

As of 1.0.0 padding for modals and prompts has changed. As a result there is excess padding around the prompt.

My recommendation would be to follow the same wrapper style as the default Quick Switcher prompt, i.e. only use the `prompt` class and remove the `modal` class. Alternatively you could add `padding: 0` to the `.omnisearch-modal` but this may be less reliable long term.

**Your environment:**

- Omnisearch version: 1.6.4
- Obsidian version: 1.0.0

**Comment by scambier** [comment]
Indeed, that's subtle! Thanks (and thanks for that awesome default theme too)
