### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by menagerie198** [scambier/obsidian-omnisearch#114]
**Problem description:**

Since the latest (Omni) update, searching is not finding files I know to be there. It only seems to be finding files created since that update, and uncreated files. Is there a way of rebuilding the search index?

I am getting these errors in the Inspecor

[errorLog.txt](https://github.com/scambier/obsidian-omnisearch/files/9844965/errorLog.txt)

**Your environment:**

- Omnisearch version: 1.7.1
- Obsidian version: 1.0.2
- Operating system:  Win 10

- Number of notes in your vault (approx.): 3k
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
The index is rebuilt at startup, so restarting Obsidian should do it. Is there any error message in the developer console (ctrl+shift+i)?

**Comment by menagerie198** [comment]
Added error Log... [errorLog.txt](https://github.com/scambier/obsidian-omnisearch/files/9844965/errorLog.txt)

**Comment by scambier** [comment]
I _just_ published 1.7.2

This should hopefully show a Notice when the error triggers and stop the crashes (at the expense of some other things). Could you also tell me if you a see a message like this, a few seconds after startup?

```
Omnisearch - Indexed 1318 notes
Omnisearch - Timing: 11184.28076171875 ms
```

**Comment by wzajchow** [comment]
I have the same problem. 
Additionally, 'Tab' switching between vault and file search works only in one direction (possible to switch from file search to vault search but not vice versa). 
[error_log.txt](https://github.com/scambier/obsidian-omnisearch/files/9845012/error_log.txt)

**Comment by wzajchow** [comment]
> I _just_ published 1.7.2
> 
> This should hopefully show a Notice when the error triggers and stop the crashes (at the expense of some other things). Could you also tell me if you a see a message like this, a few seconds after startup?
> 
> ```
> Omnisearch - Indexed 1318 notes
> Omnisearch - Timing: 11184.28076171875 ms
> ```

After startup I am getting the notification saying: "Omnisearch - Error while getting tags from file, see developer console"
[error_log_v172.txt](https://github.com/scambier/obsidian-omnisearch/files/9845019/error_log_v172.txt)

**Comment by menagerie198** [comment]
This is what I got... 

'error while getting aliases from files. See developer console'

[errorLog.txt](https://github.com/scambier/obsidian-omnisearch/files/9845033/errorLog.txt)

Search also appears to be working ok though.

**Comment by scambier** [comment]
That is one interesting bug :D

Could you try disabling all other plugins, and re-enabling them one by one? I suspect one of them is playing with metadata in a way that Omnisearch does not expect.

**Comment by wzajchow** [comment]
I disabled all other plugins, restarted Obsidian and I got the same error: "Omnisearch - Error while getting tags from file, see developer console"
[error_log_v172_allDisabled.txt](https://github.com/scambier/obsidian-omnisearch/files/9845061/error_log_v172_allDisabled.txt)

**Comment by scambier** [comment]
Thank you, I'll fix that asap

**Comment by scambier** [comment]
Alright it should be fixed with 1.7.3

Obsidian slightly changed their API, but I don't understand why this bug didn't show up for me 🤔

**Comment by wzajchow** [comment]
In 1.7.3 no more notification error and switching using TAB is working fine. Thanks for such a quick fix! 

My suggestion is that when changing search file <-> vault, the searched phrase should stay in the search box and not be removed. 

The use case is simple: I am looking for 'something' in my file. It doesn't exist so I press `TAB` to search for it in the whole vault. Now I must retype the phrase I am searching for.

**Comment by scambier** [comment]
> My suggestion is that when changing search file <->search vault, the searched phrase should stay in the search box and not be removed.

Yep, regression bug. Will fix that one too 😅

**Comment by menagerie198** [comment]
All good here, too :-)

**Comment by scambier** [comment]
> My suggestion is that when changing search file <->search vault, the searched phrase should stay in the search box and not be removed.

Fixed and will be deployed for the next release
