### ISSUE TITLE
[Feature request] Toggle blank search field

### ISSUE THREAD

**Issue by FalloutCrew** [scambier/obsidian-omnisearch#115]
Hi, 
Currently, omnisearch remembers the last search I performed. When I perform a new search, I open omnisearch and start typing. However, I usually forget to remove the previous query, which is already in the text box. 
This could be solved by making omnisearch forget the search query when it is closed. A setting for this would be useful for me. 
Additionally, a search history could be useful for avoiding the risk of loosing search queries by accident.

**Comment by scambier** [comment]
Added a toggle in settings, but isn't your issue more related to https://github.com/scambier/obsidian-omnisearch/issues/105?

The text in the input field wasn't always correctly selected, so the new query didn't replace the old one. This was just fixed 2 days ago.

**Comment by FalloutCrew** [comment]
You are probably right. Thanks a lot!
