### ISSUE TITLE
[BUG] Pressing the tab key in the Vault Search box does not switch to In-File Search

### ISSUE THREAD

**Issue by mdrain** [scambier/obsidian-omnisearch#116]
**Problem description:**
Pressing the tab key in the Vault Search box does not switch to In-File Search. (Pressing the tab key in the In-File Search box switches to the Vault Search box as expected.)

**Your environment:**
- Omnisearch version: 1.7.3
- Obsidian version: 1.0.2
- Operating system: Windows 11
- Number of notes in your vault (approx.): 100
- Other plugins that may be related to the issue: Other community plugins disabled to test

**Comment by mdrain** [comment]
No, I am viewing regular Obsidian files. Does it only work with PDFs?

**Comment by scambier** [comment]
On the contrary, it doesn't work with PDFs. Could you look in the developer console (ctrl+shift+i) and check if there is any error related to Omnisearch _after_ trying to tab into InFile? Thanks

**Comment by mdrain** [comment]
I receive the below error when trying to tab into InFile. Let me know if I can provide additional information.

![image](https://user-images.githubusercontent.com/24597626/197616921-b070cb05-7368-4124-a5df-6c7a1c159936.png)

**Comment by scambier** [comment]
I think I found it. Does the bug happen when you're opening Omnisearch and directly hit tab with 0 query for the vault (and so 0 result)?

**Comment by mdrain** [comment]
That is correct. It works once the results are shown. Sorry I missed this point.

**Comment by scambier** [comment]
Alright, fixed and released :)
https://github.com/scambier/obsidian-omnisearch/releases/tag/1.7.5

**Comment by mdrain** [comment]
Thank you!
