### ISSUE TITLE
[BUG] Input being removed after "tab"ing into search in file

### ISSUE THREAD

**Issue by malkomalko** [scambier/obsidian-omnisearch#117]
**Problem description:**

After hitting `tab` to go into a file search, typing is constantly removing the inputs with weird behavior. I don't see any errors in the console in dev tools.

![CleanShot 2022-10-27 at 11 37 25](https://user-images.githubusercontent.com/763/198335149-9a31fbf7-c9a3-45bd-b86c-4255d7894183.gif)

**Your environment:**

- Omnisearch version: 1.7.5
- Obsidian version: 1.0.3
- Operating system:  macoS 12.6
- Number of notes in your vault (approx.): New vault
- Other plugins that may be related to the issue: n/a

**Comment by scambier** [comment]
Regression - this bugs just popped up again in latest beta (though less annoying)
