### ISSUE TITLE
[BUG] IndexedDB - Transaction timed out due to inactivity

### ISSUE THREAD

**Issue by JoKo1959** [scambier/obsidian-omnisearch#118]
<! Omnisearch is a great plugin; Thank You. The new version of Omnisearch does not work. It only shows "Omnisearch indexing is currently in progress"
- Omnisearch version: 1.76
- Obsidian version: 1.03
- Operating system: Windows 10 Enterprise
- Number of Notes in my vault: 1100

**Comment by scambier** [comment]
Is there any error log in the developer console (ctrl+shift+i)? You should see something like that:
![image](https://user-images.githubusercontent.com/3216752/198517925-916408fb-50aa-432a-be81-453d40026de4.png)

"Search cache written" indicates that indexing is done and Omnisearch is 100% operational.

**Comment by JoKo1959** [comment]
Is there another way to open the developer console? ctrl+shift+i does not work. Thank you

**Comment by scambier** [comment]
It's cmd+option+i if you're on a Mac, and afaik there's no other way. Make sure that Obsidian is focused before pressing the keys. https://forum.obsidian.md/t/how-to-access-the-console/16703/4

**Comment by JoKo1959** [comment]
![grafik](https://user-images.githubusercontent.com/116335587/198523784-33865b26-edf8-4b6e-a586-eb8083c772da.png)

**Comment by scambier** [comment]
👍 Could you unfold the DexieError and screenshot it too? Thanks

**Comment by JoKo1959** [comment]
![image](https://user-images.githubusercontent.com/116335587/198528624-05000f1d-c75b-42af-870f-4062237acaf4.png)

**Comment by scambier** [comment]
I published the update 1.7.7 with some improvements related to caching. Can you tell me if it solves your issue?

**Comment by JoKo1959** [comment]
Its not possible to update from 1.7.6 to 1.7.7 ("update failed"). Then I de-installed Omnisearch an tried to load it again; but now its not even possible to install it again.

**Comment by scambier** [comment]
Yeah sorry the build was buggy, I re-published it under 1.7.8. If you can't install it again it's probably a cache issue with Obsidian (I think a PC reboot will solve it).

**Comment by JoKo1959** [comment]
It works; thank you.
