### ISSUE TITLE
[BUG] Crashes on iOS

### ISSUE THREAD

**Issue by scambier** [scambier/obsidian-omnisearch#120]
**Problem description:**

Omnisearch causes an Obsidian crash on iOS

![image](https://user-images.githubusercontent.com/3216752/198985290-08d7aceb-5e45-4407-9a98-f3ee1864cb52.png)

![image](https://user-images.githubusercontent.com/3216752/198985104-f010947f-66f4-46b9-923e-84fdb8be30e7.png)

**Your environment:**

- Omnisearch version: 1.7.8
- Obsidian version:
- Operating system: iOS
- Number of notes in your vault (approx.):
- Other plugins that may be related to the issue:

**Comment by bramses** [comment]
A few initial thoughts:

AFAIK Web Workers aren't fully supported on iOS devices  ([see example here](https://developer.apple.com/forums/thread/650317), or [here](https://www.quora.com/Can-you-use-WebAssembly-to-create-native-iOS-and-Android-apps) or [here](https://shareup.app/blog/using-webassembly-on-ios/)) natively which might cause errors in https://github.com/scambier/obsidian-omnisearch/blob/342cdabdd9f27cd3f7877a36c0a076a78c9104b5/src/lib.rs#L8

PDF.js has had trouble recently on iOS: https://github.com/mozilla/pdf.js/issues/15543

I ciuldn't find where the normal indexing step is, but perhaps the PDF indexer is competing for resources?

**Comment by scambier** [comment]
@bramses thanks for your references 👍

I guess the crashes are caused by a too high memory usage. As simple as that. There's not a single root cause. Omnisearch uses **a lot** of memory during indexing/refreshing. It eventually goes back down, but all documents still need to live in RAM to update the search index when users modify their notes.

Using my test vault as a reference: 1300 notes + 4000 PDFs (several novels)

- Startup RAM: ~250MB
- Peak memory uses: ~700MB when indexing PDFs, ~1300MB when updating the IndexedDB.
- Settled: ~550MB

Without the PDFs:

- Startup RAM: ~250MB
- Peak memory use: ~400MB when updating the IndexedDB.
- Settled: ~270MB

**Comment by scambier** [comment]
Update: the culprit is most likely the cache (de)serialization. I disabled the cache for iOS devices, and it looks like it stopped the crashes for at least one user. While I'm not satisfied with this solution, all other workarounds I tried were not better, and would have made cache management a more complex. 

If your device keeps crashing, please add your input here with as much information as possible (number of notes, pdfs, copy of the console log). Thank you.

**Comment by bramses** [comment]
@scambier great find! These problems at this scale are very complex -- and break often, I imagine it will always be a WiP as devices evolve with time. I don't have any PDFs in my vault, but if I come across this bug, I'll follow up here. Thank you for the fix!

**Comment by scambier** [comment]
Update: I removed PDF indexing for _all_ mobile devices (incl. Android), which should also reduce the risk of a crash. Even if it works technically, it's not worth the headaches.

I prefer to propose a slightly inferior, but stable version of Omnisearch mobile, than something instable.

**Comment by scambier** [comment]
I don't think I can do much more for this issue, since the crashes are more than likely caused by memory consumption.  I'm doing my best to keep it as low as possible without compromising performances too much, but Minisearch _does_ use a lot of RAM 🤷‍♂️
