### ISSUE TITLE
[Feature request] In absence of new results, make current results stick

### ISSUE THREAD

**Issue by Sanqui** [scambier/obsidian-omnisearch#121]
This is another request of mine to enhance simple usability using heuristics.  Here's what I have on mind.  Let's say I want to open the "ZX Spectrum" note.  I start by typing "ZX", and the first result already shows "ZX Spectrum".  However, because I'm a fast typer, I continue by typing "ZX Spec" before realizing the result I want is already available.  Now, by the time I stop typing, the search shows 0 results because there is no match!  I have to either finish typing "Spectrum", or go back to just "ZX", to choose the note I want.  I think Omnisearch could do better in this situation.

My idea is that, if the search query is lengthened but Omnisearch finds no results for it, it should continue showing the previous results.  This should be more useful behavior in any situation, unless I am missing something?

**Comment by scambier** [comment]
Good suggestion. In the meantime, I suggest checking the new setting "_Retry queries that return zero result_".

**Comment by Sanqui** [comment]
With the setting, I get a correct result for even "ZX Spec", so I wonder if this feature is necessary after all :smile:

**Comment by scambier** [comment]
> With the setting, I get a correct result for even "ZX Spec", so I wonder if this feature is necessary after all 😄

It is definitely necessary, because like you said, you can get "0 result" until you type _more_, which is counter-intuitive.

**Comment by scambier** [comment]
I renamed the setting to "Simpler search", and set it to "off" by default.

> When enabled, Omnisearch is a bit more restrictive when using your query terms as prefixes. May return less results, but will be quicker. You should enable this if Omnisearch makes Obsidian freeze while searching.

I also added your suggestion to stick previous results. Will be deployed with next beta 👍

**Comment by scambier** [comment]
> I also added your suggestion to stick previous results. Will be deployed with next beta 👍

I'm reverting this in favor of a more explicit message "no result" message when "simpler search" is activated.

The rationale is that showing previous results when there are 0 result only makes sense under certain conditions, and is nonsensical under others. I'd rather not write more code to manage those conditions.
