### ISSUE TITLE
[BUG] Stuck Infinitively on Indexing

### ISSUE THREAD

**Issue by tekwizz123** [scambier/obsidian-omnisearch#124]
**Problem description:**
The latest [1.8.0-beta.1](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.8.0-beta.1) seems to be making it so that the index creation never ends. I did clear the cache when I installed the new version and then restarted Obsidian but to no avail, seems to just be stuck there forever.

**Your environment:**

- Omnisearch version: 1.8.0-beta.1
- Obsidian version: 1.0.3
- Operating system: Windows 11
- Number of notes in your vault (approx.): 1511
- Other plugins that may be related to the issue: None that I am aware of?

**Comment by scambier** [comment]
> the search never ends

The search or the indexing?

**Comment by tekwizz123** [comment]
> > the search never ends
> 
> The search or the indexing?

Index creation

**Comment by scambier** [comment]
I may have broken something with a merge somewhere, it works on my test vault but the bug is present in my normal vault 🤔

Will fix this asap.

**Comment by tekwizz123** [comment]
Fixed for me with [1.8.0-beta.2](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.8.0-beta.2), thanks @scambier!
