### ISSUE TITLE
[Feature request] change behavior of Ignored files, by not indexing and searching against

### ISSUE THREAD

**Issue by hailiang-wang** [scambier/obsidian-omnisearch#127]
**Is your feature request related to a problem? Please describe.**

Previously, the ignore action would still indexing the files which match the ignore patterns.
It does not work well for large vaults.

**Describe the solution you'd like**

![sceenshoot_20221111194804](https://user-images.githubusercontent.com/3538629/201334366-702cee8e-055c-4229-9a86-0b4a13ff0333.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by scambier** [comment]
As explained in #128, I won't _replace_ the downranking, but I can modify the feature to let the user decide between "downranking"  and "ignoring" excluded files. In the longer term, respecting gitignores or letting the user select a custom list of directories are also interesting.

I've seen in another comment that you offered to pay for the feature - I don't do commissioned work, but a donation (one-time or monthly) will obviously be greatly appreciated :)
