### ISSUE TITLE
Popup window on enable and startup

### ISSUE THREAD

**Issue by the-c0d3r** [scambier/obsidian-omnisearch#13]
**Type of issue**

- [X] A bug
- [ ] A performance problem

**Problem description**
When the plugin is installed and enabled, it pops up the word "3" on a new alert box. I didn't know it was from this plugin, and I had to do divide and conquer on all the plugins that I have installed, and I have narrowed it to this plugin. 

As soon as I enable this plugin on my community plugins setting, it will pop up the number "3", as well as on startup. 
![enable](https://user-images.githubusercontent.com/4526565/163516984-ad53c190-2ddd-45bd-b0b5-54b1f16ecca7.jpg)
![startup](https://user-images.githubusercontent.com/4526565/163516987-625ddf1b-4198-468b-82bd-3c811c845667.jpg)

**Your environment**

- Operating system: Windows 11
- Number of notes in your vault (approx.): 1500
- Version of Obsidian: 0.14.6
- Other plugins that may be related to the issue: None

**Comment by scambier** [comment]
- Does the problem appear when Omnisearch is the _only_  enabled plugin?
  - If not, what are the other enabled plugins?

I don't have this issue, and Omnisearch itself definitely doesn't `alert()` anything. I first thought that you might have a note with some HTML & JavaScript that was triggered during indexing, but that doesn't seem to be that. If you can't locate the incompatible plugin(s), could you send me your plugins list?

Thank you

**Comment by the-c0d3r** [comment]
Hi, thanks for the prompt response. 

It does happen when I only have the plugin as well. 
![1p](https://user-images.githubusercontent.com/4526565/163525210-027c298d-d15f-4cf9-817c-0872b2e9b7b5.jpg)

However, when I created a totally new vault, copied the plugin and paste it there, it doesn't do a popup. 
Does the plugin read the notes on startup? Maybe I have one note somewhere which does `alert()` and the plugin reads it and renders it?

So after adding my notes folder one by one, and trying to replicate the error, I found that as soon as I copied in my notes the popup would appear. Then I used that to narrow down the note that I have, and down to the specific line, line number 5.

I narrowed it down to this file, where I kept a list of command injection payloads and xss payloads. My other payloads have been removed from this file, as it doesn't cause the popup.
![note](https://user-images.githubusercontent.com/4526565/163526430-78965cbe-6691-4808-8b36-5235c391e15a.jpg)

If your plugin is disabled, it won't spawn a popup, but when it is enabled, and I copied the note into the vault, it will popup. It seems like your plugin might be vulnerable to XSS, which is weird because the payload is in `code` format.

```


\```

echo '<img src=https://crowdshield.com/.testing/xss.js onload=prompt(2) onerror=alert(3)></img>'// XXXXXXXXXXX

\```
```
(note: please remove the leading slash as I cannot escape the nested triple ticks on the github flavour markdown.)

**Comment by scambier** [comment]
Yep that's it, thanks for you investigation!

I'll add a sanitization step asap, before the notes indexing.
