### ISSUE TITLE
[BUG] Word highlighting doesn't work on Korean characters

### ISSUE THREAD

**Issue by style5966** [scambier/obsidian-omnisearch#131]
**Problem description:**
I'm a Korean. Please forgive me for writing using a translator. If you search for vault in English like the picture below, the highlight function works normally. However, when I search in Korean, the highlights do not appear. I tried adding it directly to the css snipet, and I also tried editing the plugin style.css directly, but the result is the same. how should i solve it? i need help

https://github.com/aidenlx/cm-chs-patch

Currently, we have finished the Korean patch through this plugin.

I attach a screenshot.
The first is Korean search results
The second is the English search result
[screenshot](https://imgur.com/a/vbARtKg)

**Your environment:**

- Omnisearch version:
- Obsidian version:
- Operating system: 
- Number of notes in your vault (approx.):
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Should be fixed [in the latest beta](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.9.0-beta.3)
