### ISSUE TITLE
[BUG] PDF Indexing leads to crashdown on Android

### ISSUE THREAD

**Issue by JuergenKaettnis** [scambier/obsidian-omnisearch#132]
I am using Samsung S4 tablet with Android. All software uptodate. When pdf indexing is turned on, I often experience crashdown of Obsidian. Image indexing seems to work smoothly.

If you need more info, feel free to refer back to me.

ThanX for the great software.

**Comment by scambier** [comment]
Hello, could you tell me (approx.) how many notes & pdf you have in your vault?

Do the crashes happen at startup, or during searches?

**Comment by scambier** [comment]
I disabled PDF and OCR for mobile. Too many issues, not worth the headaches.
