### ISSUE TITLE
[Feature request] Exclude non-existing notes

### ISSUE THREAD

**Issue by aziham** [scambier/obsidian-omnisearch#133]
**Is your feature request related to a problem? Please describe.**

- It'll be nice if there's a setting to hide the non-existing notes (Notes that don't exist but are still linked) from showing on the search result.

**Describe the solution you'd like**

- A toggle in omnisearch settings to enable/disable this feature

---

**Comment by scambier** [comment]
Non existing notes are no longer indexed as of 1.9.0 (still in beta). If I ever re-implement the feature, I'll add a toggle.

**Comment by aziham** [comment]
Thanks, looking forward to the next stable release.
