### ISSUE TITLE
[Feature request] PDF search jump to page and location in PDF document

### ISSUE THREAD

**Issue by SoRobby** [scambier/obsidian-omnisearch#135]
**Overview**
When a search returns a PDF result and you select it, it would be extremely helpful to jump to the specific page and location in the PDF document where the keyword is.

Currently the only way to find the specific page is to open the PDF in a third party app (e.g. Adobe Reader or Chrome) and do a `CTRL+F` to find the page and location of the keyword.

I hope this is clear, if you have any questions please let me know, thanks!

**Comment by scambier** [comment]
Related: #100

**Comment by scambier** [comment]
Closed as duplicate
