### ISSUE TITLE
Feature request: Include notes that don't exist

### ISSUE THREAD

**Issue by laurastephsmith** [scambier/obsidian-omnisearch#14]
This is a fantastic plugin! One thing I miss from the default quick switcher though is having notes that don't exist yet showing up. In other words, notes that are `[[linked]]` from somewhere but haven't been created yet. I find that really useful to make sure my new notes are linked into existing references to something.

**Comment by briskmap4926** [comment]
Agree-this would be an incredible enhancement.

**Comment by fnuttens** [comment]
Omnisearch doesn’t find any note that’s not created yet, am I supposed to enable something in the indexing parameters?

**Comment by scambier** [comment]
The feature was removed because it was buggy. There's another issue to reimplement it #227
