### ISSUE TITLE
[Feature request] Improve default api output

### ISSUE THREAD

**Issue by Quorafind** [scambier/obsidian-omnisearch#141]
**Is your feature request related to a problem? Please describe.**

Now we can use Omnisearch to get result like:

```
base: string
foundwords: string[]
matches: SearchMatchApi[]
path: string
score: number
```

It would return result offset rather than string around result.

**Describe the solution you'd like**

is it possible to use query like `omnisearch.search(query: string, fullresult: boolean)` to fetch result like Omnisearch did?

So that we don't need to parse it and cacheread Obsidian file again.

**Describe alternatives you've considered**

Not yet.

**Additional context**

**Comment by scambier** [comment]
I'll add an `excerpt` field in the result object. What is your use-case for this?

**Comment by Quorafind** [comment]
I want to trigger omnisearch when users search text in Surfing, that means when you are searching with google/bing, a floating box would show result from omnisearch. By the way, if omnisearch provides a event like `index-finished` to let me to register custom function with it, it will be better, so that I don't need to setTimeout to wait omnisearch finished index.

**Comment by scambier** [comment]
A simple callback like `omnisearch.onIndexedFinished(yourCallback)`, or something else?

**Comment by Quorafind** [comment]
> A simple callback like `omnisearch.onIndexedFinished(yourCallback)`, or something else?

Callback is enough. Like it can be called every time omnisearch updates index

**Comment by scambier** [comment]
The API has now the following signature in beta

```ts
type OmnisearchApi = {
  // Returns a promise that will contain the same results as the Vault modal
  search: (query: string) => Promise<ResultNoteApi[]>,
  // Refreshes the index
  refreshIndex: () => Promise<void>
  // Register a callback that will be called when the indexing is done
  registerOnIndexed: (callback: () => void) => void,
  // Unregister a callback that was previously registered
  unregisterOnIndexed: (callback: () => void) => void,
}
```

The callback is only used at startup, when Omnisearch does its "big" indexing. After that you may simply call `refreshIndex()` to make sure it's up-to-date. That same function is called by Omnisearch each time you open the modal.
