### ISSUE TITLE
[maybe a BUG] There is a chance notes open with Omnisearch don't always persist properly in a history of opened notes

### ISSUE THREAD

**Issue by beetrootpaul** [scambier/obsidian-omnisearch#145]
yes, I know how unhelpful such issue description is 😅 But I decided I want to mention my suspicions, since maybe other people observed something similar but were not aware of it 🤔 

**Problem description:**

So, here goes a very unhelpful description: Sometimes, when I navigate to perviously visited note with Opt+Cmd+Left, the one I really visited last does not open. Imagine a parent note (let's say a "Career Path") with some text and links (like job boards, things to check, etc.) Among those links are links to children notes (for each company I apply to). My typical workflow is to find the parent note with Omnisearch, then click on some of children links, edit some stuff there, then Opt+Cmd+Left back to the parent note.

Sadly, sometimes (quite often) I find myself in a wrong place. My suspicion (maybe totally wrong!) is that Omnisearch is the only navigational action I take and it seems to correlate with holes in the navigation history. As if sometimes page visited by Omnisearch were added to the history and sometimes not.

Sadly, I was never focused on analysing this enough to make clear whether my hypothesis is valid or not.

What I did today is: I disabled Omnisearch and enabled back native Quick Switcher. So far navigations seems to behave in an expected manner.

**Your environment:**

- Omnisearch version: 1.8.1
- Obsidian version: 1.0.0 (will update the most recent one now)
- Operating system: macOS 13.0.1
- Number of notes in your vault (approx.): 8185 files, but might be there are some `node_modules` somewhere deep, inflating the files number to an astronomical value
- Other plugins that may be related to the issue: AidenLx's Folder Note, Dataview (used in thet parent note, but children links I am clicking are made by hand, outside Dataview area), DB Folder (although I do NOT use it in those files), Linter, Quick Explorer

**Comment by beetrootpaul** [comment]
OK, now I finally got the same issue with Omnisearch **disabled** 🤷‍♂️

**Comment by scambier** [comment]
I must say that I enjoy seeing an issue close itself _while_ I'm reading it 😅
