### ISSUE TITLE
[BUG]The Chinese search untrustworthy

### ISSUE THREAD

**Issue by zackzeng00** [scambier/obsidian-omnisearch#149]
The Chinese search support of the plugin is very weak.
It is basically in an untrustworthy state.
Many of the explicitly included ones are not searchable.
Is there expected support for Chinese search?
**Problem description:**

**Your environment:**

- Omnisearch version: 1.9.0
- Obsidian version:1.0.3
- Operating system: macos 13.0.1
- Number of notes in your vault (approx.): less than 1000
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Have you installed the required plugin? https://github.com/aidenlx/cm-chs-patch

**Comment by zackzeng00** [comment]
Just tried to install it.
So far. Combined with this plugin, the effect is barely improved

**Comment by scambier** [comment]
I'll need concrete examples of it not working to see what I can do 👍

**Comment by zackzeng00** [comment]
[case1](https://share.cleanshot.com/z8xtyr)
[case2](https://share.cleanshot.com/DNvf6W)
[case3](https://share.cleanshot.com/IIFLN8)

**Comment by scambier** [comment]
Could you copy paste the texts too? Thank you

**Comment by zackzeng00** [comment]
case1:进口

**Comment by zackzeng00** [comment]
case1:进口
case2:再见
case3:中国

**Comment by scambier** [comment]
I mean the whole texts 😅 so that I can create notes and analyse how the search behaves

**Comment by zackzeng00** [comment]
| 1    | 2    | 3      |
| ---- | ---- | ------ |
|      |      |        |
| 中国 | 美国 | 加拿大 |

输入了｜ 加一个tab自动补齐语法

必须安装了 插件
------
case3 can search
-------
## About
Title: [[艾瑞咨询-2022年中国餐饮经营参数蓝皮书-220314.pdf]]
Authors: [[pdf.dfcfw.com]]
Category: #articles
Number of Highlights: ==15==
Readwise URL: https://readwise.io/bookreview/16361090
Source URL: https://pdf.dfcfw.com/pdf/H3_AP202203141552559209_1.pdf?1647270576000.pdf
Date: [[2022-07-08]]
Last Highlighted: *2022-06-28*

---

## Highlights

2021年中国餐饮行业主要成本营收占比及利润率情况 ^338739536

Note: 食材成本 30-40%
人力成本15-20%
租金成本10-15%
水电成本3.5%
营销成本2%
Update:2022-06-28

---

2020&2021年中国餐饮各业态无会员体系门店存活率 ^338739535

Note: 各类目平均存活率25+%
Update:2022-06-28

---

2020&2021年中国餐饮各业态有会员体系门店存活率 ^338739534

Note: 各类目平均存活率 80%+
Update:2022-06-28

---

2021年中国餐饮行业各业态店均坪效&品效 ^338739533

Note: 坪效果：元/平米/年
烧烤：9782
茶饮：23366
西式快餐：18614
中式快餐：12337
火锅：5877
中式正餐：11514
小吃：15648
粉面：11646
店均品效（元/单品/年）
烧烤：7462
茶饮：3979
西式快餐：7397
中式快餐：10053
火锅：8435
中式正餐：8275
小吃：10492
粉面：6511
Update:2022-06-28

---

月度门店平均盈亏平衡点均保持在50%-80%区间，其中中式快餐盈亏平衡点营收占比最低，在53.3%左右 ^338739532

---

茶饮、中式快餐、小吃、粉面以及西式快餐营业额位居5万元左右 ^338739531

---

2021年各个业态营业额相较于去年均稳步上升，火锅、烧烤、和中式正餐业态平均单店营业额均突破10万元大关 ^338739530

---

2018年中国餐饮市场连锁化率为12.8%，2020年提高至15% ^338739529

---

限额以上餐饮业法人企业是指年主营业务收入200万元及以上的餐饮业统计单位 ^338739528

---

我国限额以上餐饮业法人企业数量由2016年的2.64万个增长至2020年的3.29万个，餐饮业年末从业人数也由2016年的221.1万人扩增至2020年年末的257.7万人 ^338739527

---

我国城镇就业人员调查取得的周平均工作时长由2016年的46.1小时/周拉长至2020年的46.8小时/周， ^338739526

---

居民人均食品烟酒支出由2017年的5373元增长至2021年的7178元，而居民人均食品烟酒支出占比稳定在29%左右 ^338739525

---

但受制于经济增速放缓、疫情阻断等因素影响，居民消费支出占比呈下降态势，由2017年的70.5%下降至2020年的65.9% ^338739524

---

我国居民人均年可支配收入由2017年的接近2.6万元增长至2021年的超过3.5万元 ^338739523

---

2016年我国餐饮行业收入为3.58万亿元，2021年餐饮业行业收入回暖至疫情前水平达到4.68万亿元，我国餐饮行业收入年复合增长率为5.5% ^338739522

---
can't search

**Comment by zackzeng00** [comment]
can i have your email.
i can send my file to you

**Comment by zackzeng00** [comment]
done
you can check your email

**Comment by zackzeng00** [comment]
done
check your email you can

**Comment by scambier** [comment]
Fixed and published
