### ISSUE TITLE
Ignore Case in File Search

### ISSUE THREAD

**Issue by 130ariel** [scambier/obsidian-omnisearch#153]
Hi! Is there an option to ignore case when searching in the current file? I want the search query "Hello" to show results for "hello".

**Comment by scambier** [comment]
The case _is_ already ignored

**Comment by ooloth** [comment]
> The case _is_ already ignored

When I make a lowercase search for a word that appears 8 times in a file (5 times lowercase, 3 times uppercase), the **vault** search reports 8 matches in that file. ✅  

However, when I highlight that file in the vault search results and press tab to switch to the **file** search, there are only 5 matches (just the lowercase ones). ❌ 

@scambier Could this issue possibly be reopened? It would be great if the file search could return the same matches for a file as the vault search does.

**Comment by scambier** [comment]
https://github.com/scambier/obsidian-omnisearch/issues/261#issuecomment-1650976247

The file results are grouped together; if 2 matches are close enough ( = roughly if they can fit in the same excerpt), they are merged into a single result in the list.

**Comment by ooloth** [comment]
Ah, interesting. I don’t see multiple hits highlighted in any of the excerpts, but I believe you. :)

I’ve also confirmed that I see the same five in-file results regardless of the case of my search string, so sorry about that! I made the wrong assumption about why I wasn’t seeing what I expected.

**Comment by scambier** [comment]
There might be an issue with highlighting though, I'll take a look :)
