### ISSUE TITLE
[Feature request] limit search to pdfs 

### ISSUE THREAD

**Issue by joniac1** [scambier/obsidian-omnisearch#154]
Hi, thanks for your contribution to the obsidian community, 

Actually the plugin search in pdfs and in other file types. It would be great to limit the search process to only pdfs. 

Regards,

Joniac

**Comment by sstar0016** [comment]
If we could write in identifiers similar to how it is done in windows (".png" only searches files with the .png extension etc) that would be really cool

**Comment by scambier** [comment]
Deployed in beta, results will automatically get filtered when you add ".pdf" (or any other extension) in the query field.

**Comment by joniac1** [comment]
Thanks for your answer, unfortunately it does not work for me, it searches on all my .md files even if I type ".pdf" in the search bar ...

**Comment by scambier** [comment]
Have you updated Omnisearch to 1.12.0 (and I'm noticing I forgot the `-beta` suffix...)? It's working as intended for me

**Comment by joniac1** [comment]
Hi, thank you, it works 👍  . I had to install brat, update, install the plugin text extractor, and wait for the indexation of my files.

**Comment by joniac1** [comment]
It would be great to have a different icon for pdf et md files. 

And now, I have another issue, I can't preview anymore my files :/
