### ISSUE TITLE
[BUG] obsidian-text-extract seems to be gone...

### ISSUE THREAD

**Issue by tmaier** [scambier/obsidian-omnisearch#156]
**Problem description:**

This plugin states in the README, that it depends on obsidian-text-extract

- The repository at https://github.com/scambier/obsidian-text-extract is gone
- The NPM package at https://www.npmjs.com/search?q=obsidian-text-extract is also gone

**Your environment:**

- I checked version as of commit ed646eba7fee7874f2e22ef7d5c6b89ba544098f

**Expected outcome**

- Either the package and repository exists or if not: Update README and `package.json`

**Comment by scambier** [comment]
Yep, I'm refactoring the lib into a plugin (easier to maintain/update/etc). I edited the README.
