### ISSUE TITLE
[Feature request] Include Canvases in search results

### ISSUE THREAD

**Issue by beetrootpaul** [scambier/obsidian-omnisearch#157]
**Is your feature request related to a problem? Please describe.**

I just updated Obsidian to 1.1 (more specifically `v1.1.9`) and created my first canvas. Then, I navigated to another file (with use of Omnisearch) and later I wanted to go to that canvas again. I typed its name in Omnisearch, but it didn't show among top results.

**Describe the solution you'd like**

To have canvases matched by title same as regular notes.

**Describe alternatives you've considered**

(no alternatives)

**Additional context**

- Obsidian v1.1.8
- Omnisearch 1.9.1

**Comment by beetrootpaul** [comment]
extra bit of info:

I took a look how canvases are treated by Quick Switcher. Apparently it required me to enable "Show attachments" config option (see screenshot below) to have canvas listed among search results. So, on one hand, it might be a hint how to do it in Omnisearch: also add "show attachments" toggle.

On the other hand… I am really unhappy with canvases being treated as attachments. Maybe it's just me "wrongly" getting into mindset of treating canvases as regular pages, and not as images, PDFs, etc. I totally understand my need might be very tailored to my needs. Still, I would prefer canvases to be included and other "attachment" files – not 😛 


<img width="1111" alt="screenshot 2022-12-21 at 10 40 10" src="https://user-images.githubusercontent.com/92947323/208873686-e4ae1dab-8d9c-447b-a091-330270dd0053.png">

**Comment by beetrootpaul** [comment]
hah, I found a workaround! Strange, I am sure I was testing it yesterday before reporting this feature request here 🤔 Maybe I haven't restarted Obsidian back then, resulting with no index update? Nevertheless, the workaround (or maybe a proper solution as designed, even?) is:

**to add `canvas` as an additional file extension to index** (see screenshot below)

<img width="834" alt="screenshot 2022-12-21 at 10 43 59" src="https://user-images.githubusercontent.com/92947323/208874758-37a218c2-b453-4d9c-979f-812b5026d36f.png">

**Comment by scambier** [comment]
I've not yet had the time to dig into the canvas format, but I guess it's a valid workaround for now, since `.canvas` files are simply json.

**Comment by beetrootpaul** [comment]
Do I understand correct this is not released yet? Asking, because I thought it is, since closed status and see "ready to ship" label was removed as well 🙂  But on the other hand: my Omnisearch see no update and the last released version seem to be older than this PR's closing date

**Comment by scambier** [comment]
Ah yes it's still in beta. I'll probably make a release before Monday.

**Comment by beetrootpaul** [comment]
just updated and checked, works great, thx!
