### ISSUE TITLE
[BUG] Vietnamese search not working properly

### ISSUE THREAD

**Issue by nhangham** [scambier/obsidian-omnisearch#158]
**Problem description:**

I am having problems searching for notes in Vietnamese. I have tried toggling Ignore diacritics and Maximizing file name and alias weight but no luck.

Case 1:
[Screenshot_20221221_105658](https://user-images.githubusercontent.com/121146260/208820205-6f96bb0f-1751-4ba0-b528-03128ede38b3.png)
The search term perfectly matches the file name (2nd on the list) but results are unreliable.

Case 2:
[Screenshot_20221221_111204](https://user-images.githubusercontent.com/121146260/208820243-b05310c8-b596-45ff-bf59-f09a51743c1c.png)
In this case, the search term still matched but the file didn't show up.

Target files:

[TTSTN - Nhân sự tiềm năng.md](https://github.com/scambier/obsidian-omnisearch/files/10274472/TTSTN.-.Nhan.s.ti.m.nang.md)
[Hoàn thiện tài liệu đào tạo.md](https://github.com/scambier/obsidian-omnisearch/files/10274479/Hoan.thi.n.tai.li.u.dao.t.o.md)

**Your environment:**

- Omnisearch version: 1.9.1
- Obsidian version: 1.1.8
- Operating system: Windows 11 Pro 64-bit
- Number of notes in your vault (approx.): 3.200 files (mostly pdf and word), of which ~500 are notes 
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Hello, thanks for your report.

> Case 1:
> The search term perfectly matches the file name (2nd on the list) but results are unreliable.

What do you mean by "unreliable"? There is an issue with highlighting, but the file is returned in the results.

> Case 2:
> In this case, the search term still matched but the file didn't show up.

![image](https://user-images.githubusercontent.com/3216752/208865191-9227f24e-5fe9-4f0c-91e8-c8d6f827b647.png)

Looks ok to me (except highlighting). Make sure that "Ignore diacritics" is **disabled**.

I'll fix the highlighting issue asap.

**Comment by nhangham** [comment]
Thank you for your speedy reply.

Case 1: 
I agree that "unreliable" is vague. To be clearer, I meant I expect the note with the exact name that I searched for to be the first result (I have maximized the title and alias weight).
The highlighting issues also added to my impression of "unreliable".
I guess the ordering issue comes from my language's heavy reliance on diacritics. For example: nhan, nhàn, nhạn, nhãn, nhân, nhấn, nhận, nhặn, nhằn, nhẵn... each has different and multiple meanings (as they can be combined with others to form more complex words). I think an option to further increase title and alias weight and reduce content weight can help solve this problem.

Case 2: 
The target did not show up in my search result even though I have tried both exact name and name with no diacritics "TTSTN - Nhan su tiem nang"). If i used the shorter search term like you, it won't make the cut.
![image](https://user-images.githubusercontent.com/121146260/209050890-40eac6f7-bab3-448b-8f3f-129a7dfe0084.png)
![image](https://user-images.githubusercontent.com/121146260/209050951-a47074a5-6def-44d1-aca7-5506fa41ccf6.png)

I have tried toggling Ignore diacritics but no luck. It is currently disabled.

**Comment by scambier** [comment]
- You can now set the weightings values between 1.0 and 5.0
- The title not correctly highlighted will be fixed for the next release

I think the scoring issues indeed come from "nhan" and its variations. When searching for "Nhân sự tiềm năng", it's totally possible that a note different than the one titled "Nhân sự tiềm năng" will be ranked higher simply because it contains more "nhan" in one of the indexed fields.

> Also, here the plugin matched the wrong word ("xang") to "năng" in my search term

That's the fuzzy search doing its thing, it matches close words (with a lower rating)

**Comment by nhangham** [comment]
Thank you very much for your response. I love the plugin.
