### ISSUE TITLE
[Feature request] Order results by modification date of note, or alphabetically

### ISSUE THREAD

**Issue by KierPrev** [scambier/obsidian-omnisearch#16]
This is particularly useful when searching through daily notes, and have them chronologically.

**Comment by scambier** [comment]
Omnisearch's main feature is (IMO) the relevancy achieved through weighted results. This feature request has no real added value compared to Obsidian's core search plugin.

**Comment by KierPrev** [comment]
I understand why it makes sense! Thank you
