### ISSUE TITLE
[BUG] can't index and find inside pdfs

### ISSUE THREAD

**Issue by valentinosant** [scambier/obsidian-omnisearch#163]
Hi,
PDFs are not indexed and I can't find anything in the text of OCRed pdfs. Tried to restart and reinstall everything multiple times, pdf indexing is enanled in settings but I can't find anything in my pdfs.
Thanks

- Omnisearch version: 1.9.1
- Obsidian version: 1.1.8
- Operating system: MacOS Ventura
- Number of notes in your vault (approx.): 5 (test vault)
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Hello, the texts is extracted from the PDF data, OCR is only used for image files. Are your PDFs documents, or just pictures?

**Comment by valentinosant** [comment]
Hi and thanks for the reply, mine are PDFs documents, I pointed the fact that those pdfs are OCR-pdfs so are already searchable, text inside the pdf.
It looks like I have no indexing, or if I have anything is found.
Thanks again

**Comment by scambier** [comment]
To quickly check if the text extraction has worked, you can
- cmd+shift+i to open the developer tools,
- open the "Application tab"
- Go into Storage > IndexedDB > obsidian-text-extract/cache/xyz > pdf
- Check if your PDFs are in the table, and if they have a "text" value

![image](https://user-images.githubusercontent.com/3216752/209326685-177a55e7-cfed-415f-aa58-808dce699491.png)

**Comment by valentinosant** [comment]
All my pdfs are in the table but _text_  value is always empty:
<img width="102" alt="immagine" src="https://user-images.githubusercontent.com/116840329/209331419-90002522-967c-4d61-94a0-42957e206d4e.png">

**Comment by scambier** [comment]
It means the library I use to extract text didn't succeed.

I'm not familiar with macOS, but when you say that those PDFs are "OCRed", you mean that macOS used a feature called "Live Text" on them? Are those PDFs simple photographs of documents?

**Comment by valentinosant** [comment]
They are not photographs/scans, I can select text and copy/paste without problems.
That is what I was meaning.

**Comment by scambier** [comment]
Anyway, the lib can't extract it for some reason. I have long-term plans to use OCR on PDFs that are difficult to process, but in the meantime, there's nothing I can do here, sorry :/

**Comment by valentinosant** [comment]
The strange thing is that these pdfs are correctly indexed in all other application I use without issues, I suspect there is an issue with the plugin in my installation. If you like to we can arrange somewhere (mail/telegram/matrix etc) and I send you one of these.
Thanks for your kindness btw.

**Comment by scambier** [comment]
You can send me an email to simon.cambier [at] proton.me, thank you 👍

**Comment by scambier** [comment]
As I said in the email: the pdf processing lib encountered an error while parsing the file, and just aborted the process. I have a few other solutions to try in the long term, but no solution for the short term, sorry.

**Comment by RuslansAleksejevs** [comment]
@valentinosant 
Hey, did you find a way to solve that at the end?

**Comment by scambier** [comment]
> sorry bus is this plugin jup to pdf page or not?

Nope, sorry

**Comment by xmaxrayx** [comment]
@scambier I see thx for fast replay was confusing

**Comment by valentinosant** [comment]
> @valentinosant Hey, did you find a way to solve that at the end?

Hi, I'm no longer an obsidian user. I apologize I can't be of help.
