### ISSUE TITLE
[Feature request] Add a button to switch to In-file Search on mobile

### ISSUE THREAD

**Issue by sohanglal** [scambier/obsidian-omnisearch#164]
**Is your feature request related to a problem? Please describe.**
Is in-file Search available on mobile? I checked all the settings and past issues but couln't find it mentioned anywhere. 

**Describe the solution you'd like**
A button to search in-file right next to the create note button 

**Describe alternatives you've considered**
I really prefer omni search over obsidian search

**Comment by scambier** [comment]
In-File search is available on mobile (there's a dedicated "Omnisearch: In-File search" command), but there is currently no way to switch between Vault and In-File

**Comment by sohanglal** [comment]
Adding a button to switch between Vault Search and in-file search would really help. Thanks a lot for your efforts!
