### ISSUE TITLE
[BUG] Failed to load plugin omnisearch

### ISSUE THREAD

**Issue by MyAnivia** [scambier/obsidian-omnisearch#167]
Failed to load plugin omnisearch
I use "Obsidian Dev Tools Plugin: Toggle Console" to get log.
![Snipaste_2023-01-09_01-06-32](https://user-images.githubusercontent.com/120353247/211209376-35d91c66-bb3c-4aea-8f98-932768bcc8b0.jpg)

**Comment by scambier** [comment]
There's a nice (and short) template when filling out a bug, that asks for a few important questions:
- Omnisearch version:
- Obsidian version:
- Operating system:

**Comment by MyAnivia** [comment]
Sorry，It's my fault.
Omnisearch version: 1.9.1
Obsidian version: 1.1.8
Operating system: Windows 10 家庭中文版 版号21H2

**Comment by scambier** [comment]
Could you please try the 2 test builds in this post, and tell me if one (or both) of these work? https://github.com/scambier/obsidian-omnisearch/issues/137#issuecomment-1347320335

**Comment by MyAnivia** [comment]
[omnisearch 137 dynamic.zip](https://github.com/scambier/obsidian-omnisearch/files/10211979/omnisearch.137.dynamic.zip)，this verision can load，so i dont continue trying the next verision.
Unfortunately，i found a problem or disadvantage in this version. #168

**Comment by MyAnivia** [comment]
I maybe know the reason it cant be load，i guess official's plug download exists bug in some situation. 
Because i meet same question in another plug，I found it lost main.js，but offcial tell me download it successful.
So i download main.js，that plug can be load normally.

**Comment by scambier** [comment]
You can try downloading the latest version directly from here then https://github.com/scambier/obsidian-omnisearch/releases/tag/1.9.1

**Comment by scambier** [comment]
[It looks like you were able to sideload the latest version](https://github.com/scambier/obsidian-omnisearch/issues/168#issuecomment-1375905851), so the original issue was likely a bug from Obsidian while downloading the plugin, and not within the plugin itself.
