### ISSUE TITLE
[Feature request] Ability to change keybindings within the search window

### ISSUE THREAD

**Issue by KTM25** [scambier/obsidian-omnisearch#171]
Request: 
The current keybindings within the search window are fine, but the ability to change them would be better and to suit multiple preferences depending on the individual. 

For example: 
After opening a search to move down, I need to move my hand to my mouse or to the arrow keys if they exist on my keyboard. 

Solution:
Being able to change the keybindings within the search popup so I could change navigating to Ctrl + N or to Ctrl + P (to go with prior example) for easier navigation. This would allow the ability for further customization for the user and how they may move around the Obsidian window.

**Comment by scambier** [comment]
For your specific example, ctrl+n/p and ctrl+j/k already work if you have vim mode enabled

**Comment by scambier** [comment]
Closing this in favor of #274
