### ISSUE TITLE
[BUG]Loading index Error :Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zdwzdw1983** [scambier/obsidian-omnisearch#174]
**Problem description:**
Loading index Error :Maximum call stack size exceeded
![image](https://user-images.githubusercontent.com/14261220/211962843-6fda0b59-0a32-4393-ab70-202f082db74c.png)

**Your environment:**

- Omnisearch version:1.9.2/1/10.0-bata.4
- Obsidian version:1.1.9
- Operating system: windows 11 
- Number of notes in your vault (approx.): 
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Is this issue still happening? Does it happen when Omnisearch is the only plugin active?

**Comment by zdwzdw1983** [comment]
yes，when  only Omnisearch active ，this issue  still happening
![image](https://github.com/scambier/obsidian-omnisearch/assets/14261220/6db1a16b-28ab-42f7-9758-33f7a05c9c0f)
![image](https://github.com/scambier/obsidian-omnisearch/assets/14261220/fd313579-143a-4643-bf11-55bf3d61fdcb)
 Obsidian  v1.2.8

**Comment by scambier** [comment]
Closing this as I was never able to reproduce the issue. Feel free to reopen if you have a reproducible case
