### ISSUE TITLE
[Feature request] Open results in new tab

### ISSUE THREAD

**Issue by mutachre** [scambier/obsidian-omnisearch#175]
Surely this can be worked around with keyboard shortcuts, but I would find it very useful to include a **setting** that could allow me to open Omni **search results in new tab by default**. I always find it inconvenient that the result I open goes to replace the tab I am working in. Thank you!

**Comment by iafisher** [comment]
Hello, I'm interested in working on this. It looks like it would be a straightforward change to `src/components/modals.ts`. Can I start working on a PR?

**Comment by scambier** [comment]
Sure, go ahead :)
