### ISSUE TITLE
[Feature] Index CamelCaseWords as 3 different tokens

### ISSUE THREAD

**Issue by MartinP7r** [scambier/obsidian-omnisearch#176]
**Problem description:**

Possibly faulty fuzzy search logic?
Please see below search results for similar terms within the same vault. I would expect `Timelines` to also show the result shown for `reloadTimelines`.

<img src="https://user-images.githubusercontent.com/2669027/212616603-9d3fb246-0c40-483e-84fa-47ffe22d0b4a.png" />|<img src="https://user-images.githubusercontent.com/2669027/212616609-331b4aa4-6561-4cbe-8434-8f1815117df4.png" />

**Your environment:**

Please add to the bug template how to find the current version.  
I have everything updated to latest.

- Omnisearch version: 
- Obsidian version: 
- Operating system: macOS Ventura
- Number of indexed documents in your vault (approx.): 2000

**Things to try:**

- Does the problem occur when Obsidian is the only active community plugin:  not tested 
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  yes
- Does the problem occur after a cache reset: yes

**Comment by scambier** [comment]
[That's a limitation of Minisearch](https://github.com/lucaong/minisearch/issues/67), the library used by Omnisearch. You can't do partial matching (if not a prefix).

The fuzzy matching works with the Levenshtein distance algorithm, and `timelines` is too different from `reloadTimelines`.

**Comment by MartinP7r** [comment]
Oh, interesting. So, according to that algorithm, `Timelines` is closer to `pipelines` than `reloadTimelines`? There's no way to set it up to account for partial matches or even search with wildcards?  

Anyway, thank you for the quick answer!

**Comment by scambier** [comment]
Actually it might be interesting to have an opt-in option to index "CamelCaseWord" as "Camel"+"Case"+"Words"

**Comment by scambier** [comment]
Deployed in 1.13.0-beta.1
