### ISSUE TITLE
After once of using Alt-Enter to expand results and clicking Esc, arrow navigation no longer works

### ISSUE THREAD

**Issue by esm7** [scambier/obsidian-omnisearch#18]
**Type of issue**

- [x] A bug
- [ ] A performance problem

If I use Omnisearch, navigate with the arrows to a result, press Alt+Enter to expand and go back with Esc, arrow navigation completely stops working.
Not just for that dialog, but for all subsequent opens of Omnisearch until Obsidian is restarted.

**Your environment**

- Operating system: Linux Manjaro
- Number of notes in your vault (approx.): 400
- Version of Obsidian: 0.14.6
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Sorry about that, it should be fixed and published now 👍
