### ISSUE TITLE
[BUG] Switching from in-file search to vault search loses search term

### ISSUE THREAD

**Issue by harmtemolder** [scambier/obsidian-omnisearch#180]
**Problem description:**

1. Open "Omnisearch: In-file search"
2. Search for something, e.g. "omni"
3. Press <kbd>tab</kbd> to switch to "Omnisearch - Vault"
4. The search term (e.g. "omni") is gone

(The other way round, as described [here](https://github.com/scambier/obsidian-omnisearch/issues/117), does work.)

**Your environment:**

- Omnisearch version: 1.10.0
- Obsidian version: 1.1.9
- Operating system: Linux (Manjaro)
- Number of indexed documents in your vault (approx.): 4000

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  Yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files: Yes
- Does the problem occur after a cache reset: Yes

**Comment by scambier** [comment]
Fixed in 1.14.0-beta.1

**Comment by harmtemolder** [comment]
I installed the beta version, and confirm that this works now. Thanks!

It works different from what I expected: I expected it to remember the initial file I searched in, instead of searching in the file of the highlighted search result, but the latter actually is more useful. It would be helpful if the in-file search showed what file you are searching in, somewhere in the UI. What do you think?
