### ISSUE TITLE
[BUG] Uncaught exception during indexing: cannot read path from undefined

### ISSUE THREAD

**Issue by kithairon** [scambier/obsidian-omnisearch#181]
**Omnisearch repeatedly stating that it is indexing though nothing happens:**

Updated to 1.10.0 a few days ago. Since then Omnisearch does not find anything but states it is in need of indexing.
There is no progress visible in the number of files to be reindexed. Tried re-installing, restarting Obsidian to no avail.

Console log: please see attached screenshot

**Your environment:**
macOS 12.6.2
Obsidian v1.1.12
Omnisearch 1.10.0

Vault has 1700+ .md files.
- Number of indexed documents in your vault (approx.):  have emptied the cache, currently 0 (Prior to updating to v1.10: about 1776; since updating to v1.10: 0)

I do not index pdfs or any other non-notes files.
 
**Things tried:**
- Does the problem occur when Omnisearch is the only active community plugin:  yes 
- Does the problem occur after a cache reset:  yes
[Bildschirmfoto 9.pdf](https://github.com/scambier/obsidian-omnisearch/files/10428594/Bildschirmfoto.9.pdf)

**Comment by scambier** [comment]
Thanks for the detailed report. Could you please try this test build, and report back console logs if there are still issues? Thank you.

This is an un-minified build, so the main.js file is larger than the release build
[omnisearch 181 fix 1.zip](https://github.com/scambier/obsidian-omnisearch/files/10429347/omnisearch.181.fix.1.zip)

**Comment by kithairon** [comment]
Thanks for your build. Sorry to report the issue persists after installing and restarting. Attached a screenshot of log and omnisearche's message. 
[Bildschirmfoto 11.pdf](https://github.com/scambier/obsidian-omnisearch/files/10431160/Bildschirmfoto.11.pdf)
Thanks for your efforts.

**Comment by wzajchow** [comment]
I have the same issue with the same symptoms

**Comment by scambier** [comment]
New tentative fix: [omnisearch 181 fix 2.zip](https://github.com/scambier/obsidian-omnisearch/files/10438399/omnisearch.181.fix.2.zip)

**Comment by kithairon** [comment]
Thanks for v181 fix 2. It works – my 1776 files were indexed in a breeze – I was to slow to do a screenshot of the confirmation message but definitely saw it flashing by. After a few test searches all looks good. Thanks for your efforts!
