### ISSUE TITLE
Cannot Update/Install Omni Search after last update[BUG] 

### ISSUE THREAD

**Issue by mahadevan** [scambier/obsidian-omnisearch#185]
Cannot Update/Install Omni Search after last update.

update fails, so i uninstalled & tried to install back again. Same error. It says failed to install.

went to obsidian plugin directory. There was no omni search folder.

unable to install omni search now.

also uninstalled "text extractor" plugin to see if it has conflict with omni search.

screenshot : 

![image](https://user-images.githubusercontent.com/2020804/213623252-0a0fb623-1c6b-4fa7-9219-e26dc25a7fca.png)

**Comment by scambier** [comment]
That should be fixed now, I botched a rollback. If you still have the error, you should restart your computer to clear the cache.
