### ISSUE TITLE
[BUG] Crash while indexing with TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by Sanqui** [scambier/obsidian-omnisearch#186]
I'm getting the following crash during indexing:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'path')
    at eval (plugin:omnisearch:40:42298)
    at Array.filter (<anonymous>)
    at FV.addFromPaths (plugin:omnisearch:40:42260)
    at async fE (plugin:omnisearch:47:6949)
    at async eval (plugin:omnisearch:47:5764)
```

I'm not sure how to identify which file is at fault, but it is blocking me from using Omnisearch completely.  Temporarily using the built in quick switcher :)

Omnisearch version 1.10.0 \
Obsidian version v1.1.9

**Comment by scambier** [comment]
Probably the same (fixed) issue as https://github.com/scambier/obsidian-omnisearch/issues/181

The fix is also deployed in [beta](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.11.0-beta.1). I'll release it asap in production

**Comment by Sanqui** [comment]
Oh, sorry about the duplicate.  I checked closed issues but missed this one, and I even tried searching for the error, but the result didn't show up :sweat_smile:

**Comment by scambier** [comment]
np :)
