### ISSUE TITLE
Support a custom toggle excerpts keybinding

### ISSUE THREAD

**Issue by Destaq** [scambier/obsidian-omnisearch#191]
**Is your feature request related to a problem? Please describe.**

When using Omnisearch and toggling excerpts on MacOS, there is a command conflict. One of the default Mac shortcuts for delete is Control-H ([see here](https://support.apple.com/en-us/HT201236)), and so whenever I toggle cases in the search pane, one letter from the search query also gets deleted.

**Describe the solution you'd like**

It would be great to have an option in the plugin's settings / Obisidan hotkeys to change Control-H to something else.

**Describe alternatives you've considered**

I went into the Mac Settings, and there is no way to modify this specific keybinding there. I then tried to create a custom `Keybindings/DefaultKeyBindings.dict` file that mapped Control-H to no operation, but this was either unsuccessful or crashed Obsidian.

**Additional context**

https://user-images.githubusercontent.com/61620873/216777421-47ef9162-4ac1-4543-a8b6-c1927dcc0fc2.mp4

**Comment by scambier** [comment]
Related to #171

**Comment by scambier** [comment]
Closing this in favor of #274
