### ISSUE TITLE
[BUG] Characters are not highlighted/underlined for non-english characters

### ISSUE THREAD

**Issue by charleshan** [scambier/obsidian-omnisearch#195]
**Problem description:**
Characters are not highlighted/underlined for non-english characters. Below is a screenshot for Korean. The same problem occurs in Chinese and Japanese.
![ScreenCapture 2023-02-12 at 19 06 12](https://user-images.githubusercontent.com/3143154/218361374-5a4c2c08-a9f6-4792-96bd-f67a73e253da.png)
Here's an example text for testing: 안녕하세요

**Expected results:**
![ScreenCapture 2023-02-12 at 19 16 04](https://user-images.githubusercontent.com/3143154/218362527-8c70959d-c1cb-47f1-a178-d40d765cf851.png)

**Your environment:**

- Omnisearch version: v1.12.0
- Obsidian version: v1.1.9
- Operating system: MacOS 13.0.1
- Number of indexed documents in your vault (approx.): 3000

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  Yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Yes
- Does the problem occur after a cache reset: Yes

**Comment by iAurora** [comment]
I'm having the same issue with Cyrillic characters for some reason. Latin ones are highlighted as expected.
<img width="359" alt="Screenshot 2023-02-15 at 01 35 10" src="https://user-images.githubusercontent.com/347206/218879304-2c491479-4883-4726-9ae5-21b04695ac36.png">

**Comment by scambier** [comment]
@charleshan this additional plugin is required for CJK languages: https://github.com/aidenlx/cm-chs-patch

![image](https://user-images.githubusercontent.com/3216752/219945328-4e73df6a-676f-4394-8407-d47c3b5a0327.png)

@iAurora for cyrillic chars, the bugfix will be deployed with next release

**Comment by charleshan** [comment]
That's interesting. I wasn't aware of the concept of CJK Characters. I just mentioned them because, from the language I'm aware of, I know that they're sufficiently different than english and I guessed that they would have the same problem.

I checked out the repo you mentioned. From looking at your screenshot, it seems to solve this problem but their demo shows something completely different. The repo is for solving a different problem: Separating words in a sentence without spaces.

Can you try creating a file with ❓ and try searching for it? It has the same problem. I use ❓ for question marks because Android doesn't support question marks in file names.

**Comment by charleshan** [comment]
> That's actually the same problem

Are you sure about this? Can you take another look? Your latest update almost solved the problem [^1]. I didn't download any additional plugins. My guess was that adding regex match for non-ascii characters would solve this problem but you're the expert here :)

![ScreenCapture 2023-02-20 at 12 10 11](https://user-images.githubusercontent.com/3143154/220190836-b8e449a6-ae68-42f3-9721-c9e59679f17c.png)
This looks perfect!

![ScreenCapture 2023-02-20 at 12 09 42](https://user-images.githubusercontent.com/3143154/220190779-ec138c14-9b9f-44c0-8bdc-9970702ddf8c.png)
It doesn't seems to highlight when the search term is the first word (filename or content).

Filename: 유니코드 국제 회의
Content: 세계를 향한 대화, 유니코드로 하십시오. 제10회 유니코드 국제 회의가 1997년 3월 10일부터 12일까지 독일의 마인즈에서 열립니다. 지금 등록하십시오.
Search terms: 국제, 유니코드
