### ISSUE TITLE
Consider the directory path to be an indexable part of the title

### ISSUE THREAD

**Issue by preslavrachev** [scambier/obsidian-omnisearch#196]
One of my vaults uses a nested directory structure of folders with notes. Partially, I use the directory names for search purposes. Here is one example:

```
/Snippets/Python/An Interactive Plot with Plotly
```
The default Quick Switcher takes the entire path into consideration. Omnisearch doesn't. Thus, I'd usually have to repeat myself in the note title:

```
/Snippets/Python/Python - An Interactive Plot with Plotly
```

It is not that much of a big deal, but it would be great if Omnisearch took the entire path to a given note and made it part of the search index too. How feasible is that?

**Comment by preslavrachev** [comment]
Thank you so much! Can't wait to see this change in an official release. One question - can I try out a beta release of Omnisearch while using the stable one too? I suppose, I can simply disable the stable release and it won't mess with my settings.

**Comment by scambier** [comment]
You can't install both, since the plugin id is the same for beta and stable. I'll probably publish the next stable this weekend.

**Comment by preslavrachev** [comment]
OK, no rush. I am looking forward to checking it out. I am drafting a small
blog post about how I use Obsidian, and there is a section about Omnisearch
as well. I will postpone the publishing until the version makes it out.

Once again, many thanks for your effort!
