### ISSUE TITLE
[Feature request] Regex support

### ISSUE THREAD

**Issue by zanodor** [scambier/obsidian-omnisearch#199]
Hi buddy,

I was searching for this request and couldn't find it. Do you have anything against it?  
I would be faster to have range/proximity search results in a hefty vault than in the basic/core vault search of Obsidian.  

Cheers

**Comment by scambier** [comment]
> I would be faster to have range/proximity search results

Could you provide an example? Not sure what you mean, or how it would be different than the core Search plugin

**Comment by scambier** [comment]
Omnisearch is not a drop-in replacement for the core Search plugin, it doesn't work the same at all. Omnisearch will match your query against an index of "words" to calculate a score and order results by relevance. See https://lucaong.github.io/minisearch/ for the internals.

I don't plan to add a regex search. It wouldn't bring anything over the core Search, and I'd have the same problems to solve regarding speed.
