### ISSUE TITLE
Feature Request - Ignore files and directories

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [scambier/obsidian-omnisearch#2]
This plugin would benefit greatly from being able to ignore files and folders (e.g. I have a song library that I'd like to exclude from searching). Ideally, starting a search with a character (specified in settings, potentially '?' by default) would search without exclusions.
There could be a toggle for each ignore to use regex or a plain file path

**Comment by TfTHacker** [comment]
excluding folders would be good. I have a large vault, and also some reference info. would prefer certain folders ignored. Also could be the same folders already excluded within the obsidian settings (this recent feature where obsidian will ignore predefined paths for things like search, etc)

P.S. thank you for your hard work on this plugin.

**Comment by scambier** [comment]
I just published 1.2.0 through BRAT.

Files present in Obsidian's "excluded files" are now downranked. I'll close this issue for now, but may (_will_) add more options in the future Settings page (#41), once it's done.
