### ISSUE TITLE
Trouble installing plugin (manually) - Solved!

### ISSUE THREAD

**Issue by ashhawk25** [scambier/obsidian-omnisearch#20]
**Type of issue**

- [X] A bug
- [ ] A performance problem

**Problem description**

I tried following the manual installation steps (downloading scambier.obsidian-omnisearch-0.2.3.zip from the releases page), unzipping, and then putting the folder in the obsidian plugins folder. 

But when going into Obsidian to activate the plugin it doesn't seem to show up. Tried re-loading the plugins, restarting Obsidian, using a previous version of the plugin (0.2.2), but no luck :-(

**Your environment**

- Operating system: Windows 10
- Number of notes in your vault (approx.): ~500
- Version of Obsidian: v.0.14.6 (says up to date)
- Other plugins that may be related to the issue: I don't think so, tried temporary disabling other plugins one by one, but didn't have a change

**Comment by scambier** [comment]
Do you have other community plugins installed? You must first deactivate the Safe Mode:
![image](https://user-images.githubusercontent.com/3216752/164957784-ade13bbd-95c8-4316-b75a-c9c7d9461d28.png)

Then the plugin must be installed this way:
![image](https://user-images.githubusercontent.com/3216752/164957801-eb725b2c-8987-44ca-a522-684df9880eda.png)
![image](https://user-images.githubusercontent.com/3216752/164957808-be1053b0-94ee-4747-be28-3a385233c562.png)

Omnisearch will then show up in the list after a refresh or a restart:
![image](https://user-images.githubusercontent.com/3216752/164957845-e7ef686e-b959-496f-b64b-dd3977aad560.png)

**Comment by ashhawk25** [comment]
I did have safe mode off bit on your 2nd screenshot it looks like there's a manifest.json file which I don't think was included in the "scambier.obsidian-omnisearch-0.2.3.zip" file.

After downloading that separately and putting it into the plugin folder, things showed up without a problem! :-)

**Comment by scambier** [comment]
And thanks for noticing, the manifest was not included because of an error in the build process
