### ISSUE TITLE
[Feature request] Optionally remove icons from search 

### ISSUE THREAD

**Issue by universvm** [scambier/obsidian-omnisearch#201]
**Is your feature request related to a problem? Please describe.**
As shown in the GIF omnisearch used to have no icons: 

https://raw.githubusercontent.com/scambier/obsidian-omnisearch/master/images/omnisearch.gif

Now this is what it looks like:

<img width="702" alt="Screenshot 2023-02-25 at 15 11 32" src="https://user-images.githubusercontent.com/17524568/221364606-82d5491d-0b5f-41b1-a9fe-a4e82167bd9b.png">

I believe this is related to this commit: https://github.com/scambier/obsidian-omnisearch/issues/107

But it is clear that this was a poor choice, for instance rather than taking up vertical space, the folder could be either on the right side of the panel, like the OP in the issue showed. Instead the only change was an icon, which does not add any explanatory power to the results. 

**Describe the solution you'd like**
A button to turn off the feature.

**Describe alternatives you've considered**

**Additional context**

**Comment by scambier** [comment]
> But it is clear that this was a poor choice

UI is hard ok ☹


Though I agree with the suggestion of adding a few layout options (no folder / on the same line / on a different line)

**Comment by universvm** [comment]
> But it is clear that this was a poor choice
> > UI is hard ok ☹

That's absolutely fine, I meant to say this solution seems to be poorer compared to the option proposed by the OP in the image:

![195159715-c3474591-c430-4957-8ca8-c8e2e6fefcc0](https://user-images.githubusercontent.com/17524568/221373453-7eba1ccc-579a-4008-a193-2dd01c37a55c.png)

Apologies if it sounded negative. UI is indeed hard!

> Though I agree with the suggestion of adding a few layout options (no folder / on the same line / on a different line)

Thanks!

**Comment by scambier** [comment]
(There was an issue with the message you quoted while I was writing it, it got deleted sorry)

I initially tried to put all the information on a single line, but fields were shifted around when the folder and/or filename were too long to fit on a single line (on top of the filetype and number of matches). I settled on 2 lines to ensure consistent results 🤷‍♂️

**Comment by universvm** [comment]
If possible it'd be good to be able to turn them off, eg. in my case I have very few folders and would rather use the vertical space for additional search results / more details.

**Comment by NeighNeighNeigh** [comment]
If you don't mind having no folder shown, you could use the following snippet to completely remove the 'Folder' line

```css
.omnisearch-result__folder-path {
    display: none;
}
```

**Comment by scambier** [comment]
Closing this, Omnisearch's appearance can be personalized with CSS snippets.

I can always add more classes to help you select specific elements if needed; just reopen this issue and ask here 👍
