### ISSUE TITLE
[Feature request] Command Option enter shortcut to open note in a new split pane

### ISSUE THREAD

**Issue by gavinmn** [scambier/obsidian-omnisearch#202]
I could have sworn this shortcut used to exist, but even after installing an old version I couldn't find it. Right now we have the option to:

- Open note
- Open note in new tab
- Create new note
- Create new note in new tab

But I'd love the Quick Open functionality of using Command + Option to open the selected note in a new split pane too.

**Comment by pricebaldwin** [comment]
I badly want this as well. I'm willing to look into implementing it if @scambier wants the feature.

**Comment by scambier** [comment]
> I badly want this as well. I'm willing to look into implementing it if @scambier wants the feature.

If the offer still stands, you're welcome to submit a PR for this :)

**Comment by Drakemoor** [comment]
This would be of great help.
