### ISSUE TITLE
[Feature request] Go from searching vault to in-file search on Mobile 

### ISSUE THREAD

**Issue by jamie9090** [scambier/obsidian-omnisearch#204]
**Is your feature request related to a problem? Please describe.**
Searching vault on mobile doesn't allow for then searching within the file. On desktop, you can achieve this via Tab.

**Describe the solution you'd like**
Swipe to switch to in file search, or have a button, or click and hold

**Comment by scambier** [comment]
Duplicate of https://github.com/scambier/obsidian-omnisearch/issues/164
