### ISSUE TITLE
[BUG] Minor UI issue. Tab icon shows tab and shift-tab. Shift-tab does nothing.

### ISSUE THREAD

**Issue by chris-lesage** [scambier/obsidian-omnisearch#205]
This is pretty minor. But in the Omnisearch window, it shows a multi-directional tab symbol ↹ for "to switch to In-File Search".

On keyboards, this icon indicates holding shift would un-tab. But shift-Tab isn't a hotkey in Omnisearch.

So the icon should likely just be ⇥ (Or alternatively, perhaps support shift-tab too. It would do the same operation, since it's just a toggle.)

Inspired from this forum post:
https://forum.obsidian.md/t/omnisearch-plugin-how-to-to-switch-to-in-file-search-using-keys/55740/2

**Comment by scambier** [comment]
Well https://en.wikipedia.org/wiki/Tab_key and it's the same symbol on my own keyboard 😅

I have no issue replacing it with ⇥, but it could even be clearer to just write `tab`?
![image](https://user-images.githubusercontent.com/3216752/222959210-c7dba523-3327-4f9a-b103-ba885b1d3bdc.png)

**Comment by chris-lesage** [comment]
Exactly, but like I said, the reason it shows both on your keyboard is because the upper one is the shift modifier. :)

![5E8559BB-D771-4169-BCD3-D1426FB653D1](https://user-images.githubusercontent.com/5263648/222968223-8711ede5-34be-4dda-8aad-e5aa5bf77ea0.jpeg)

“tab” would be nice and clear too.
