### ISSUE TITLE
[BUG] Obsidian freezes as soon as I start an Omnisearch query

### ISSUE THREAD

**Issue by viktoriakeller** [scambier/obsidian-omnisearch#208]
Obsidian freezes as soon as I start an Omnisearch query.

I open Omnisearch (Shift + Cmd + O) and start typing. Sometimes it freezes immediately (pic Freeze 1), sometimes a few letters can be typed, but then everything freezes afterwards (pic Freeze 2). 
I cannot end Omnisearch, and it doesn't change with waiting. The only solution is to force quit Obsidian

I deinstalled and re-installed Omnisearch. Now it is about 50% freezing and in the other 50% ist is extremely slowly (and freezes sometimes as well after showing some results).

Copying Console Logs doesn't work.

**Your environment:**

- Omnisearch version: 1.12.3
- Obsidian version: V1.1.16, (Installer version: v1.1.9)
- Operating system: macOS Ventura 13.2.1
- Number of indexed documents in your vault (approx.):  3565

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  yes
- Does the problem occur after a cache reset: yes

I really love Omnisearch - it really ramped my Obsidian workflow and it had worked until yesterday without any problem. I would be very thankful, if the bug r the problem could be solved.

<img width="1488" alt="Omnisearch_Freeze1" src="https://user-images.githubusercontent.com/74709696/224479397-732f7c39-324a-44b8-9b0f-40dee2c63b40.png">
<img width="1481" alt="Omnisearch_Freeze2" src="https://user-images.githubusercontent.com/74709696/224479398-28c8ca05-3cdc-49f6-9107-d35f147f05d0.png">

**Comment by scambier** [comment]
Hello, could you try a few things to help me pinpoint the problem?

- Does it freeze with _all_ queries? 
- Does it freeze when you disable the excerpts (ctrl+h)?
- Does it freeze on the sandbox vault?

Thank you :)

**Comment by viktoriakeller** [comment]
**Freezing with all queries**: I tried a few, but I didn't try anything systematically. 
- It seems that its more likely to freeze, when the search term occurs more often in my vault (e.g. I have a lot about psychology, when searching for "psy" it freezes immediately and does not end, I have to quit Obsidian // news: waited for ~5 minutes and results occurred)
- and less likely when a search term does not occur in my vault (e.g. "xöz", results are even shown immediately sometimes)
- with everything in between (medium occurring words) it is always slowly, and sometimes it freezes, sometimes results are shown after a (long) while
- freezing occurs mostly after typing 3 characters / it freezes after 3 characters are shown

**Freeze when excerpts are disabled**: yes

**Sandbox Vault**: no

Thank you for the fast response!

**Comment by scambier** [comment]
Thanks for the answers. In the meantime, enabling this Omnisearch setting will maybe help with the freezes

![image](https://user-images.githubusercontent.com/3216752/224484005-45caec71-3c7d-4478-82d4-6c7e6cb67455.png)

**Comment by viktoriakeller** [comment]
Thanks, but it doesn't change the problem.

**Comment by scambier** [comment]
I've added an opt-in verbose logging option in the [latest beta](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.13.0-beta.2), if you're willing to try that. It won't solve the issue but should hopefully help me find what's breaking.

To install it, you can simply download the .zip file and extract its contents in `path_to_your_vault\.obsidian\plugins\omnisearch`

To use it:
- Enable the option in Omnisearch settings
- Show the developer console with ctrl+shift+i, then click on the "Console" tab
- Start a search, and take a screenshot when it freezes

**Comment by viktoriakeller** [comment]
I hope that's how you wanted it.
I only typed a "g" accidentally and deleted it immediately, then typing "test".
First picture: console after omnisearch froze after typing the g
Second picture: console after waiting for a minute or two when it realized that I typed "test" instead.


<img width="1496" alt="Bildschirm­foto 2023-03-12 um 10 02 39" src="https://user-images.githubusercontent.com/74709696/224534961-abbc9112-1da3-41da-bee0-f833b3e004cb.png">
<img width="1496" alt="Bildschirm­foto 2023-03-12 um 10 06 02" src="https://user-images.githubusercontent.com/74709696/224535146-68e83792-89c4-4da6-8b95-15a41afefb65.png">

**Comment by scambier** [comment]
This test build should reduce the load times. [omnisearch 208 fix 1.zip](https://github.com/scambier/obsidian-omnisearch/files/10950577/omnisearch.208.fix.1.zip)

Are some (most?) of your files particularly large? It looks like Omnisearch is struggling to locate the search matches inside your notes. It eventually succeeds but that takes way longer than it should.

**Comment by viktoriakeller** [comment]
Thanks, so it is a little bit faster/less freezing now, but still not anywhere where it was a few days ago.
I don't know what you'd count as large. I have some videos (21 > 150MB) in my folder that are in the attachments folder - which could easily be excluded from search (ticking the "use excluded files from obsidian" where they are excluded, doesn't change the search).
No PDFs or other "larger" things, just markdown files, and not one of them is large.

I cannot remember that I've changed anything in my vault, that might have caused the freezing.

**Comment by scambier** [comment]
> Thanks, so it is a little bit faster/less freezing now, but still not anywhere where it was a few days ago.

Ok, I didn't understand that it was working correctly before that. Would you mind giving me another screenshot of the logs when Omnisearch is freezing? To check on which files it's choking. Thank you for your help :)

**Comment by viktoriakeller** [comment]
<img width="1496" alt="Bildschirm­foto 2023-03-12 um 17 05 21" src="https://user-images.githubusercontent.com/74709696/224557116-5b8f99bc-abda-4b92-9ea0-2075fa89bee1.png">

Oh, sorry for not making that clear, that it started a few days ago after using it for - I don't know, I think since it's available in the community "store". 

Atm it does not freeze for minutes any more, it is only a few seconds late. I took the picture in the small freezing window. I hope it can help you.

Thank you for your help!

**Comment by scambier** [comment]
> Atm it does not freeze for minutes any more, it is only a few seconds late.

Good :) It should also perform a bit faster if you close the dev tools and/or disable the verbose logging. Though I can't really reduce the time much more without undesirable side-effects.

I'm noticing the same file `ICD-10 Klassifikation Kurzbeschreibung.md` in 2 screenshots. Is Omnisearch faster if you remove this file from your vault?

**Comment by viktoriakeller** [comment]
I removed it and it doesn't change anything. It is quite an old file, one of the first I had in the vault actually.
It is now, when disabling the dev/verbose logging thing, still a bit sluggish, but does not freeze completely.

**Comment by tsteckenborn** [comment]
Have a very similar behavior (for some search terms). Getting matches places or something after that and before matches are the culprit. Interestingly enough the search is somewhat fine for "XYZ" but gets stuck for "XYZ A", after that "XYZ ABC" is fine again.

![2023-08-01 at 09 17 30](https://github.com/scambier/obsidian-omnisearch/assets/50519619/ba6dbe19-e1f2-4285-8f9e-befccb4def9b)
![2023-08-01 at 09 20 27](https://github.com/scambier/obsidian-omnisearch/assets/50519619/6f202701-6bc3-4e35-b378-a79e7c553a18)

**Comment by chrisweis** [comment]
Thanks so much for creating and helping with this awesome plugin!  It's so much better than the native Obsidian search.

I'm experiencing the same slowness problem.  It seems to most often occur with the first letter of searches.  Happens on my Mac (slow) but not my PC (fast) with the same vault (synced via Obsidian Sync).  I noticed that the first result was a large (3.3 MB) MD file, an export from my raindrop account.  **When I removed that large file from my vault the problem seemed to go away.  And when I added it back in again the problem came back.**  

I temporarily enabled verbose logging - where are the logs stored, @scambier?

**Comment by scambier** [comment]
Thanks both of you for your feedback.

@tsteckenborn 

> but gets stuck for "XYZ A", after that "XYZ ABC" is fine again.

The "Simpler search" setting should help in this case. Please report if it doesn't, I might have to rework it a bit.

@chrisweis 

> I temporarily enabled verbose logging - where are the logs stored, @scambier?

They're just available in the developer console (cm+shift+i) but now that you mention it, that would be interesting to have them written somewhere...

From what I've gathered in the different reported cases, the slowdowns are caused by the regex search that locates the different matches in a single note. It's interesting to see that you only have freezes on MacOS, I wonder if the Chromium regex implementation is different.

I think a proper solution would be to use background workers to do the search. It probably won't be faster, but at least it shouldn't freeze the interface.

**Comment by chrisweis** [comment]
@tsteckenborn the Base64 idea doesn't seem to apply to me.  My troublesome MD file only contains a 54K-line file of exported raindrop.io bookmarks, none that seem to contain any Base64.

**Comment by chrisweis** [comment]
When it hangs, this is what Activity Monitor's CPU looks like:
![image](https://github.com/scambier/obsidian-omnisearch/assets/13931731/de84f058-452a-44ad-bc18-012be6951d46)

**Comment by scambier** [comment]
@viktoriakeller the latest Omnisearch update (1.16.0) contains changes related to your issue, that could improve performances.

>  (my search was "s" without quotes)

Have you enabled the "Simpler search" option? It does this:

> Enable this if Obsidian often freezes while making searches. Words shorter than 3 characters won't be used as prefixes; this can reduce search delay but will return fewer results

So if you just type "s" it won't match the 4139 different tokens starting with that letter, but will wait until you at least type 3 letters. It might not outright solve the issue, but it definitely won't hurt.
