### ISSUE TITLE
[BUG] Slow/hang at startup w/medium size vault

### ISSUE THREAD

**Issue by pjeby** [scambier/obsidian-omnisearch#21]
**Problem description:**

When this plugin is active, the "loading workspace" of Obsidian startup it takes an extra 10-30 seconds.

It seems that this plugin's onload() is building an index and reads all files in the vault to do so; patching main.js to run the onload method body inside an onLayoutReady() callback defers the index load and event handler setup to after the workspace is loaded, allowing them to run in the "background" instead of blocking Obsidian startup.

**Your environment:**

- Omnisearch version: 0.2.3
- Obsidian version: 0.14.5
- Operating system: Windows
- Number of notes in your vault (approx.): 2800
- Other plugins that may be related to the issue: n/a

**Comment by scambier** [comment]
Excellent suggestion, thank you! The slower startup time was not _really_ noticeable on my computer, but it definitely is faster on my phone.
