### ISSUE TITLE
[BUG]  Search results not scrolling when navigating using keyboard

### ISSUE THREAD

**Issue by sohanglal** [scambier/obsidian-omnisearch#210]
**Problem description:**
Search results not scrolling when navigating using keyboard. This happens only on child windows of obsidian. The search result scrolls perfectly on the main window
![out](https://user-images.githubusercontent.com/29398628/225708621-751b99a5-8ec7-4202-a42c-967edc1097ae.gif)

**Your environment:**

- Omnisearch version: 1.12.3
- Obsidian version: 1.1.16
- Operating system: [[Kubuntu]] 22.04
- Number of indexed documents in your vault (approx.): 5000

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  Haven't checked
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Haven't checked
- Does the problem occur after a cache reset: Yes

**Comment by scambier** [comment]
Fixed in 1.14.0-beta.1
