### ISSUE TITLE
[Feature request] Add to API a method to highlight matches

### ISSUE THREAD

**Issue by olrenso** [scambier/obsidian-omnisearch#214]
I'm integrating Omnisearch in the search bar of the [Home tab](https://github.com/olrenso/obsidian-home-tab) plugin, and I'd like to replicate the search matches highlighting.

To keep consistency with the default style of Omnisearch would be nice to have a way to process the `excerpt` field from the search result object directly through the API.

![](https://i.imgur.com/vhwUN6G.png)

**Comment by qazxcdswe123** [comment]
There is a `matches: SearchMatchApi[]` returned in the result and I think you can use that to insert CSS to make a highlight.

```ts
type SearchMatchApi = {
  match: string
  offset: number
}
```

**Comment by scambier** [comment]
@olrenso Is the `matches` enough for your needs?

**Comment by olrenso** [comment]
I was worried about replicating exactly the default Omnisearch highlights, hence my request. Anyway, I got a pretty close implementation using `foundWords` since `matches` sometimes also returns parts of a found word.
