### ISSUE TITLE
[Feature request] Create block processor alternative to built-in "query"

### ISSUE THREAD

**Issue by artem-barmin** [scambier/obsidian-omnisearch#22]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that FTS in Obsidian embed search is very slow

**Describe the solution you'd like**
Would be great to utilise FTS index for alternative embed block

**Describe alternatives you've considered**
No alternatives so far

**Additional context**
This API can be used for creating such block processor: https://marcus.se.net/obsidian-plugin-docs/api/classes/Plugin_2#registermarkdowncodeblockprocessor

**Comment by scambier** [comment]
What is "FTS"?

**Comment by artem-barmin** [comment]
Full text search

**Comment by scambier** [comment]
Ok so you'd like Omnisearch to be able to return notes based on the contents of their embedded (transcluded) blocks?

**Comment by artem-barmin** [comment]
Yes. I would like to have functionality like this https://help.obsidian.md/Plugins/Search#Embed+search+results but backed by Minisearch library. 

So writing something like: 
\`\`\`omnisearch
content:(some words)
\`\`\`

would return notes from Minisearch index and embed them to page.

**Comment by artem-barmin** [comment]
This would enable workflow described in this article: https://roambrain.com/brainstorming-with-myself-systematic-creativity-in-roam/. Currently Obsidian search based on content is very slow

**Comment by scambier** [comment]
Ok I got it, that's definitely an interesting feature.

**Comment by scambier** [comment]
Instead of maintaining a custom code block + rendering on top of the search features themselves, I'd rather find a way to add a small API to expose search results and make them usable through DataViewJS

**Comment by shaggyfeng** [comment]
> Instead of maintaining a custom code block + rendering on top of the search features themselves, I'd rather find a way to add a small API to expose search results and make them usable through DataViewJS

Both options are very useful. You are amazing.
