### ISSUE TITLE
[Feature request] Support "Disable on this device"

### ISSUE THREAD

**Issue by quanru** [scambier/obsidian-omnisearch#229]
**Is your feature request related to a problem? Please describe.**
In mobile phone, i only use for writing note instantly, but omnisearch will index everytime

**Describe the solution you'd like**
Support "Disable on this device".

**Describe alternatives you've considered**
Support "Disable in mobile phone".

**Additional context**
Just like obsidian git plugin:
![image](https://user-images.githubusercontent.com/11739753/233588322-f40cff04-8c93-46d1-8bc6-81eb45f82006.png)

**Comment by szfkamil** [comment]
I stan this! Damn it, why did I say that?? I did get the point across, though! On each load, Omnisearch indexes all files which can cause some not-cool performance issues.
