### ISSUE TITLE
[BUG] Omnisearch doesn’t activate on iOS

### ISSUE THREAD

**Issue by quinncomendant** [scambier/obsidian-omnisearch#230]
**Problem description:**

I can install Omnisearch on my iPhone, but when I activate it nothing happens. The settings gear icon does not appear, settings are inaccessible, and Omnisearch is not available in the command palette. I tried reinstalling Obsidian and using a fresh vault with no other plugins. This problem been occurring for over a month.

**Your environment:**

- Omnisearch version: 1.13.0
- Obsidian version: 1.4.3
- Operating system: iOS 16.4.1
- Number of indexed documents in your vault (approx.): 833 notes

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin: yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  yes
- Does the problem occur after a cache reset: yes

https://user-images.githubusercontent.com/6884276/233802952-c71446c2-c38f-4e8c-a940-ebcea9cea7f3.mp4

**Comment by scambier** [comment]
Probably a crash during loading. See https://github.com/scambier/obsidian-omnisearch/issues/137#issuecomment-1345646832 for a step-by-step to display Obsidian's logs
