### ISSUE TITLE
[BUG] Characters deleted when typing search text

### ISSUE THREAD

**Issue by replete** [scambier/obsidian-omnisearch#232]
**Problem description:**

For a few months I've had this problem where my typed query loses entered characters as I am typing. You see the characters disappear as you are typing. 

I've included a recording showing the effect for a 'daily' search term. If I search for another term immediately after this, the behaviour is the same.

![screencast 2023-05-01 13-41-10](https://user-images.githubusercontent.com/812139/235453579-1c3f61af-0ba6-427e-8807-a94dd35664d8.gif)

**Your environment:**

- Omnisearch version: 1.14.0
- Obsidian version:  1.1.16 (1.15 installer)
- Operating system: MacOS
- Number of indexed documents in your vault (approx.): < 1000

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin: Yes 
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Yes
- Does the problem occur after a cache reset: Not sure

**Comment by scambier** [comment]
I've been unable to reproduce it, but I just published a tentative fix in beta

**Comment by replete** [comment]
I've done some further digging, and it looks like the Make.MD plugin is causing the problems. In fact, it appears that it provides its own search bound by default to the hotkey I was using.I was not aware of this. 

Apologies for barking up the wrong tree!
