### ISSUE TITLE
[BUG] Search Chinese not work when the word is not start of line

### ISSUE THREAD

**Issue by quanru** [scambier/obsidian-omnisearch#233]
**Problem description:**

Search Chinese not work when the word is not start of line!

![image](https://user-images.githubusercontent.com/11739753/236097156-aa8046c8-fcbb-4356-aa75-4122cfed7f33.png)
![image](https://user-images.githubusercontent.com/11739753/236097231-27212889-5122-47dc-8379-00b53825124d.png)
![image](https://user-images.githubusercontent.com/11739753/236097165-c1c48465-9524-4019-a70f-4623c480af1b.png)
![image](https://user-images.githubusercontent.com/11739753/236097245-1a30c702-01e2-4cf8-9908-7f4d57e72d43.png)

the text:
```md
- [ ] 请搜索我 onmisearch bug
```

**Your environment:**

- Omnisearch version: 1.14.0
- Obsidian version: 1.2.7
- Operating system: mac os
- Number of indexed documents in your vault (approx.): 2000

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  no
- Does the problem occur after a cache reset: yes

**Comment by scambier** [comment]
Have you installed and enabled this plugin? https://github.com/aidenlx/cm-chs-patch

It's required for CJK languages

**Comment by quanru** [comment]
> Have you installed and enabled this plugin? https://github.com/aidenlx/cm-chs-patch
> 
> It's required for CJK languages

It work after install https://github.com/aidenlx/cm-chs-patch! Thanks~
