### ISSUE TITLE
[Feature request] Option to open Omnisearch in the left sidebar like built-in Search

### ISSUE THREAD

**Issue by MrBertie** [scambier/obsidian-omnisearch#234]
Could you consider providing the option to open Omnisearch inside the left sidebar (like the built-in Search, Bookmarks, FileTree, etc.)?

Advantages: the search dialog could remain open when editing or doing other tasks, rather than the current modal dialog.

**Comment by aikruger** [comment]
in the meantime you can use the following dataviewjs script together with an inline dataview field Search:: 
const searchterm = dv.current().Search;
const results = await omnisearch.search(searchterm);
const arr = dv.array(results).sort(r => r.score, 'desc');
dv.table(['File', 'Score', 'Line'], arr.map(o => [dv.fileLink(o.path), Math.round(o.score), o.line]));

**Comment by aikruger** [comment]
It would be good to have a function to also display the line context of the search term as a column

**Comment by scambier** [comment]
I've recently updated the [API](https://publish.obsidian.md/omnisearch/Public+API+%26+URL+Scheme). In your example, you could get the context with `o.excerpt`. 

About this feature request, there's very little chance I ever implement it _but_ the API should provide everything necessary to build another plugin on top of it.
