### ISSUE TITLE
[BUG] Create note button is not visible in mobile

### ISSUE THREAD

**Issue by charleshan** [scambier/obsidian-omnisearch#237]
**Problem description:**

Create note button is not visible in mobile.
![image](https://user-images.githubusercontent.com/3143154/236705892-0afad0ef-a0fd-4fc2-abdb-221876f42b34.png)

**Your environment:**

- Omnisearch version: 
- Obsidian version: 1.4.4 (API v.1.2.7)
- Operating system: Android
- Number of indexed documents in your vault (approx.): 3000

**Comment by scambier** [comment]
Works for me, did you enable the setting?

**Comment by charleshan** [comment]
I see it now. We can close this issue :)
