### ISSUE TITLE
[BUG] There is no padding in the search box

### ISSUE THREAD

**Issue by kangruixiang** [scambier/obsidian-omnisearch#24]
There is no padding in the search box

Search box has no padding. Example:

![image](https://user-images.githubusercontent.com/17035138/165000497-2f80160e-751c-4ef6-945d-88c0c53f955b.png)

In comparison, default command palette: 

![image](https://user-images.githubusercontent.com/17035138/165000556-4aacc820-a209-4c88-a755-f4ba4e3858f7.png)

Windows 

- Omnisearch version:
- Obsidian version: v0.14.6
- Operating system: 0.2.5
- Number of notes in your vault (approx.): 1500
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Could you give me your theme so I can check if my fix is ok? Thank you.

**Comment by kangruixiang** [comment]
Sorry just saw this comment. But the theme is California Coast. The padding has also been fixed.
