### ISSUE TITLE
[Feature request] Search filters

### ISSUE THREAD

**Issue by javiavid** [scambier/obsidian-omnisearch#25]
**Is your feature request related to a problem? Please describe.**
I would like to have a filter for exact phrases and to discard words

**Describe the solution you'd like**
-Use quotation marks for exact phrases
"antique car"

-Use hyphen to discard notes containing unwanted words
"antique car" -1970

**Describe alternatives you've considered**
For discards NOT could be used
"antique car" NOT 1970

**Comment by scambier** [comment]
This feature has been released in [version 1.1.0](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.1.0), which is accessible through BRAT.

You can now search for `"antique car" -1970`. Do note that quotes and exclusions work as a post-search filter: Omnisearch will first look for all notes that match `antique` and `car`, and then filter those who contain the sequence `"antique car"`, and exclude those who have `1970`
