### ISSUE TITLE
Search in Dashboard

### ISSUE THREAD

**Issue by VialesProductions** [scambier/obsidian-omnisearch#256]
## Problem description
The contents of dashboard files created through the [dashboard](https://github.com/trey-wallis/obsidian-dashboards) plugin aren't surfaced in Omnisearch

## Feature proposition
Enable Omnisearch to search through the contents of the `.dashboard` files created by the [dashboard](https://github.com/trey-wallis/obsidian-dashboards) plugin

## Alternatives considered
Doesn't seem to be any available

## Implementation details/context
`.dashboard` files are `JSON`.

**Comment by VialesProductions** [comment]
So, I just realized that I need to add the `.dashboard` extension to the "allowlist" in the Omnisearch config.
The same goes for the `.cook` files that weren't being indexed.

Now the `.dashboard` files are surfaced by Omnisearch. The only problem (although minor) is the fact that the excerpt shows the `JSON` syntax.

![image](https://github.com/scambier/obsidian-omnisearch/assets/137490306/12ce1ec1-2707-4abd-941b-b42401c9e465)

**Comment by scambier** [comment]
That's the quick and dirty solution; it works but Omnisearch will also index a lot of noise. I have to add a special case for dashboard files

**Comment by scambier** [comment]
Deloyed in 1.15.0-beta.2
