### ISSUE TITLE
[Feature request] Add an option to disable the "Omnisearch - your files have been indexed" popup on Obsidian start

### ISSUE THREAD

**Issue by cakechaser** [scambier/obsidian-omnisearch#259]
**Is your feature request related to a problem? Please describe.**

--

**Describe the solution you'd like**
I'd like an option to disable the "Omnisearch - your files have been indexed" popup which appears each time Obsidian is started. Right now I don't find it useful, since it happens almost instantly, and it doesn't really affect my usage. I don't have to wait until the files are indexed, to start searching.

It would be useful to have a popup only in case of issues, to know that indexing has failed and search results might be incorrect/incomplete.

**Describe alternatives you've considered**
Alternative - disable the popup altogether.

**Additional context**

--

Thank you!

**Comment by scambier** [comment]
The messages "_Omnisearch will index..._" and "_Your files have been indexed_" appear when the cache is disabled and when there are 1000+ files to index. The first one warns that there might be slowdowns, and the second is just there to say "everything went well". You can enable the cache and the messages won't be displayed anymore.

**Comment by cakechaser** [comment]
I actually have the cache enabled, but I just realized that I only get this pop-up on iOS, and not on desktop (in the same vault with the same plugins/settings).

Could the configuration be different between desktop/mobile?

**Comment by scambier** [comment]
ah yes, there's no cache on iOS 🤔 I'll see to implement the message differently

**Comment by LMRW** [comment]
Please do, I also have this issue and it is very annoying. The information shown in a pop up takes a large percentage of iPhone screen and covers essential UI elements. If you are doing to do that, do it for useful information. The current message is entirely wasteful information nobody can react or do anything with so it's just a (literal) giant waste of space. Amazing plug-in - this is a total deal breaker for many though I'm sure as it delays being able to use the app once it opens! Thank you
