### ISSUE TITLE
[BUG] Words prefixed by a tab \t are not indexed

### ISSUE THREAD

**Issue by wolvido** [scambier/obsidian-omnisearch#262]
**Problem description:**
Omnisearch cannot search nested non listed items, but can search listed items. 
Or just not implemented yet?

I have a file with a nested list where the item is listed with '-':
![testWith](https://github.com/scambier/obsidian-omnisearch/assets/59104773/aa66ac4d-191c-45ab-9908-1ba242bc4bfc)

I have another with a nested list where the item is not listed:
![testWithout](https://github.com/scambier/obsidian-omnisearch/assets/59104773/c3b44de1-fbf7-40b1-8055-aaa6b38da439)

Search results only shows the file with a nested list where the item is listed with '-':
![result](https://github.com/scambier/obsidian-omnisearch/assets/59104773/ab31e661-58f0-4881-9d61-c204cb83b39d)
![result2](https://github.com/scambier/obsidian-omnisearch/assets/59104773/1de26e14-155c-4076-ae4f-6861b56afba9)

**Your environment:**
- Omnisearch version: 1.15.1
- Obsidian version: 1.3.5
- Operating system: Windows 10 Home Single Language version 22H2 build 19045.3208
- Number of indexed documents in your vault (approx.): 100

**Things to try:**
- Does the problem occur when Omnisearch is the only active community plugin:  it occurs when Omnisearch is the only active and when other plugins are active.
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  it occurs with or without pdf and image indexing.
- Does the problem occur after a cache reset: yes.

**Comment by wolvido** [comment]
hi, sorry if my explanation was confusing. 
"Words prefixed by - are not indexed" is not accurate, it's the opposite. 
More like; "Words in a nested list not prefixed by - are not indexed."

**Comment by scambier** [comment]
I'll run you different examples while working on it, but there's a bug that needs to be fixed anyway:)
