### ISSUE TITLE
[BUG] ==Highlighted== text isn't found in search

### ISSUE THREAD

**Issue by Finni123** [scambier/obsidian-omnisearch#263]
**Problem description:**
When searching for something, words that are markdown-highlighted like ==this== aren't found.

**Your environment:**

- Omnisearch version: 1.15.1
- Obsidian version: 1.3.5
- Operating system: Windows 10
- Number of indexed documents in your vault (approx.): maybe 200?

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  yes
- Does the problem occur after a cache reset: yes

**Comment by Finni123** [comment]
@scambier it's nice to see how fast you react to new bug reports, but seeing how many issues are still open, I wonder when all the bugs will be fixed.

This one is very annoying for me, because I highlight the important words, but when searching for something I (naturally) search for those important words, resulting in completely useless search results.

Can you give any estimate whether this will be fixed in the near future? Or should I rather look for another search plugin meanwhile? Just a genuine question. :)

**Comment by scambier** [comment]
> but seeing how many issues are still open, I wonder when all the bugs will be fixed.

Issues != bugs :) 

Bugs that I consider "breaking" (= that affect the indexing or results) are usually fixed and deployed within a few days or a week, as soon as I get the time.

**Comment by scambier** [comment]
This should be fixed in 1.15.2. You'll certainly have to clear Omnisearch cache and restart Obsidian to reindex notes with highlights
