### ISSUE TITLE
[Feature request] Make work with supercharged links styling

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [scambier/obsidian-omnisearch#27]
**Is your feature request related to a problem? Please describe.**
Supercharged links styling shows up in the standard quick switcher:
![image](https://user-images.githubusercontent.com/31261158/165370172-453e107f-8786-461c-8aee-c8aa399f6674.png)

Omnisearch would benefit from this, as it aids in visual distinction between files

**Comment by scambier** [comment]
Hello, thanks for your PR, it's up to Supercharged Links to support Omnisearch: https://github.com/mdelobelle/obsidian_supercharged_links#supported-plugins

> Want support for another plugin? Create an issue here in the repo!
