### ISSUE TITLE
[BUG] UseCache deactivating automatically

### ISSUE THREAD

**Issue by zanodor** [scambier/obsidian-omnisearch#271]
Hello good sir,

I have searched for the bug at your GH and couldn't find it mentioned.  

I use GitHub Desktop and I can easily see in the data.json file that true is changed to false without the user's knowledge.  

I have seen this behaviour when  
- updating Omnisearch; 
- having Obsidian index the vault (after some changes made from outside, e.g. Notepad++ regex changes).  

I need to go into the data.json file with a text editor and put `true` back in before a restart.

**Comment by scambier** [comment]
Hello, yes it is an intended behavior: useCache is set to false at startup, and then reset to true once the cache is fully written:
https://github.com/scambier/obsidian-omnisearch/blob/a077b427ebaee85bccb001210f7ec1e2902da15c/src/main.ts#L207-L216

![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/891feae2-9659-4cd4-bc41-261706d90098)

In rare cases (especially on mobile), a hard crash can happen during cache write. When that happens, the cache disables itself to avoid bootloop crashes of Obsidian. If that happens on your device, that means that there's either something wrong when writing the cache, or you're quitting Obsidian during the process.
