### ISSUE TITLE
[Feature request] Add shortcut to "open in the background"

### ISSUE THREAD

**Issue by scambier** [scambier/obsidian-omnisearch#275]
**Is your feature request related to a problem? Please describe.**

Open multiple results from Omnisearch, while keeping the search modal open.

**Describe the solution you'd like**

Another Quick Switcher uses alt+o for this feature

**Describe alternatives you've considered**

none.

**Additional context**

https://www.reddit.com/r/ObsidianMD/comments/15ip51w/omnisearch_experts_is_this_possible/

**Comment by myeewyee** [comment]
Is there any way to change the hotkey? Alt o does not work for me.

**Comment by scambier** [comment]
See #418
