### ISSUE TITLE
[Unable to enable PDF Contexting and Image OCR Indexing] 

### ISSUE THREAD

**Issue by haardikg** [scambier/obsidian-omnisearch#277]
**Problem description:**

Whenever I try to enable the listed settings I get the error in the image, I get a popup to restart obsidian but nothing happens after restarting other than the setting being disabled. I already have text extractor enabled. Even without enabling the above settings omnisearch doesn't show up in my command palette and is essentially hidden

<img width="1512" alt="Screenshot 2023-08-19 at 10 53 04 PM" src="https://github.com/scambier/obsidian-omnisearch/assets/36541643/466efa59-9f45-4db7-8569-d394c0a5c47f">**Your environment:**

- Omnisearch version: 1.15.2
- Obsidian version: v1.3.7
- Operating system: macOS Ventura 13.0.1
- Number of indexed documents in your vault (approx.): idk

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  I can't use omnisearch for anything
- Does the problem occur after a cache reset: It says that the cache is being reset after I enable the settings but nothing happens

**Comment by scambier** [comment]
This looks like an internal error to Chromium, and Dataview logs a similar error. https://kagi.com/search?q=internal+error+opening+backing+store+for+indexeddb&r=no_region&sh=osKlujECaP0Bgm1EHdm5Jg

The most sensible suggestion I've seen is to clean your IndexedDb storage and make sure you have enough available space on your computer. 
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/f3a5a75f-40e4-4a2b-81f9-0c08900de54a)

**Comment by haardikg** [comment]
The IndexedDB doesn't have any drop down for me, what should I do?
<img width="1512" alt="Screenshot 2023-08-20 at 10 16 11 AM" src="https://github.com/scambier/obsidian-omnisearch/assets/36541643/7b3ebebd-9e0d-408a-b91c-4de41f27f527">

**Comment by scambier** [comment]
Honestly no idea, sorry 🤷‍♂️ Maybe reinstall Obsidian, or ask for help on their forum/discord?

I'm closing the issue because this is outside the scope of Omnisearch.
