### ISSUE TITLE
[BUG] Adding a dash breaks the search

### ISSUE THREAD

**Issue by charleshan** [scambier/obsidian-omnisearch#278]
**Problem description:**

If we have a note called "Book - Some Book", we can't search for it with "Book - Some Book". In addition, I expect to be able to match all books with "Book -".

**Your environment:**

- Omnisearch version: 1.15.2 (I just tried to update with BRAT and it downgraded to 1.15.1? Do you know why this happened?)
- Obsidian version: v1.3.7
- Operating system: 13.4.1 (22F82)
- Number of indexed documents in your vault (approx.): 3000

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin: Yes.
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files: Yes.
- Does the problem occur after a cache reset: Yes.

**Comment by scambier** [comment]
> I just tried to update with BRAT and it downgraded to 1.15.1? Do you know why this happened?

The beta manifest wasn't up-to-date, it should be fixed now, but there's no active beta right now. The current versions are shown on the readme 
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/10ebf392-ea5e-4aad-a2c1-1f4780441056)
