### ISSUE TITLE
[BUG] Omnisearch not displaying results for specific strings despite finding matches

### ISSUE THREAD

**Issue by DrSAS** [scambier/obsidian-omnisearch#281]
**Problem description:**

When I search for the string `"ssh -T git"` in Omnisearch, even though I have a note that contains this exact text, no results are displayed. This seems contradictory to the debug terminal output which indicates "Found 1 result" initially, and then "Found 2 results" after clearing the cache. Despite this, the results pop-up remains empty.

Please note that in my original note, this snippet is surrounded by backticks like this: 

```
- [...] `ssh -T git@github.com` [...]
```

If I search using the full occurrence (`"ssh -T git@github.com"`), I also do not get any results.

**Your environment:**

- **Omnisearch version:** 1.15.2
- **Obsidian version:** 1.3.7
- **Operating system:** Windows 11
- **Number of indexed documents in your vault:** Approximately 1550 notes

**Things to try:**

- **Does the problem occur when Omnisearch is the only active community plugin:** Yes, the issue persists even with all other plugins disabled, after clearing the Omnisearch cache and restarting.
- **Does the problem occur when you don't index PDFs, images, or other non-notes files:** Not checked 😇 but the PDF indexing is not enabled
- **Does the problem occur after a cache reset:** Yes, after a cache reset, the debug terminal indicates "Found 2 results" instead of 1, but the results pop-up is still empty.

![image](https://github.com/scambier/obsidian-omnisearch/assets/6788696/d68bf514-ee05-4813-97d9-df5750a46939)

Thank you!

**Comment by scambier** [comment]
It should be fixed (to be deployed with the next beta), though there's one thing that won't work by design: when searching for `ssh -T git` without quotes, the `-T` will act as a exclusion, so it will filter out notes that contain a token that starts with `T`.

> This seems contradictory to the debug terminal output which indicates "Found 1 result" initially

This logs the results _before_ applying further filters, such as quotes and exclusions

**Comment by DrSAS** [comment]
Hi @scambier, thank you for clarifying. 

I now understand the behavior with the exclusion using -T. My use of quotes was an attempt to capture the exact phrase, given the unexpected results without them. 

I appreciate the quick fix and look forward to the next beta release :)
