### ISSUE TITLE
[BUG] Characters not indexed

### ISSUE THREAD

**Issue by wolvido** [scambier/obsidian-omnisearch#284]
**Problem description:**
Characters such as ^ * % ! @ % & ( ) [] {} = - are not indexed.
![1](https://github.com/scambier/obsidian-omnisearch/assets/59104773/5f7f4c06-a68d-4876-960b-dfdada9b67a0)
![2](https://github.com/scambier/obsidian-omnisearch/assets/59104773/4e03a566-dc4d-452b-8c90-8e7d1fbcfb63)

**Your environment:**

- Omnisearch version: 1.16.0
- Obsidian version: 1.4.5 
- Operating system: Windows 10
- Number of indexed documents in your vault (approx.): 120

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  yes
- Does the problem occur after a cache reset: yes

**Comment by scambier** [comment]
That's by design. Omnisearch indexes tokens (words), and those characters (and _many_ others) are used as separators.
