### ISSUE TITLE
[BUG] Failed to load plugin manifest

### ISSUE THREAD

**Issue by Cutuchiqueno** [scambier/obsidian-omnisearch#29]
**Problem description:**

When selecting the plug-in in the plug-in browser in order to see the README and to install it I get an error message and see nothing. For matters of humor I post the screenshot below 😉 All other plug-ins (installed and not installed work well in the plug-in browser)

![grafik](https://user-images.githubusercontent.com/306064/165457077-44036125-22b5-4af7-a57d-682e9cb5d103.png)

**Your environment:**

- Omnisearch version: -
- Obsidian version: 0.14.7
- Operating system: Windows 11 21H2 22000.613
- Number of notes in your vault (approx.): 400
- Other plugins that may be related to the issue: -

**Comment by scambier** [comment]
Yep, I made an error in the community plugins list pull request, it has to be fixed on their end :(
https://github.com/obsidianmd/obsidian-releases/pull/920#issuecomment-1110603635

In the meantime, you can install it with BRAT. Sorry for the inconvenience!

**Comment by Cutuchiqueno** [comment]
Thanks so much for the tip/quick response and no reason to apologize. You are providing us with this wonderful plugin, thus thank you!
