### ISSUE TITLE
[BUG] Unable to search for words in the title

### ISSUE THREAD

**Issue by sjhsbhqf** [scambier/obsidian-omnisearch#292]
**Problem description:**

 Unable to search for words in the title 
![image](https://github.com/scambier/obsidian-omnisearch/assets/41407099/7ffa1252-e52b-4137-b04a-7fe7fdc20742)

**Your environment:**

- Omnisearch version: 1.17.1
- Obsidian version: 1.4.5
- Operating system: win10 22H2

**Comment by scambier** [comment]
Have you installed and enabled https://github.com/aidenlx/cm-chs-patch ?

**Comment by sjhsbhqf** [comment]
Thank you.  when i restart the ob, it makes effect
