### ISSUE TITLE
[Feature request] Saved Search Filters

### ISSUE THREAD

**Issue by tsteckenborn** [scambier/obsidian-omnisearch#295]
**Is your feature request related to a problem? Please describe.**

As a user I want to quickly find relevant notes. Therefor it would be handy to save and reuse filters.

**Describe the solution you'd like**

One proposal would be an save / alias of parts of the search.

**Describe alternatives you've considered**

Manual Path Entry.

**Additional context**

Further filter options would be great.

**Comment by scambier** [comment]
Duplicate of #235
