### ISSUE TITLE
[BUG] Enter does not jump

### ISSUE THREAD

**Issue by sjhsbhqf** [scambier/obsidian-omnisearch#298]
**Problem description:**

When I search for a certain keyword, I see what I want in the results, but pressing the Enter key does not jump to the specified location

**Your environment:**

- Omnisearch version: 1.17.1
- Obsidian version: 1.4.11
- Operating system: WIN11 23H2
- Number of indexed documents in your vault (approx.):  1

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:   yes
- Does the problem occur after a cache reset:  yes

**Comment by scambier** [comment]
@ammarhusain @sjhsbhqf From my tests, it looks like the bug mainly happens when the location is a heading. Can you confirm it's the same for you, or are there other situations?

**Comment by ammarhusain** [comment]
works now - thanks!
