### ISSUE TITLE
FR -- Include Embed Directives

### ISSUE THREAD

**Issue by StefanoRausch** [scambier/obsidian-omnisearch#3]
I have the embed `![[Diving Store]]` in one of my MD files.

OS does find the original `Diving Store` file, but not the file containing the embed.

Would be great if you could enhance the findings.

Thanks for your consideration.

**Comment by scambier** [comment]
So, something like this?

![image](https://user-images.githubusercontent.com/3216752/162627765-7dc056d8-9d57-44e4-9035-81edaa379f03.png)

It's indeed not working on the current version, the embeds are stripped from the indexed data. It's an oversight on my part,  I'm fixing that :)

**Comment by StefanoRausch** [comment]
Apologies for the late reply. OS now finds embedded directives -- thank you for the enhancement!
