### ISSUE TITLE
[BUG] 1.18.0 won't start on Android

### ISSUE THREAD

**Issue by materemias** [scambier/obsidian-omnisearch#302]
**Problem description:**

plugin stays disabled on Android, errors with `Failed to load plugin omnisearch`. Worked with previous version

**Your environment:**

- Omnisearch version: 1.18.0
- Obsidian version: 1.4.9
- Operating system: Android 13
- Number of indexed documents in your vault (approx.): 500

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  NA
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  NA
- Does the problem occur after a cache reset: NA

**Comment by scambier** [comment]
Fixed in 1.18.1, thank you

**Comment by materemias** [comment]
I can confirm, it works properly now, thanks for the fix
