### ISSUE TITLE
[BUG] help!! cannot highlight search results anymore; just can highlight english words but cannot highlight chinese words

### ISSUE THREAD

**Issue by kafkazov** [scambier/obsidian-omnisearch#303]
**Problem description:**

**Your environment:**

- Omnisearch version: 1.18.1
- Obsidian version: 1.4.16
- Operating system: win11
- Number of indexed documents in your vault (approx.): 500+

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  YES
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  NO
- Does the problem occur after a cache reset: NO
![image](https://github.com/scambier/obsidian-omnisearch/assets/125727173/998fd85c-10c3-4eaf-9f8e-9e0a9d31b874)

![image](https://github.com/scambier/obsidian-omnisearch/assets/125727173/8b96100b-fac1-4979-8755-1376c88c8b4a)

**Comment by scambier** [comment]
Please fill the template with the asked information, a description, and possibly a few screenshots.

**Comment by kafkazov** [comment]
> Please fill the template with the asked information, a description, and possibly a few screenshots.

THANKS for your responding. i have  uploaded some pictures to show that problem. THE WORDS are highlighted but 汉字 Chinese words cannot be highlighted.

I tried in my own vaults and Blue-topaz-examples vault. Same result.

Do not know why this happens.Hope you can help me.Thanks again.

**Comment by scambier** [comment]
Have you installed and enabled this additional plugin? https://github.com/aidenlx/cm-chs-patch

It's required by omnisearch to correctly split Chinese words.

**Comment by kafkazov** [comment]
> Have you installed and enabled this additional plugin? https://github.com/aidenlx/cm-chs-patch
> 
> It's required by omnisearch to correctly split Chinese words.

Thanks for your responding.
YES. i have installed and enabled this plugin.
Tried just now.Same result.

**Comment by kafkazov** [comment]
Borrowed my friend's Mac which never installed obsidian before. Tried my own vault and a totally new vault.

Same result. English words can be highlighted and Chinese words cannot.

**Comment by gy-git** [comment]
i have the same Problem！

**Comment by kafkazov** [comment]
> i have the same Problem！

问过Ob交流群的其他人，也都是这样，应该就是插件目前不支持？

**Comment by gy-git** [comment]
我记得之前中文高亮是没问题的吧

**Comment by scambier** [comment]
A fix will be deployed for the next version.
