### ISSUE TITLE
[BUG]  WHen I search URLS I get the right file result but the highlight is always something else...

### ISSUE THREAD

**Issue by cocoonkid** [scambier/obsidian-omnisearch#304]
**Problem description:**

After obsidian destroyed their search with the new colon option I use omnisearch to be able to search  for my urls in my knowledgebase. I know, very very edge case.

 When I search URLS I get the right file result but the highlight is always something else...

Pressing enter opens the right file but does not put the cursor at the search result.

![image](https://github.com/scambier/obsidian-omnisearch/assets/43231640/ded98c4b-fd86-4823-9807-a9e55dda1ba8)

**Your environment:**
Latest Obsidian
Latest Omnisearch
Latest MacOS / Latest LINUX

**Comment by scambier** [comment]
Omnisearch does a token-based search, and the url `https://foo.bar/baz` is actually read as `https foo bar baz`. The highlighting reflects that.

Though I understand how it can be unexpected with this kind of usecase and will look to rework the highlight and "go to line"

(Might be related to #301 too)

**Comment by cocoonkid** [comment]
Maybe optionally a list of regex that will always be searched as full string.?
So I could declared urls to always search not-token-based.

**Comment by cocoonkid** [comment]
much love @scambier

**Comment by scambier** [comment]
This is now deployed in the 1.19.0-beta.1 version (if you use [BRAT](https://github.com/TfTHacker/obsidian42-brat)). I'll probably push it on the main branch within 2 weeks. You'll also need to clear your Omnisearch cache for a full reindex.

**Comment by cocoonkid** [comment]
@scambier Could it be that Obsidian changed smth?  I cannot query for urls again...just noticed that right now.
I cleaed the cache and restarted and made sure I have all updates in.

**Comment by scambier** [comment]
Nope, no change since the update that included this feature 🤔

![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/9666ff27-bf89-4664-b837-dcf3d7b2d972)

**Comment by cocoonkid** [comment]
Okay, it seems to work most of the time but still not everytime.

see this example. What could the reason be?  Would there be a way to add more weight to full matches? especially with urls?

![image](https://github.com/scambier/obsidian-omnisearch/assets/43231640/cdd90e60-d496-47f6-8a9f-02f9f0a4a21a)

**Comment by cocoonkid** [comment]
Still having these issues. Thanks for your time :-)

**Comment by KraXen72** [comment]
hi, i also have this issue:
query: "normie.cc"
part of markdown file with match:
```md
# contents
- main homepage with social icons + something custom
	- https://kasper.space cool starry animated bg
	- https://thedise.me nice background, social icons
	- https://www.normie.cc cool greeting font
	- [tinyclouds](https://tinyclouds.org) cool social icons
```
omnisearch:
![image](https://github.com/scambier/obsidian-omnisearch/assets/21956756/8e3dd477-e018-428a-8fc7-11182a05b176)
![image](https://github.com/scambier/obsidian-omnisearch/assets/21956756/50bd5ad7-c130-4c18-af46-845d049127cf)

**Comment by cocoonkid** [comment]
I think the solution would be an option for an ignorelist.

Whenever I remove the https scheme for example it works.
I personally would just add https://github.com to the ignorelist so the search always only focusses on the path thereafter.

@scambier  Please please stop our suffering :-)

**Comment by KraXen72** [comment]
i think a better solution might be rewriting the highlighting to support highlighting several matched tokens

**Comment by scambier** [comment]
I've published a version [1.22.0-beta.1](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.22.0-beta.1) last week that should improve the general highlighting.

**Comment by cocoonkid** [comment]
Just tried it out. Unfortunately no improvement so far.  I deleted the  cache  and restarted + reindexed as well.  
![image](https://github.com/scambier/obsidian-omnisearch/assets/43231640/40ea044e-4a9e-4764-bc0d-a5311cee129a)

example 1:

![image](https://github.com/scambier/obsidian-omnisearch/assets/43231640/c7b4f0c0-68a8-4cce-9b28-949c05297352)


![image](https://github.com/scambier/obsidian-omnisearch/assets/43231640/58406355-ccde-4949-a1aa-3d5039251619)

example 2:

![image](https://github.com/scambier/obsidian-omnisearch/assets/43231640/33cdf0f8-abb4-4737-b78d-68c3c1c7d259)


![image](https://github.com/scambier/obsidian-omnisearch/assets/43231640/558c2a60-316b-4fb0-b8c0-8ad7dff9d8d3)


Thank you for your continued  pursuit of this issues. Really highly  appreciated.

**Comment by KraXen72** [comment]
i from how omnisearch (and under the hood, minisearch) works, the whole query gets split into terms - many files have some of the terms from that url, but it happens so that the file with the full url has most terms, so it's at the top. the problem is, not all the terms are necessarily found one after another in the file, leading to the highlighting you see.

i think it could be worth exploring detecting urls in the search query, and adding custom highlighting logic if the query contains a url, to try to highlight most of it without interruptions.
it also could be useful to see if minisearch has some options which are relevant to this problem.

**Comment by scambier** [comment]
I published [1.22.0-beta.2](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.22.0-beta.2).

Urls are now considered whole tokens so that should greatly improve results. I also reworked the highlighting a bit.

**Comment by cocoonkid** [comment]
just updated and will report back how it works out.  So far it has improved for sure.

**Comment by cocoonkid** [comment]
So far it works GREAT!!!!  
The highlighting is a little off and weird sometimes but absolutely no problem at all. 
I can show a few examples over time if you want me to.  And I think it still has to do with  too many results for the protocol scheme.
So still somehow assuming it would be cool to be able to ignore any `protocol://`

But anyways. Thank you for taking care of this!!!  HIGHLY appreciated.

**Comment by scambier** [comment]
Neat :)

> I can show a few examples over time if you want me to.

If you happen to have a minimal reproducible example (a note + a search query), I'll gladly take it 👍

**Comment by scambier** [comment]
Hello, due to #363, I've gated this feature behind an opt-in setting in the Behavior section

**Comment by cocoonkid** [comment]
Today I noticed ;-) All good.

I did not find any more reproducible examples.

I feel this "issue" is truly solved.  Thanks again @scambier!

**Comment by scambier** [comment]
Thanks for your feedback o/
