### ISSUE TITLE
[Feature request] Automatically close omnisearch when opening obsidian file switcher

### ISSUE THREAD

**Issue by cocoonkid** [scambier/obsidian-omnisearch#305]
[Feature request] Automatically close omnisearch when opening obsidian file switcher.

Right now I need to close it manually and then open the file switcher.

THanks for your consideration.

**Comment by scambier** [comment]
I don't think it's doable, and the problem also happens in reverse: if the Quick Switcher is open, my Omnisearch shortcut is unresponsive.
