### ISSUE TITLE
Conflicting licensing information

### ISSUE THREAD

**Issue by a13ph** [scambier/obsidian-omnisearch#313]
**Problem description:**

In the Readme, GPL-3 is mentioned as a repo license.
In Github sidebar, AGPL-3.0 is listed as a repo license.
Those two are different licenses.

Please resolve or clarify this conflicting information.

**Comment by scambier** [comment]
Fixed, GPL-3 is the correct license, I guess I misclicked when I created the file back then. From my understanding, AGPL doesn't really make sense for Omnisearch. I also fixed the license for Text-Extractor.
