### ISSUE TITLE
[Feature request] Hide indexing notification in certain situations

### ISSUE THREAD

**Issue by GollyTicker** [scambier/obsidian-omnisearch#314]
**Is your feature request related to a problem? Please describe.**
When opening obsidian on mobile (android) after updating my files via gut - omnisearch shows two notifications that it's indexing these new files. The problem is, that on mobile these notifications both take 50% of the space right when the notes have loaded and when I want to start typing. This is annoying and I haven't found a setting to disable these notifications.

**Describe the solution you'd like**
Add a setting to disable "indexing on going" etc. notifications. Either always disabled, always enabled, or enabled per device. Last option is optional. Not getting this notification is fine for me - as even if I try the omnisearch, I'll see in the pop-up, that it's indexing. Then I know, that I just need to wait. We could also make it such that only indexing of large number of files (e.g. after a fresh copy is created) are notified - but small number of files like <15 are not notified.

**Describe alternatives you've considered**
I cannot disable these notifications afaik. And just waiting for a few seconds is breaking my concentration when I'm eager to formulate my thoughts.

I could help out with the implementation of we can agree on that this should be added.

what does everyone think?

**Comment by scambier** [comment]
The notification is supposed to be shown only when there's >= 1000 updated files. Does it work differently for you?

(also I think you can just tap on the notification to make it disappear, fwiw)

**Comment by GollyTicker** [comment]
Interesting. I get these notifications quite frequently. At least the "omnisearch finished indexing" comes altmost everytime.

I am aware, that I can tap on it - but I'd prefer it not just come in the first place. Sometimes, I might get distracted when I start typing and the notification comes only a second or two after I started.

As I said. I'm willing to implement it myself since I don't expect it to be too hard...

**Comment by scambier** [comment]
Start indexing:
https://github.com/scambier/obsidian-omnisearch/blob/71788b1493d37afe1a2c089e0e341f2d7c8eefe2/src/main.ts#L207-L212

End indexing:
https://github.com/scambier/obsidian-omnisearch/blob/71788b1493d37afe1a2c089e0e341f2d7c8eefe2/src/main.ts#L234-L236

In both cases, those notifications (should) appear when there's more than 1000 modified/added files. I guess we could reduce the duration for the first notification, but I won't disable them 🤷‍♂️

**Comment by GollyTicker** [comment]
Interesting. When I get to it, I'll test this with debug console in my setup and also sprinkle some logs inbetween. The second notification definitively should't occur in my case except if I'm doing something nonstandard somewhere. Thanks for the hint. :smile:

**Comment by scambier** [comment]
Closing this issue, feel free to reopen if you have more information to share.

To summarize, if the notification appears, that means Omnisearch effectively sees at least 1000 modified files and has to reindex them. Even if only the timestamp is different and those files are virtually identical, the reindex will have to be done, so the notification is warranted.
