### ISSUE TITLE
[BUG] Obsidian Crashing While Indexing PDF With Omnisearch

### ISSUE THREAD

**Issue by JamesIslan** [scambier/obsidian-omnisearch#316]
Hello! I'm trying to use Omnisearch to index some of my OCR PDF files inside Obsidian. However, i'm facing some problems with it, as the amount of files is big. I noticed that the obsidian.exe process reach 4GB on the Task Manager, and after that the program crashes and forces me to reload. When i do that, the plugin automatically disables the file cache indexing. I really need the cache to be enabled, as the indexing without it would take a really long time on every program opening. I would like to know if there's a way to limit the RAM usage of the Obsidian process to be always below 4GB, so that the crash stop occurring. I've already tried to index the PDF files one by one, but as some of the files have big size (~100MB), this workaround isn't enough, and after some files are indexed, the crash occur anyway. Any solution or hint would be really appreciating!

![image](https://github.com/scambier/obsidian-omnisearch/assets/69359116/c166a49c-1855-4030-a4cb-4d65475d02cc)

- Omnisearch version: 1.19.0
- Obsidian version: 1.4.16
- Operating system: Windows 11 23H2
- Number of indexed documents in your vault (approx.): 1500

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  Yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  No
- Does the problem occur after a cache reset: Yes

**Comment by scambier** [comment]
I think that unfortunately, you're hitting the limits of Omnisearch here. The cache is simply too large, and disables itself to avoid bootloop crashes. I can only recommend to not index your PDFs, or place the biggest ones in an excluded folder 🤷‍♂️

I'll leave this open for now and see if a fix is possible in Minisearch.

**Comment by scambier** [comment]
@JamesIslan I have updated the cache loading mechanism in the latest Omnisearch update (1.23). Could you please check and report if your issue still persists?
