### ISSUE TITLE
[Feature request] Highlight parts of the path too

### ISSUE THREAD

**Issue by MaxLap** [scambier/obsidian-omnisearch#318]
So right now, it seems that the path parts that match are not highlighted when searching.

![image](https://github.com/scambier/obsidian-omnisearch/assets/894561/a2a92a7a-a5f1-43ee-b302-332e1a1432aa)

This is a bit confusing as you expect to be scanning for the bold parts to find what you are looking for, and can en up having nothing to look at. It's especially jarring when searching with excerpts.

So it would be nice if the highlighting was also happening on the path.

**Comment by MaxLap** [comment]
I'm willing to look into making a PR for this if you agree this is desirable. Let me know.

**Comment by scambier** [comment]
Yes, thank you!
