### ISSUE TITLE
[BUG] Missing highlights in excerpts

### ISSUE THREAD

**Issue by MaxLap** [scambier/obsidian-omnisearch#319]
**Problem description:**

If you look at this screenshot:
![image](https://github.com/scambier/obsidian-omnisearch/assets/894561/af7a97fc-9e23-4708-b254-6268bf486e3a)

* In the first result: It feels like a bug that the two "controller" in the excerpt are not highlighted. Maybe it's not because it's highlighted in the file title, but they should still be highlighted.
* In the second result: There is nothing highlighted while we can see the word "control" right there in the excerpt. We can see it working in the 3rd excerpts.

**Your environment:**

- Omnisearch version: 1.19.0
- Obsidian version: 1.4.16
- Operating system: Windows 11
- Number of indexed documents in your vault (approx.): Less than 100

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin: I highly doubt this could have an impact, tell me if you think otherwise and I will try 
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Also not active
- Does the problem occur after a cache reset: Nothing changed

**Comment by TucGibson** [comment]
I have the same issue. For me it is _more likely_ to highlight the word when there is more than one instance of the word in the note (excluding the note title).

**Comment by MaxLap** [comment]
I'm willing to look into making a PR for this if you agree this is a bug and you haven't looked into it yet.

**Comment by scambier** [comment]
Please do 😅 I would love to have this issue solved, but too busy atm to work on it.

There has been some recent changes with PR #317, but the issue lingers

**Comment by MaxLap** [comment]
I have been unable to reproduce when using master which has #317 merged. Checking out it's previous commit, which is 1.19, makes the issues instantly apparent to me.

So I'm closing this and eagerly awaiting the next version :)
