### ISSUE TITLE
[Feature request] Ability so select the width.

### ISSUE THREAD

**Issue by tracure1337** [scambier/obsidian-omnisearch#323]
Ability so select the width.

I'd like to double the width of the search bar and results just to be able to see more information at a glance.

Thank you for your consideration.

**Comment by scambier** [comment]
The modal respects the default style provided by Obsidian. If you wish to customize the appearance, you can either modify the related css variables (e.g. `--prompt-width` or `--prompt-max-width`) or directly with [omnisearch's css classes](https://github.com/scambier/obsidian-omnisearch/blob/master/assets/styles.css)
