### ISSUE TITLE
[Feature request] Sort by modified date

### ISSUE THREAD

**Issue by gerroon** [scambier/obsidian-omnisearch#324]
**Is your feature request related to a problem? Please describe.**
It is hard to find some documents sometimes via search due to too many hits

**Describe the solution you'd like**
It would be very helpful if there is a way to sort the results based on mod/chng date since date can help with filtering the results

**Describe alternatives you've considered**
no alternatives I can tell

**Comment by scambier** [comment]
(Mostly) duplicate of #172
