### ISSUE TITLE
[BUG] Omnisearch fails on Android when searching PDF even with the text-extractor cache on the device

### ISSUE THREAD

**Issue by Araeos** [scambier/obsidian-omnisearch#326]
First off, thank you very much for developing and maintaining this plugin, it's very useful for many people.

**Problem description:**
Omnisearch does not find PDF contents on my Android phone.

I'm indexing and using Omnisearch on Windows and it shows me the expected results even in PDF files. Since the plugin should work when syncing the cache to mobile, I tried mirroring my `text-extractor` plugin folder from Windows to my Android phone using FolderSync and the cache is correctly downloaded on my phone as shown in the image.
<img src="https://github.com/scambier/obsidian-omnisearch/assets/6041246/2ceb53cb-a8a8-4d9f-9dd9-cc78ba7c5b0d" alt="My Android file structure" width="270">
Still, when searching using Omnisearch on Android fails to find the same PDF contents in my vault.

I enabled the *PDFs content indexing* and *Images OCR indexing* toggles and tried the *clear cache* option of the Omnisearch plugin to no avail. To be clear, I am **not** using the official Obsidian Sync feature, but maintain a mirror of the `text-extractor` plugin contents via an external channel.

**Your environment:**

- Omnisearch version: 1.19.0
- Obsidian version: v1.4.16
- Operating system: Android 13
- Number of indexed documents in your vault (approx.): 70 to 80  with only 1 PDF among them

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  Yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Not applicable
- Does the problem occur after a cache reset: Yes

**Comment by scambier** [comment]
This may be related to https://github.com/scambier/obsidian-text-extractor/issues/37

Is this issue still present with the latest release of Text Extractor (on both devices)?

**Comment by Araeos** [comment]
I don't know what did it, but after updating all relevant packages it now works on both of my devices. Thank you!
