### ISSUE TITLE
[Feature request] Make any property of frontmatter a display name

### ISSUE THREAD

**Issue by alumite14** [scambier/obsidian-omnisearch#329]
Please make it possible to display the value of any property embedded in the frontmatter within the file, in the part where the file name of the search results is displayed, by changing the settings.

The current situation is as follows.
![image](https://github.com/scambier/obsidian-omnisearch/assets/127008092/84af2b24-88b4-4655-8ed7-402453d0d151)

However, this makes it difficult for Zettelkasten users who use UUIDs in file names to identify files.
Therefore, it would be helpful if you could make it possible to change the part where the file name of the search results is displayed through settings (for example, through an interface like the [L7Cy/obsidian-2hop-links-plus](https://github.com/L7Cy/obsidian-2hop-links-plus) settings screen).
![image](https://github.com/scambier/obsidian-omnisearch/assets/127008092/97534837-3036-4cac-a156-f8825db1912f)

**Comment by scambier** [comment]
Published in beta https://github.com/scambier/obsidian-omnisearch/releases/tag/1.24.0-beta.2

Though it works, the result excerpt will likely display the associated frontmatter property.
