### ISSUE TITLE
No Omnisearch action on Android [BUG] 

### ISSUE THREAD

**Issue by PAGWatson** [scambier/obsidian-omnisearch#330]
**Problem description:**
I installed Omnisearch in a vault through the Community Plugins settings in the Android mobile app. I can see an "Omnisearch" button in the menu and two in the command palette (for vault and in-file search). If I select any of these, nothing happens - I just get returned to the note view, and no box comes up to enter a search query as I would expect. When I open the vault, I get a notification saying Omnisearch is indexing files and another saying when it's completed, so it seems to be doing something. Closing and reopening the app and uninstalling and reinstalling the plugin didn't help. I'm quite new to Obsidian and I've not done much to change the settings, and Omnisearch is the only plugin I've installed. I can't think of any setting in my phone that would be causing a problem.

**Your environment:**
- Omnisearch version: 1.20.1
- Obsidian version: 1.4.16
- Operating system: Android 11 (MIUI 12.5.1)
- Number of indexed documents in your vault (approx.): ~1000

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin: Yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files: Yes
- Does the problem occur after a cache reset: I don't know how to do this - but uninstalling the plugin and reinstalling it didn't fix it

**Comment by scambier** [comment]
> When I open the vault, I get a notification saying Omnisearch is indexing files and another saying when it's completed

Does this notice appear at each startup? There is maybe a cache issue, you can try disabling it in Omnisearch settings.

There are 3 ways to get crash details:
1. If you can reproduce the crash on a desktop PC, you can easily get the logs from the dev tools (ctrl shift i)
2. If you know how it works, you can access Obsidian logs through [remote debugging](https://developer.chrome.com/docs/devtools/remote-debugging)
3. You can follow [these steps](https://github.com/KjellConnelly/obsidian-dev-tools) to install another plugin that will display the logs directly inside the app

**Comment by PAGWatson** [comment]
Thanks for replying. Re 1 - it doesn't happen on my laptop. I tried 3, but searching the Core and Community plugins in the app didn't bring up a "Dev Tools" plugin or anything similarly named - is there a different way to get that?

**Comment by scambier** [comment]
my bad, I copied the wrong link for the step-by-step: https://github.com/scambier/obsidian-omnisearch/issues/137#issuecomment-1345646832

**Comment by PAGWatson** [comment]
I tried those steps and the installation of the obsidian-dev-tools still didn't work - on the BRAT plugin window, I enter the repository URL, click "Add Plugin" and then nothing seems to happen. I tried ticking and unticking "Enable after installing..." and it doesn't make a difference.

**Comment by PAGWatson** [comment]
I just thought I'd say I tried it again today and it seemed to be working - I'm not sure what changed. I will see if it stays this way.
