### ISSUE TITLE
[Feature request] Would it be possible to inject Omnisearch results into the edge browser

### ISSUE THREAD

**Issue by KuecukMimarBey** [scambier/obsidian-omnisearch#332]
**Is your feature request related to a problem? Please describe.**

Is there maybe a more general approche to implement obsidian files into the search engine ?

I would love to have this great feature on the edge browser too, right know it has a strong flow in development and its my search engine of choice, it would be great if you could implement this into the edge browser too. i sadle dont have clues to do it on my own :/

**Comment by scambier** [comment]
What do you mean by "in the Edge browser"? In the Bing search engine, or something else?

**Comment by KuecukMimarBey** [comment]
yes in the bing search engine, is this possible ?

**Comment by scambier** [comment]
Yes it's possible.

Though it's pretty low on the priority list, so if anyone is willing to work on this, the other Omnisearch userscripts are available here: https://github.com/scambier/userscripts/tree/master/src

A PR on my repo isn't necessary, you can publish your own userscript wherever and take full credit for it.

> Is there maybe a more general approche to implement obsidian files into the search engine ?

Yes, but no. Omnisearch could return a pre-rendered HTML list, but it wouldn't really blend with the specific search engine's style, and you'd still have to have custom code to inject it at the right place and time.

**Comment by scambier** [comment]
Bing userscript available at https://github.com/scambier/userscripts/raw/master/dist/obsidian-omnisearch-bing.user.js
