### ISSUE TITLE
[BUG] TAB shortcut to switch from vault search to in-file search causes command palette closure if no result is provided in vault-search

### ISSUE THREAD

**Issue by valentinosant** [scambier/obsidian-omnisearch#333]
**Problem description:**

As in the title, if vault-search doesn't provide any result, pressing TAB to switch to in-file search causes the closure of the command palette. 

**Your environment:**

- Omnisearch version: 1.20.2
- Obsidian version: 1.5.3
- Operating system: MacOS Sonoma 14.2.1 (23C71)
- Number of indexed documents in your vault (approx.): 30 (test vault)

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  \
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  \
- Does the problem occur after a cache reset: yes

**Comment by scambier** [comment]
I cannot reproduce this issue. It just switches fine to In-File, though with 0 result.

**Comment by valentinosant** [comment]
I don't know why, I don't know how.. maybe due to other plugin updates but I'm unable to reproduce the issue again.
So thanks, now It's fine.
