### ISSUE TITLE
[BUG] Quotes around exact terms do not affect in-file search

### ISSUE THREAD

**Issue by sngchn85** [scambier/obsidian-omnisearch#336]
**Problem description:**

When searching for an exact term in quotes, the vault search successfully filters down the notes it displays to only those that contain the exact search. However, the in-file search (whether selected to begin with or switched to from vault search) seems to behave exactly the same as if there are no quotes. Specifically, all tokens in the file that begin with any of the words included in the exact search match and are shown.

Here's an example screenshot:
![image](https://github.com/scambier/obsidian-omnisearch/assets/155385475/cc49bfc2-f2e9-404c-934e-e1afdf772f33)

And a screenshot of the associated logs:
![image](https://github.com/scambier/obsidian-omnisearch/assets/155385475/76170d5b-5911-4790-b775-adff0c47c7c8)

**Your environment:**

- Omnisearch version: 1.20.2 
- Obsidian version: 1.5.3
- Operating system: Microsoft Windows 11 Home 10.0.22621 Build 22621
- Number of indexed documents in your vault (approx.): 850

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  Yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Yes
- Does the problem occur after a cache reset: Yes

**Comment by Drakemoor** [comment]
I'm on
Omnisearch version: 1.21.1
Obsidian version: 1.5.8

This bug still exists. For this reason, I often have to switch back to the native Obsidian search to find what I'm looking for. It would be nice if we didn't need to juggle. 

Thank you for your consideration.
