### ISSUE TITLE
[Feature request] Compatibility with Supercharged Links

### ISSUE THREAD

**Issue by MarcosDantasdeSantana** [scambier/obsidian-omnisearch#339]
**Is your feature request related to a problem? Please describe.**
Omnisearch brings me the search results files, with a standard icon and standard color.

**Describe the solution you'd like**
If it were possible, I would like it to follow the pattern I set in the Supercharged Links Plugin

**Describe alternatives you've considered**
Show file metadata in search responses, and try to apply the settings established in Supercharged Links.

**Comment by scambier** [comment]
Closing this, please reopen if/when you have actionable items 👍
