### ISSUE TITLE
[Feature request] Aliases are missing from search

### ISSUE THREAD

**Issue by q7z** [scambier/obsidian-omnisearch#34]
While searching for files aliases are not taken into account. Would it be possible to extend the search ability to aliases too?

**Comment by scambier** [comment]
Aliases should be indexed, and they do show up in my tests. Do you have an example?

**Comment by q7z** [comment]
![image](https://user-images.githubusercontent.com/59842659/166127861-7ec06d0a-db93-4078-a3cc-cb3e55e5babe.png)

It comes up, but does not seem to especially prioritize it as a file name, it comes up as merely a content match and there is no demarcation of the title being "PC toolkit"
