### ISSUE TITLE
[Feature request] Force enable "Save index to cache"

### ISSUE THREAD

**Issue by Anarchtism** [scambier/obsidian-omnisearch#349]
**Is your feature request related to a problem? Please describe.**
I often open Obsidian on my phone and close it before Omnisearch is done indexing. This causes Omnisearch to think it crashed and disable the "Save index to cache" option.

**Describe the solution you'd like**
I want to be able to tell Omnisearch I'm an advanced user and can handle leaving "Save index to cache" on (I can always edit data.json if I need to disable the setting -- maybe make the _Force enable "Save index to cache"_ setting only modifiable by editing data.json?).

**Describe alternatives you've considered**
I've tried to make a [QuickAdd](https://github.com/chhoumann/quickadd) script run on startup to always overwrite Omnisearch's data.json, but wasn't able to make something that worked on both desktop and mobile.

**Comment by scambier** [comment]
Added a "danger zone" setting in the latest beta https://github.com/scambier/obsidian-omnisearch/releases/tag/1.24.0-beta.2
