### ISSUE TITLE
Partial search not as expected

### ISSUE THREAD

**Issue by icebruce** [scambier/obsidian-omnisearch#35]
**Partial word match not displayed as a result**

When searching for the middle or end of a term, the search does not display it as a result. 

**Steps to reproduce**
- create a new file and enter a word -> test1user
- Search for test -> file shows in results
- Search for 1use -> file does not show in results
- Search for user -> file does not show in results
- Same test works with Obsidian native search

New note
![Screenshot_2022-04-28-2 Inbox](https://user-images.githubusercontent.com/66655064/165823779-f2382bdf-95b3-4090-ab35-f128e598e753.png)
Search
![Screenshot_2022-04-28 Inbox](https://user-images.githubusercontent.com/66655064/165823787-138a1d0f-2541-4ae9-a019-adac7d6a848b.png)
Obsidian search
![2022-04-28 14_19_28-Window](https://user-images.githubusercontent.com/66655064/165823797-ebd9f450-db18-45f2-9ae5-b7b5ce800d80.png)

**Environment:**

- Omnisearch version: 1.0.1
- Obsidian version: 0.14.7
- Operating system:  Win10
- Number of notes in your vault (approx.): ~100
- Other plugins that may be related to the issue: no other search related plugins

P.S: Awesome plugin!

**Comment by AnweshGangula** [comment]
The feature request #194 only mentions partial file name search, but it would be very useful to have it in file content too.
