### ISSUE TITLE
Stronger boolean search with date range

### ISSUE THREAD

**Issue by jwhco** [scambier/obsidian-omnisearch#352]
I wrote a note last week. Searching for it by keyword isn't working even with `fuzzy enough` enabled. I don't remember if I used the term `shutdown OR close` in the document.

If I could search, `-mtime +7 (shutdown OR close) AND members` it would narrow the scope quickly. Because a search `shutdown members` or `close members` doesn't return anything relevant.

Some long specific searches, `shutdown membership site brunson kennedy` don't return anything. My assumption is the `AND` operator, where I'm scoping by speakers names and subject.

Also my expectation was that `shutdown` and `close` being synonyms would trigger something with fuzzy. I do know that the two words would be near each other, so `shutdown NEAR member` would also be useful.

An ideal solution would be GNU find commands for the date range, plus boolean for the search. This would allow scoping of a search term for more accurate results.

My Obsidian vault has 26k files. Performance is awesome. Using Omnisearch + Text Extract works consistently. Unfortunately, I either get too many results or none at all.

I'd be more than happy to test. However, I don't understand the code enough to contribute. If possible, use a common syntax library so boolean or time modifiers are familiar to the maximum number of users.

**Comment by jwhco** [comment]
I finally found the document I was seeking using `close membership kennedy brunson`, as document doesn't contain `shutdown`. However, it does include `shut it down`, `closing`, `interrruption`, and `disconnection` which are similar words. The document also contains `site`.

Interesting enough, `(close OR shutdown) NEAR membership AND (brunson OR kennedy)` comes up with my note of the original feature request with no other documents. As does `close shutdown membership brunson kennedy` but not the document I'm seeking.

**Comment by scambier** [comment]
Omnisearch is essentially a huge wrapper around [minisearch](https://github.com/lucaong/minisearch) with a bit of customization on top of it.
There's no proximity and no synonyms matching (fuzziness refers to the spelling of individual terms), and the only feature I could implement would be the boolean search (currently, all terms are combined with `AND`)

I understand those are all desirable features, but they're mostly not feasible with minisearch. I'm not against using another search engine - see #179 for a related discussion about uFuzzy -, but switching engines is not a small undertaking.

**Comment by jwhco** [comment]
Thank you for the reply. I've read the other issues, and it sounds like this feature is more for the underlying engine rather than this implementation. Fine work otherwise, thanks for what you're doing.

**Comment by ovgolovin** [comment]
@scambier Typically, recency is incorporated into search result rankings by using a decay function. Here's an example of how it can be applied in Minisearch, provided by the library's author: https://github.com/lucaong/minisearch/issues/223#issuecomment-1628669680
