### ISSUE TITLE
[BUG] Hello friend! Cannot find "Omnisearch: In-file search"

### ISSUE THREAD

**Issue by zhouxinghong** [scambier/obsidian-omnisearch#357]
**Problem description:**

Hello friend! Unable to find "Omnisearch: In-file search" command

**Your environment:**

- Omnisearch version: [1.21.1](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.21.1)
- Obsidian version: 1.5.11
- Operating system: Windows 10
- Number of indexed documents in your vault (approx.): 

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  
- Does the problem occur after a cache reset:

**Comment by zhouxinghong** [comment]
![image](https://github.com/scambier/obsidian-omnisearch/assets/54253524/56a1034b-d903-4b5e-b047-fafd993a436c)

**Comment by scambier** [comment]
You need to have an active markdown note for the In-File search to be accessible

**Comment by zhouxinghong** [comment]
> You need to have an active markdown note for the In-File search to be accessible

I don't understand what you mean, can you give me an example?

**Comment by scambier** [comment]
The "In-File Search" feature is only available when you're editing a document:
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/045e5b11-c2b5-46cd-bc73-ca6a3ab31829)


If the focus is not on the file, or if for example you're in a canvas, the option does not appear:
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/fac8ad85-3fdb-4652-8604-bebaff08d738)

**Comment by zhouxinghong** [comment]
Okay! Thank you very much for your help! I wish you: a good life! 🎉👏👍
