### ISSUE TITLE
[BUG] OCRd and cached image cannot be found in search

### ISSUE THREAD

**Issue by ivensrocha** [scambier/obsidian-omnisearch#359]
**Problem description:**

Hello, thanks for your work on this project. It has been quite helpful.

I’m trying to make an OCR’d image to be foundable on Omnisearch.
I’ve installed both Omnisearch and Text Extractor, activated it, waited a few minutes and searched for a string inside an image. I know it was cached because the cached filed exists:
<img width="1416" alt="Screenshot 2024-03-30 at 15 32 04" src="https://github.com/scambier/obsidian-omnisearch/assets/976430/565f195f-6830-4bba-96fe-50ed86077a7a">

This is the image:
![Pasted image 20240330152206](https://github.com/scambier/obsidian-omnisearch/assets/976430/c7ca9b98-b4a6-4431-a0e4-e419e74b130e)

But when I searched for a string that exists in the cache file, it results in nothing.
![image](https://github.com/scambier/obsidian-omnisearch/assets/976430/b7ff6071-48ff-4d40-84b7-0205b422cb2a)

Do you happen to know what could be the reason for this?

I have tried:
- clearing the cache
- leaving only omnisearch + text extractor plugins enabled
- searching for different words
- removing the ! in front of the image-insertion markdown code

**Environment:**

- Omnisearch version: 1.21.1
- Obsidian version: 1.5.11 (Installer 1.5.8)
- Operating system: macOS Sonoma 14.4.1
- Number of indexed documents in your vault (approx.): 36

**Comment by scambier** [comment]
So, it _should_ work 😅
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/c7129870-e350-4c08-94f4-a642b83df6c8)

Can you double check that the relevant Omnisearch setting is enabled?
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/3e88a757-c28e-459e-b844-c38f72c44f1c)

> removing the ! in front of the image-insertion markdown code

This isn't important, an image doesn't need to be linked into a note to be searchable :)

**Comment by ivensrocha** [comment]
Yes, it's enabled. Check it out:
![Screenshot 2024-03-30 at 15 55 52](https://github.com/scambier/obsidian-omnisearch/assets/976430/31253ad9-c06f-4853-8901-30bd1b7f0844)

**Comment by scambier** [comment]
- Is it the only image that you can't find?
- When you right click on the image filename and go to `Text Extractor > Extract text in a new note`, does it show you the correct text?
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/efbafb61-f3cf-4b2a-a914-9a720c950e0d)

**Comment by ivensrocha** [comment]
Nevermind, I just realized that I was searching with the default search from Obsidian 🤦 

Thanks for your time! :)
