### ISSUE TITLE
[BUG] Message: "... files need to be indexed. Obsidian may experience ..." at every start of Obsidian

### ISSUE THREAD

**Issue by merlinuwe** [scambier/obsidian-omnisearch#362]
With the latest release of your great plugin I get this message, every time I start obsidian (latest) on Windows 10 (latest).

![image](https://github.com/scambier/obsidian-omnisearch/assets/4138869/4804a088-e6dd-4be3-98a9-ddaff41e7b6a)

I cleared the cache, restarted Obsidian an get the same result.

In the console, I see this:

![image](https://github.com/scambier/obsidian-omnisearch/assets/4138869/0db3ed20-5f09-49f2-a4d8-894c55a094aa)

Restarting Obsidian again, shows again the error message. 

What can I do to solve the issue? (Reinstalling did not help.)

**Comment by scambier** [comment]
Should be fixed with 1.22.1

There's probably an issue with one of your notes during the tokenization of urls. After updating, make sure that "Save index to cache" is correctly toggled in settings.
