### ISSUE TITLE
[BUG]  iOS crash since 1.22.x

### ISSUE THREAD

**Issue by MichaelWilson-online** [scambier/obsidian-omnisearch#363]
**Problem description:**
for the longest time I have used Omni search every day, multiple times a day on all my devices.  This was my favorite plugin. 
with the latest Omni search, the latest obsidian, Omni search still works on my Mac Studio and m2 air.   On my iPhone 15 pro, iPad mini and iPad m2 pro opening obsidian with Omni search installed, obsidian locks up instantly on launch totally unresponsive.   No amount of waiting brings it back. The only way to fix it is to delete obsidian and data and install fresh and don’t since plugins.   I have tried everything including wiping my phone and installing obsidian with only the Omni search plugin.  Launch obsidian and it immediately locks up and becomes unresponsive.   Something here is broken 

**Your environment:**

- Omnisearch version: 
- Obsidian version: 
- Operating system: 
- Number of indexed documents in your vault (approx.): 

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  
- Does the problem occur after a cache reset:

**Comment by scambier** [comment]
Hello, I've pushed an update that should hopefully fix your issue. Could you update to 1.22.2 and confirm it works?

**Comment by Compg** [comment]
Not OP, but it worked for me. Had similar issue on 14 Pro Max and M2 iPad Pro. Obsidian mobile is no longer locking up.

**Comment by scambier** [comment]
Good to know, thanks for the feedback. The issue comes from the URL tokenization, so don't enable the setting 😅

I'll disable it for iOS in the next release.

**Comment by MichaelWilson-online** [comment]
The sad part is that I cannot disable anything. I must enable to disable that setting and as soon as I enable I am locked up. Thanks for the advice

—
Michael
Fighting duplicity
—not my circus, not my monkeys—

I have the full expectation of privacy with this email. Only the intended recipient(s) may read, use and respond to this email. My 4th amendment rights are secure.

**Comment by scambier** [comment]
The setting is opt-in, so disabled by default. You just need to install the latest version of Omnisearch

**Comment by scambier** [comment]
Is the issue fixed with the latest release @MichaelWilson-online?

**Comment by MichaelWilson-online** [comment]
Yes it is. Thank you

—
Michael
Fighting duplicity
—not my circus, not my monkeys—

I have the full expectation of privacy with this email. Only the intended recipient(s) may read, use and respond to this email. My 4th amendment rights are secure.
