### ISSUE TITLE
[BUG] Open note instead of navigating to the already opened instance

### ISSUE THREAD

**Issue by DivineMK** [scambier/obsidian-omnisearch#364]
**Problem description:**

When a note is already opened, searching for it will reopen the note in the current tab instead of navigating to the already opened tab. 
If this is already the intended behavior, I hope there can be an option to change to my described behavior as well.

**Your environment:**
- Omnisearch version: 1.22.1
- Obsidian version: 1.5.12
- Operating system: Linux Mint 21.3, Windows 11
- Number of indexed documents in your vault (approx.):

**Comment by scambier** [comment]
This is standard Obsidian behavior, and changing that is outside the scope of Omnisearch. There are a few plugins like [No Dupe Leaves](https://github.com/scambier/obsidian-no-dupe-leaves) (I'm also the author) that more or less fix this.
