### ISSUE TITLE
[BUG] Save index to cache gets disabled on android

### ISSUE THREAD

**Issue by charleshan** [scambier/obsidian-omnisearch#367]
**Problem description:**
"Save index to cache" gets disabled on android every few days. I see the note that says that it'll get disabled when cache write causes Obsidian to crash but Obsidian never crashed on me.

**Your environment:**

- Omnisearch version: 1.22.2
- Obsidian version: 1.5.12 (134)
- Operating system: Android 14
- Number of indexed documents in your vault (approx.): 3000

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin: I don't know. As I said before, "save index to cache" gets disabled even when Obsidian doesn't crash. I don't know what's causing the issue and I cannot reproduce the issue on the spot. It does happen quite frequently (every few days).
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files: I don't know. Same reason as above.
- Does the problem occur after a cache reset: Yes.

**Comment by scambier** [comment]
There is now a "Force save the cache" setting in the Danger Zone.
