### ISSUE TITLE
[BUG] With Omnisearch enabled, opening a note instantly after launching Obsidian leads to a delay reading it

### ISSUE THREAD

**Issue by gchegr** [scambier/obsidian-omnisearch#371]
**Problem description:**

Opening a note from the Obsidian’s explorer immediately after launching the application makes the header of the current tab change to the opened note’s name, but the contents of it gets loaded much later, up to 5 seconds, both for Windows and Android. On the smartphone it happens every launch, on desktop at least once a day.

**Your environment:**

- Omnisearch version: 1.22.2
- Obsidian version: 1.6.0
- Operating system: Windows 10, Android
- Number of indexed documents in your vault (approx.): ~1300 notes

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  yes
- Does the problem occur after a cache reset: I haven’t used caching until this point... I tried to enable it and relaunched the app several times — nothing changed, the delay is still there (at smartphone, where it’s easier to test the problem).

**Comment by scambier** [comment]
You confirm that a) the issue is present when Omnisearch is _the only_ active community plugin, and b) the issue doesn't happen when Omnisearch is not enabled?

**Comment by gchegr** [comment]
Android — yes, for both A and B.
I’ve yet to confirm it for desktop, since this behavior doesn’t happen each time. So far no lags with the plugin disabled.

**Comment by scambier** [comment]
This freeze is more than likely Omnisearch cache being deserialized and loaded into memory 🤷‍♂️

The only alternative is to disable the cache, which will remove the hard freeze but will make Obsidian sluggish while Omnisearch re-reads all the files at startup.
