### ISSUE TITLE
[Feature request] Can you add delay or button press for starting search

### ISSUE THREAD

**Issue by ZobaJakColbert** [scambier/obsidian-omnisearch#378]
**Is your feature request related to a problem? Please describe.**
When I'm trying to search for something and write first letter Omnisearch freezes up, because it starting to search every note with this letter. For example I want to search for Hero, then Omnisearch after I write letter "H" freezes up.

**Describe the solution you'd like**
Maybe add option to search only after pressing Enter.

**Describe alternatives you've considered**
Or maybe add variable in Settings that user can set miliseconds after which Omnisearch starts searching. For example user input 3000 ms, then Omnisearch starts searching after last keystroke was latter than 3000 ms.

**Additional context**
I uploaded video with my problem.

https://github.com/scambier/obsidian-omnisearch/assets/57141103/83d7c117-966a-49e9-938a-11effa498c9c

I've searched for HERO. Then I remove whole word. And starting to write word Hero. Omnisearch hangs up on first letter. After 110 seconds it unfreezes. After this time I've got randomly those options: 
1. search is done correctly (like on video)
2. only first letter is inputted
3. nothing is inputted. Query is empty.

**Comment by scambier** [comment]
In Omnisearch settings > Behavior, could you enable the "Simpler search" option, and see if it improves the delay?

**Comment by ZobaJakColbert** [comment]
Yes, with Simpler search now this is working. Searching is instant.
