### ISSUE TITLE
What is the shortcut to open the search box for obsidian-omnisearch

### ISSUE THREAD

**Issue by adonis-lau** [scambier/obsidian-omnisearch#379]
I checked the readme and issues and couldn't find any hints about it.
If there is, please let me know, thank you.

**Comment by scambier** [comment]
There isn't any shortcut set by default, it's up to the user to configure it directly in Obsidian

![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/6a53e991-d522-41fd-bd17-15a8cf6a2874)

**Comment by adonis-lau** [comment]
Alright, thank you.
