### ISSUE TITLE
[BUG] Can no longer type "ó" character, because it opens a selected item instead

### ISSUE THREAD

**Issue by beetrootpaul** [scambier/obsidian-omnisearch#380]
**Problem description:**

Disclaimer: I am not sure if to categorize this as a bug or a feature request. I am convinced I was able to type "ó" (Opt+O) before, but maybe I never really did that? The probability is very low because I use Omnisearch for a long time already, but I cannot assure for 100%. Therefore it _feels_ to me like this is a regression to my usual usage of Omnisearch, hence "bug".

The problem:
- in Polish language we use some characters that are not present in English, like `ą/Ą`, `ł/Ł` or `ó/Ó` (see [this Wikipedia page for a full list](https://en.wikipedia.org/wiki/Polish_alphabet))
- we type those characters with `Alt/Opt + <letter>` (optionally with `Shift` as well, if we want uppercase)
- sometimes some apps decide to bind some actions to some `Opt + <letter>` combinations, thus breaking the ability to type aforementioned letters
- it feels like a similar thing happens in Obsidian, because when I try to type `półkolonie`, the `płkolonie` is typed instead and, if typed slowly, Omnisearch also manages to open the currently highlighted result in background

<img src="https://github.com/scambier/obsidian-omnisearch/assets/92947323/ad52112b-e690-4edf-bcbb-83cf67b3bd36" width="400">

**Your environment:**

- Omnisearch version: `1.23.1`
- Obsidian version: `v1.6.5`
- Operating system: macOS Sonoma 14.5
- Number of indexed documents in your vault (approx.): have no idea… 1000 maybe? (maybe it could be displayed in Omnisearch settings?)

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  YES
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  I didn't check that
- Does the problem occur after a cache reset: YES

**Comment by scambier** [comment]
👍 I'll change the shortcut as ctrl+o

**Comment by scambier** [comment]
Fixed in https://github.com/scambier/obsidian-omnisearch/releases/tag/1.24.0-beta.2

**Comment by beetrootpaul** [comment]
I just updated the Omnisearch and confirm the fix works OK, thx!
