### ISSUE TITLE
[BUG] Enter key inserts return character at start of result

### ISSUE THREAD

**Issue by krausekai** [scambier/obsidian-omnisearch#39]
**Problem description:**

Pressing Enter on an omnisearch modal result will jump to it as it should, but will also insert a return character at the start of the result line, editing the document with an empty line in the process

**Your environment:**

- Omnisearch version: 1.0.1
- Obsidian version: v0.14.6 (same as installer version)
- Operating system: Windows 10
- Number of notes in your vault (approx.): 150
- Other plugins that may be related to the issue: Disabled

**Comment by scambier** [comment]
This should be fixed in [1.1.0](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.1.0)
