### ISSUE TITLE
[Feature request] Ignore Obsidian linking syntax when searching

### ISSUE THREAD

**Issue by ThatXliner** [scambier/obsidian-omnisearch#391]
**Is your feature request related to a problem? Please describe.**
E.g. When I type in "banana" it won't give me results for notes that contain "[[Yellow fruit|Banana]]" (which is [Obsidian linking syntax](https://help.obsidian.md/Getting+started/Link+notes#Step+1+Create+a+link))

**Describe the solution you'd like**

Self explanatory

**Describe alternatives you've considered**

N/a

**Additional context**

**Comment by scambier** [comment]
Well, it does. At least for "banana".

![image](https://github.com/user-attachments/assets/ccb28f05-91ef-4908-a3f5-2390a26a33d6)

Is there a specific alias that doesn't work in your vault?

**Comment by ThatXliner** [comment]
Interesting. I think it was just a glitch as I don't think I can reproduce anymore. I'll open this up if the issue arises again even after a restart
