### ISSUE TITLE
[Feature request] Add in settings 'Binding Host' and "Api key" for autorization header

### ISSUE THREAD

**Issue by azdolinski** [scambier/obsidian-omnisearch#396]
**Is your feature request related to a problem? Please describe.**
Im using obsidian inside docker. 
Omnisearch accept only HTTP API request on 127..1 so it is impossible to map port from outside docker to localhost.
In setting section there is no option to change binding host to 0.0.0.0.

**Describe the solution you'd like**
As in title: Add in settings 'Binding Host' and "Api key" for autorization header (as this will be now in on external interface so some base auth would be nice option). 
Do not need for now any SSL / just pure HTTP with basic Authentication would be ok.

**Describe alternatives you've considered**
N/A

**Additional context**
Im using now standard search 'Local REST API' plugin for search content of my obsidian note by llm agent. 
It would be nice to have option to do same via omnisearch plugin.

**Comment by scambier** [comment]
You can edit the file `.obsidian/plugins/omnisearch/data.json` and manually set the value `"DANGER_httpHost": "0.0.0.0"`. It's not supported through settings because I don't want to be responsible for users who may accidentally expose their entire vault through this.

No support yet for auth (or other) headers though.

**Comment by azdolinski** [comment]
Thank you, that is sufficient for my needs. I can configure additional proxy settings and expose them with authentication. I quickly scanned the code for 'http<b>Api</b>Host/Bind' and didn't find it, which is why I asked.
