### ISSUE TITLE
[Feature request] Support Iconize Plugin

### ISSUE THREAD

**Issue by acrylicus** [scambier/obsidian-omnisearch#400]
## **Is your feature request related to a problem? Please describe.**

My job requires a lot of multicloud, unfortunately a lot of the terminology is shared across cloud providers (I.e. VPC in both GCP + AWS). So I use Iconize to keep track of things for quick-glance stuff, i.e. the AWS icon for VPC is very different to the GCP icon for VPC. Currently omnisearch does not include the icons

## **Describe the solution you'd like**
To give you an idea, this is how I have my notes structured:
<img width="313" alt="image" src="https://github.com/user-attachments/assets/a43d441b-0752-4d0d-9279-9a0a1c1f38a2">

But in the search they all show up like this 

<img width="780" alt="image" src="https://github.com/user-attachments/assets/a26e79df-085c-4bbc-a518-9461e8723b9a">

Would be great if it looked like this
<img width="778" alt="image" src="https://github.com/user-attachments/assets/0aad9140-3fb8-4061-b028-16facc3036c7">

## **Describe alternatives you've considered**
For now I just read the file path to work it out, which is fine, but having the actual icon show up would be great
## **Additional context**
Screenshots above.

To be clear its not *just* VPC, there are lots of examples (i.e. AWS Privatelink, Azure Privatelink, IAM is used on all 3, Load balancers, KMS etc etc)

**Comment by acrylicus** [comment]
@scambier any chance you can weigh in on whether you think this is something you will put some time into? I can have a crack at it if not (though I am a shit coder lol)

**Comment by scambier** [comment]
Iconize has a work-in-progress API, which looks like it doesn't (yet?) have a function to get an icon from a path: see [here](https://github.com/FlorianWoelki/obsidian-iconize/issues/155) and [there](https://github.com/FlorianWoelki/obsidian-iconize/blob/main/src/lib/api.ts).

It's certainly possible to do without it - basically replicate what Iconize is doing -, but I'd rather rely on a stable API.

**Comment by acrylicus** [comment]
Good spot @scambier - I will keep my eyes peeled for the release of the API. Looks to be coming soon from their most recent commit.

**Comment by acrylicus** [comment]
Hi @scambier - in lieu of the API can we not just use the `data.json` file in the plugin folder?

```json
❯ cat data.json | head -40
{
  "settings": {
    "migrated": 6,
    "iconPacksPath": ".obsidian/icons",
    "fontSize": 16,
    "emojiStyle": "native",
    "iconColor": null,
    "recentlyUsedIcons": [
      "AwResAmazonVPCEndpoints48",
      "AwResAmazonVPCNetworkAccessAnalyzer48",
      "AwResAmazonVPCReachabilityAnalyzer48",
      "LiWheat",
      "LiCandyCane"
    ],
    "recentlyUsedIconsSize": 5,
    "rules": [],
    "extraMargin": {
      "top": 0,
      "right": 4,
      "bottom": 0,
      "left": 0
    },
    "iconInTabsEnabled": true,
    "iconInTitleEnabled": true,
    "iconInTitlePosition": "inline",
    "iconInFrontmatterEnabled": true,
    "iconInFrontmatterFieldName": "icon",
    "iconColorInFrontmatterFieldName": "iconColor",
    "iconsBackgroundCheckEnabled": true,
    "iconsInNotesEnabled": true,
    "iconsInLinksEnabled": true,
    "iconIdentifier": ":",
    "lucideIconPackType": "native",
    "debugMode": false
  },
  "Project Notes/Customers": "OcPersonFill16",
  "Tech Notes/GCP": "SiGooglecloud",
  "Tech Notes/Fortinet": "SiFortinet",
  "Tech Notes/Azure": "SiMicrosoftazure",
  "Tech Notes/AWS": "FabAws",
<...>
❯ cat data.json | tail -20
  "Tech Notes/AWS/Networking & Content Delivery/VPC/Reachability Analyzer.md": {
    "iconName": "AwResAmazonVPCReachabilityAnalyzer48"
  },
  "Tech Notes/AWS/Networking & Content Delivery/VPC/Network Access Analyzer.md": {
    "iconName": "AwResAmazonVPCNetworkAccessAnalyzer48"
  },
  "Tech Notes/AWS/Networking & Content Delivery/VPC/Endpoints": "AwResAmazonVPCEndpoints48",
  "Tech Notes/AWS/Networking & Content Delivery/VPC/Endpoints/Endpoints Overview.md": {
    "iconName": "AwResAmazonVPCEndpoints48"
  },
  "Tech Notes/AWS/Networking & Content Delivery/VPC/Endpoints/Gateway Endpoints.md": {
    "iconName": "AwResAmazonVPCEndpoints48"
  },
  "Tech Notes/AWS/Networking & Content Delivery/VPC/Endpoints/Interface Endpoints.md": {
    "iconName": "AwResAmazonVPCEndpoints48"
  }
}%
```

**Comment by acrylicus** [comment]
I have managed to get this working :)

<img width="780" alt="image" src="https://github.com/user-attachments/assets/db5440f5-8241-4e90-999b-00381a89c171">

I have created a pull request here https://github.com/scambier/obsidian-omnisearch/pull/405

**Comment by scambier** [comment]
Done and published in beta, thank you.
