### ISSUE TITLE
[BUG] I am unable to input anything, and the software freezes. 

### ISSUE THREAD

**Issue by itangqiao** [scambier/obsidian-omnisearch#406]
“I have encountered a serious problem. I’ve tried both the latest stable version and the beta version, but the same issue occurs. I hope it can be resolved as soon as possible. This is really important to me. Thank you!”

https://github.com/user-attachments/assets/771d1955-33a9-4a4f-8144-14fc57da3ca0

![iShot_2024-09-30_20 07 50](https://github.com/user-attachments/assets/0ed387e2-3795-4b0d-be46-2c573de07775)
![iShot_2024-09-30_20 08 02](https://github.com/user-attachments/assets/36192be3-8e67-44c4-a492-bac972849396)
![iShot_2024-09-30_20 08 13](https://github.com/user-attachments/assets/55526f17-8107-45bd-a4a7-58e469f5d1b2)
![iShot_2024-09-30_20 08 21](https://github.com/user-attachments/assets/db8ad2e7-6ced-4ffa-a8cf-2fe92b359bf5)

- Omnisearch version: Both 1.24.1 and Beta version
- Obsidian version: v1.6.7
- Operating system: MacOS 15，Mac Studio M1 Max
- Number of indexed documents in your vault (approx.):

**Comment by scambier** [comment]
Please follow these steps to gather some logs:
- Clean the cache and restart Obsidian (and wait it's done indexing)
- Enable the "Simpler search" toggle
- Enable the "Verbose logging" toggle
- Activate the developer tools with cmd+option+i and select the "Console" tab

Omnisearch should hopefully log a bunch of things before crashing. Could you take a screenshot of these logs please?

**Comment by itangqiao** [comment]
Enable the "Simpler search" toggle, solved my problem. I really like this plugin, thank you!

**Comment by scambier** [comment]
For reference, it looks like a sort of duplicate of #208, with a possible explanation [here](https://github.com/scambier/obsidian-omnisearch/issues/208#issuecomment-1710050745)

**Comment by itangqiao** [comment]
Received.
