### ISSUE TITLE
[BUG] Latency when indexing notes

### ISSUE THREAD

**Issue by rvzaytsev** [scambier/obsidian-omnisearch#409]
When I add a new file, omnisearch can't find it.
E.g. I add a file some_unique_name.md and look for it in omnisearch - it doesn't show up for a while. I tried restarting obsidian - still doesn't show up. Then may be after some time it will begin showing up. But that's no good, this behaviour is too unpredictable.

**Problem description:**

**Your environment:**

- Omnisearch version: latest
- Obsidian version: latest
- Operating system: ubuntu 20.04
- Number of indexed documents in your vault (approx.): 1000

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files: yes  
- Does the problem occur after a cache reset: yes

**Comment by scambier** [comment]
When creating a bug (or a feature request) on this repository, there's a template that asks a few questions that give me some information that might be important and pushes the user to perform a few checks.

Please edit this post accordingly and do the few checks it asks, thank you

**Comment by scambier** [comment]
There might be a latency when Omnisearch is still actively indexing your notes, especially when Text Extractor is enabled ; newly create files are added at the end of the processing queue.

Could your please try these steps:
- Disable Text Extractor
- Clear Omnisearch's cache
- Restart Obsidian
- Wait for the notification saying that indexing is done
- Create a new note and save it

The note should be indexed in Omnisearch after at most a few seconds

**Comment by rvzaytsev** [comment]
I see what the bug is now. There is no setting to search for a folder. You can only search for a folder if that folder contains a document that is indexed. So, if I create a folder with a bunch of pdfs and disable content indexing - I can search for the folder, I can search those pdf names - nothing shows up. Now index path of unsupported files resolves one of the issues - I can now search paths that contain pdfs. But I still can't search empty folder names. 
Anyway, this issue is of course resolved - I'll just clear cache when omnisearch becomes disfunctional. But I note that there is still an issue of not being able to just search for a folder and open it in navigation. Though that is also a general problem in Obsidian, which doesn't allow to just search and open folder in navigation.
