### ISSUE TITLE
Make a Settings page

### ISSUE THREAD

**Issue by scambier** [scambier/obsidian-omnisearch#41]
A basic settings page, with

- [x] ~~Some explanations on how results a returned~~ Weightings
- [x] A toggle to downrank "Excluded files" in Obsidian's settings

More settings to add later, and to be defined in new issues

**Comment by lguenth** [comment]
Adding to this: I would love this plugin even more if I could disable the status bar stats and indexing notices.

**Comment by scambier** [comment]
@lguenth Ok for the notices, but there aren't any status bar stats for Omnisearch (or at least, nothing that is explicitely defined)
