### ISSUE TITLE
[Feature request] Reverse Tab-Opening Behavior (or Add Toggle to Customize It)

### ISSUE THREAD

**Issue by greetclammy** [scambier/obsidian-omnisearch#415]
Is your feature request related to a problem? Please describe.

I'm frustrated with the current tab-opening behavior in the OmniSearch plugin. When I press `Enter` on a search result, it opens the note in a new tab. To open a note in the same tab, I have to press `Command + Enter.` This setup feels unintuitive and inconsistent, especially since most other apps—including web browsers and Obsidian’s native Quick Switcher—use `Command + Enter` (or `Command + Click`) to open in a new tab or window.

Describe the solution you'd like

Please switch the default behavior: pressing `Enter` should open a note in the same tab, while pressing `Command + Enter` should open it in a new tab. Alternatively, add a toggle in the settings to let users configure which key combination opens a note in the same or a new tab, making it more customizable.

Describe alternatives you've considered

I’ve tried to adjust my workflow to accommodate the current setup, but the inconsistency compared to the Quick Switcher and common app standards continues to disrupt my flow. I’ve also looked into alternatives to OmniSearch, but I find its features useful and don’t want to switch plugins entirely over this one functionality.

Additional context

This would bring OmniSearch more in line with common user interface practices, improving the overall experience. A setting to control this behavior would also give users flexibility to align it with their preferred workflows.

**Comment by scambier** [comment]
There's this setting, under the "Behavior" section
![image](https://github.com/user-attachments/assets/b07619ca-b04d-4dfa-bad5-ecbd8e04209f)

If you uncheck it, Omnisearch should have the expected behavior
