### ISSUE TITLE
[BUG] Alt+O doesn't not work after recent upgrade - Ubuntu Linux 24.04

### ISSUE THREAD

**Issue by kirtr** [scambier/obsidian-omnisearch#418]
**Problem description:**
When the omnisearch list comes up and shows matching results, one of the options is to open the note in a new tab with Alt+O. This now does nothing. 

**Your environment:**
- Omnisearch version: 1.25.1
- Obsidian version: 1.7.6
- Operating system: Ubuntu 24.04
- Number of indexed documents in your vault (approx.): 500

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  yes
- Does the problem occur after a cache reset: yes

I have booted an ubuntu live cd, installed Obsidian and Omnisearch in a clean environment and then tested and the problem exists there. 
If you wish to test, the Obsidian appimage currently needs libfuse2 installed with "sudo apt install libfuse2t64". Launch with <filename>.Appimage --no-sandbox

Are there any other Linux, Ubuntu or Gnome users here? Is it working for you?

**Comment by scambier** [comment]
The label is incorrect, the correct shortcut is ctrl+o (changed in #380)
