### ISSUE TITLE
[BUG] In-file search for PDFs works only on Mac but not iOs

### ISSUE THREAD

**Issue by stardustx8** [scambier/obsidian-omnisearch#421]
**Problem description:**

Search results in "In-File" mode are dissimilar between Mac and iOs when the search term appears in a PDF file.

**Your environment:**

- Omnisearch version: 1.25.1
- Obsidian version: 1.7.7 / I'm using Obisidian Sync
- Operating system: iOS 18.2 / MacOS
- Number of indexed documents in your vault (approx.): 4k

I did already try cache reset with the same issue resulting.
As far as I read, Text Extractor is not able to do the indexing of ex. PDFs on iOs but says in the setings that it can synchronize the cache to mobile devices.

**Comment by scambier** [comment]
Text Extractor by itself doesn't sync its cache, the sync must be done through external means. It also doesn't work with Obsidian Sync, so I'm not sure what options are available on iOS

**Comment by stardustx8** [comment]
Thanks so much for your prompt info - all clear.

Best
