### ISSUE TITLE
[BUG] Update not installing

### ISSUE THREAD

**Issue by nogira** [scambier/obsidian-omnisearch#43]
**Problem description:**

I have v1.0.1

Trying to update to v1.2.0 using the default obsidian addons manager doesn't work. Installing popup comes up, but the version stays the same, and then when you check again for updates the v1.2.0 update appears again.

I have tried uninstalling the addon, then redownloading, but it is still v1.0.1

**Your environment:**

- Omnisearch version: v1.0.1
- Obsidian version: v0.14.6
- Operating system: macOS 12.3
- Number of notes in your vault (approx.): 2k

**Comment by scambier** [comment]
It should be good now.
That's weird though, because I have a vault with the production version of Omnisearch, and it updated correctly :/ I'll check how other plugins manage beta releases

**Comment by nogira** [comment]
yep, updated to 1.2.1 fine :)
