### ISSUE TITLE
[BUG] Mobile: 1.2.0 doesn't show any results ...

### ISSUE THREAD

**Issue by avirosso** [scambier/obsidian-omnisearch#44]
Android 11
Obsidian Mobile (Version 1.2.0 / API von 0.1.2))
Omnisearch (Version 1.2.0)
Number of notes in vault: 2967

Omnisearch V 1.0.1: Vault Search worked on mobile. 

After update to Omnisearch 1.2.0 (and Obsidian restart) the plugin indexes the vault ("Indexed 2967 notes"), but doesn't show any results (always shows: "We found 0 result for your search here")

**Comment by scambier** [comment]
Fixed in 1.2.1. Unfortunately, the API to check if a file is excluded doesn't work on mobile.

**Comment by avirosso** [comment]
Thanks!
