### ISSUE TITLE
[Feature request] Search Filter Quotation Mark -> Hotkey Helper on Modal 

### ISSUE THREAD

**Issue by FelipeRearden** [scambier/obsidian-omnisearch#45]
Hello again @scambier !!!!

Thank you very much for the features from #25 . I really need the quotation marks `” “`

MY FR: Would be possible to add a hotkey when the modal in open to quickly add the quotation marks  `” “` in the search text field 

➡️ The caret cursor is between each quotation mark :)

![C0C2F3D0-7069-4A24-A1D8-417B8B198016](https://user-images.githubusercontent.com/85180696/166930665-018b1db8-cc47-4df6-8230-928838491ee5.jpeg)

🔠 My Suggestion is the `TAB` key as a hotkey 

---

Let me know what you think 

Thanks for reading this!

Have a great day!!!!

**Comment by scambier** [comment]
I'm don't see the added value of a dedicated hotkey to insert a pair of quotes, sorry... That's not like pressing a single key instead of 2 would change something.
