### ISSUE TITLE
show the results sorted on descending "highest number of matches"

### ISSUE THREAD

**Issue by jaroet** [scambier/obsidian-omnisearch#47]
Running with the latest omnisearch and Obsidian version. 

Thanks for this plugin freeing me from the small sidebar using the regular search :-).

I understand you prioritize results with the search-term in the page name above others and that seems fine ... but I wander how the  find-results that do not have the search-term in the pagename are sorted. 

I would expect it to be sorted on matched as when a search-result is found multiple times in a page it should (IMHO) be presented higher on the list of search results then a page that has the search result on once in the page. 

But currently it does not.

**Comment by scambier** [comment]
The search algorithm is [more complex than that](https://github.com/lucaong/minisearch/blob/master/DESIGN_DOCUMENT.md). Actually the number of matches is mostly informative, and not (directly) related to the scoring ; results with a higher number of matches usually score higher, but not necessarily. See these 2 points:

> - If a term is less common, the score should be higher (like TD-IDF).
> - If a term occurs more frequently, the score should be higher (so far this is the same as TD-IDF). But the relationship is not linear. If a term occurs twice as often, the score is not twice as high.


 On top of that, Omnisearch boosts results where the query terms are found in the filename or headings.
