### ISSUE TITLE
[BUG] Unable to open note when filename contains # character

### ISSUE THREAD

**Issue by quinncomendant** [scambier/obsidian-omnisearch#49]
**Problem description:**

Omnisearch is unable to open notes which contain a `#` character in the filename. Instead, a new note is created. Obsidian's built-in *Quick switcher* is able to open files with # in filename successfully.

I can recreate the problem like this:

1. Create a note named, e.g., `Crazy #hashtag time!`
2. Invoke *Omnisearch: Vault search*
3. Type `Crazy` and this note is the first match
4. Hit `return` to open this note
5. A *new* note is created named `Crazy`

Here's a screencast showing 1) Omnisearch creating a new note instead of opening the note `Crazy #hashtag time!`, and 2) Quick switcher opening this note successfully.

![Screen Recording 2022-05-14 at 10 44 52](https://user-images.githubusercontent.com/6884276/168439311-3c916b71-1b29-407e-8a0f-9f5ec44c2ee5.gif)

I expect Omnisearch to open the note `Crazy #hashtag time!`, not to create a new note named `Crazy`. A new note should only be created when typing `Shift-return`.

I know Obisidian recommends not using `#` character inside note titles, but I have imported many notes from other sources and some contains `#`. Although it's a rare edge case, it's probably easy to fix?

**Your environment:**

- Omnisearch version: 1.2.1
- Obsidian version: v0.14.6
- Operating system: macOS 12.3.1
- Number of notes in your vault (approx.): 500
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Are there other community plugins that manage to do this? Because what's happening is that Omnisearch calls the `openLinkText()` function, but Obsidian somehow fails to open the note thus creates a new one.

**Comment by quinncomendant** [comment]
> Are there other community plugins that manage to do this? 

I'm not aware of any. Obsidian's built-in *Quick switcher* works fine, but as a core plugin it might use private APIs to open the note.

**Comment by scambier** [comment]
Obsidian bug:
- https://forum.obsidian.md/t/poor-handling-of-character-in-the-filepath-aka-hashtag-pound-octothorpe/3192/11
- https://forum.obsidian.md/t/make-links-work-also-for-filenames-that-contain/13732

Unlikely to be fixed in the short term. It looks like Obsidian handles these files with minimal issues, but the same can't be said for the public API.
