### ISSUE TITLE
[BUG]"In-file search": If note is 'pinned', the note opens a second time / duplicate

### ISSUE THREAD

**Issue by avirosso** [scambier/obsidian-omnisearch#51]
**Problem description:**

"In-file search": If note is 'pinned': 

Opening a search hit with 'return' opens the note a second time (a duplicate of the note)

**Comment by scambier** [comment]
It looks like an Obsidian bug (or feature, depending on how you consider pinned notes), and even if I determine that the note is already open, setting the focus on it has no effect.

**Comment by scambier** [comment]
It's a half-fix: the note scrolls where it should, but I cannot make it active to set the cursor 🤷‍♂️
