### ISSUE TITLE
[BUG] search `passw` then obsidian stuck

### ISSUE THREAD

**Issue by Jackiexiao** [scambier/obsidian-omnisearch#56]
when I search `passw`, the obsidian stuck (no response), I have to force close obsidian and relauch it. everything works well until I enter the last character `w`  (btw, `pasas` also trigger this bug)

![image](https://user-images.githubusercontent.com/18050469/168994682-fd907578-2d25-4b8a-be84-de94944ab162.png)

**Your environment:**

- Omnisearch version: v1.2.1
- Obsidian version: v0.14.12
- Operating system:  window11
- Number of notes in your vault (approx.): 2 thousands
- Other plugins that may be related to the issue: I am not sure

**Comment by scambier** [comment]
This bug should be fixed in the current [1.3.0-beta](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.3.0-beta), which can be installed manually or through BRAT

**Comment by Jackiexiao** [comment]
ok thx

**Comment by scambier** [comment]
Reopening to backport the fix in 1.2
