### ISSUE TITLE
[Feature request] Plugin settings for disabling real-time indexing for large documents

### ISSUE THREAD

**Issue by shaggyfeng** [scambier/obsidian-omnisearch#57]
**Is your feature request related to a problem? Please describe.**

When typing in a document that has a lot of words (300,000ish), this plugin will cause some lag. I tested it many times to make sure the lag was caused by Omni Search.

**Describe the solution you'd like**

It would be great to have a plugin option to turn off real-time indexing for documents that have more than a certain number of characters. 

**Describe alternatives you've considered**

Or simply provide an option to only index new words when opening obsidian. That might fix the lag, I guess.

**Additional context**

Your plugin is the best searching plugin IMO! Thanks

**Comment by scambier** [comment]
> When typing in a document that has a lot of words (300,000ish), this plugin will cause some lag.

Oh boy I'm sure it does. Is the lag longer than 1-2 seconds?

If not, what about an option to re-index edited documents when Obisidian is alt-tabbed out? So the indexing is done in the background, and should be done once you're back.

> Your plugin is the best searching plugin IMO! Thanks

❤

**Comment by shaggyfeng** [comment]
> 

Well, whenever I tried to type anything, anywhere within a large document, input would lag for 1 second. 

Indexing in the background does sound like a good idea. I guess as long as no indexing happens when writing or editing a large document, we should not have any lagging issues. 

Thanks

**Comment by scambier** [comment]
Fixed and published in 1.3.2-beta (accessible through BRAT)

**Comment by shaggyfeng** [comment]
> Fixed and published in [1.3.2-beta](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.3.2-beta) (accessible through BRAT (乳臭未干) )

When I copy text from another APP to Obsidian, the cursor will lag for a few seconds if the MD file has a lot of words (200k) in it. When I turn the omni plugin off, there is no lag.

**Comment by scambier** [comment]
@shaggyfeng can you make sure that this setting is unchecked?
![image](https://user-images.githubusercontent.com/3216752/172777011-80ed9e4a-9080-45dc-ae5d-b0105b0b86ca.png)

If that's the case, does the lag happen only when you first paste the text, or every time you write something?

**Comment by shaggyfeng** [comment]
> 
The lag happens only when I first paste the text (tab out of obsidian). If I copy outside of obsidian and paste inside of obsidian, it lags. So if you add a delay to indexing after tab-out of obsidian, it should work just fine. Maybe something like a 15 or 20 seconds delay will be all right.

**Comment by scambier** [comment]
I'll tweak the settings to get something less intrusive.

**Comment by shaggyfeng** [comment]
> I'll tweak the settings to get something less intrusive (侵入) .

Is it a good idea to terminate the indexing if a user tabs back to obsidian and the indexing is still running after, let's say 1000ms? Just a thought. Just ignore me if it is not helpful. 

Thanks

**Comment by scambier** [comment]
Nope sorry. Once a document is starting to get indexed, you can't stop it; it's a synchronous process. You can stop between documents, but I don't think it'd be useful in your use-case, since you're alt-tabbing and copying (I guess) one document at a time.

If the startup indexing time is also a problem for you, the latest beta introduced a feature to save the index on disk and reload it at startup.
