### ISSUE TITLE
Add a setting to display the short form of links in search results

### ISSUE THREAD

**Issue by icebruce** [scambier/obsidian-omnisearch#59]
**Problem description:**
After searching and selecting a note, the file does not open. Using the arrow keys+enter or with the mouse does not open the selected note. 

The strange thing is that it does not happen to all notes, only certain ones and at ad-hoc. After these notes are "stuck", using the built-in Obsidian search resolves the issue and I can go back and open them via Omnisearch. The notes in question are relatively easy, without any special characters or content.

https://user-images.githubusercontent.com/66655064/170407044-415002eb-37d9-4a20-a72e-35522b8c2872.mp4

**Environment:**
- Omnisearch version:
- Obsidian version: 0.1.7
- Operating system: Windows 10
- Number of notes in your vault (approx.): ~100
- Other plugins that may be related to the issue: n/a

**Comment by scambier** [comment]
Hello, is there any error log in the console (Ctrl shift i)?

**Comment by scambier** [comment]
Could you check Obsidian and Omnisearch versions? Omnisearch is at 1.3.3 and Obsidian should be at 0.14.2

**Comment by icebruce** [comment]
Obsidian is at 0.14.15.
Strangely Obsidian was not providing the latest omnisearch update. I had to uninstall and re-install to get the latest version, now everything seem to be in order.

There is another issue I came across however. The file name in the search pane now shows the full path of the file instead of the file name. I checked in obsidian settings and I do have the option for showing the "shortest path when possible" under link format (in case its related). 

Any ideas?
![image](https://user-images.githubusercontent.com/66655064/170892424-29107e3c-94ef-4c38-9753-d7af8a3ec808.png)

**Comment by scambier** [comment]
This is the intended behavior, it mimics the Quick Switcher.

> I do have the option for showing the "shortest path when possible" 

I took a quick look, and Obsidian's public API does expose this setting, nor does it provide a function to get the short form of a link. I'll keep this issue open and ask around; if there's a built-in way I'll add a setting 👍

**Comment by icebruce** [comment]
Weird, now I wonder why it was actually showing the filename before. And I think I did not pay attention to the native switcher, you are right it is also showing the full path.

>I took a quick look, and Obsidian's public API does expose this setting, nor does it provide a function to get the short form of a link. I'll keep this issue open and ask around; if there's a built-in way I'll add a setting 👍

Thanks for this! Personally I would love to have that option. If its ever of any help, I found [this ](https://forum.obsidian.md/t/toggle-show-full-path-in-quick-switcher/21976)thread talking about this topic. [This plugin](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher) actually has that enabled by default.

**Comment by scambier** [comment]
Oh ok, I misunderstood (and probably though a bit too far). Actually I _can_ display the short name without the full path, that's not an issue. What I can't do easily is reproduce Obsidian behavior that **shows the short name only if there is no more than 1 file with this name**. That's what the "shortest path _when possible_" option does.

I'll add a setting to just toggle between short name / full path 👍
