### ISSUE TITLE
[Feature Request] Multiple Matches in the Same Note

### ISSUE THREAD

**Issue by FelipeRearden** [scambier/obsidian-omnisearch#6]
Hello @scambier !!!!

My FR is about the modal behavior when we have more than one match in the same note.

Example: my `Chicago Bulls.md` has 4 entries for the term `Michael Jordan`
- line 5
- line 50
- line 122
- line 400

## My FR

Would be very helpful to have each math visible and separated in the modal:
- From my tests, the modal only the first 2 matches from a single note. 

This FR would an productivity if combined with #5  
- We could selected in the modal exactly the position in the nothe that we are looking for and open the note in the exactly position :)  

---

Thank for reading this :)

Have a great day!!!!!

**Comment by scambier** [comment]
The issue with this request (as useful as it is for long documents), is that it's becoming unusable when you have more than 4-5 matches per file.

If you look for "search" in the Help vault, The Search.md note has 44 matches for "search", 5 for "searching", 2 for "searched" and 1 for "searches". That's 52 matches to display and scroll through, _for a single file_. It is absolutely ridiculous, and also a part of why the core search plugin is so bad.

I'm open to suggestions on how to solve this from a UI (and UX) point of view.

**Comment by FelipeRearden** [comment]
> I'm open to suggestions on how to solve this from a UI (and UX) point of view.

How about a fold ⬇️ unfold ⬆️ button in the **filename.md line** ?
- The first 3/4/5 will always be visible and if the note has more 44 matches, it will be hidden and only if the user click in the **filename line**

"Open the Filename.md" could open a new modal that brings all 52 matches from this note :)

Just an idea for us to talk about :) 

Have a great day!!!

**Comment by scambier** [comment]
The latest update brings another modal to list search matches within a note. It's accessible with `alt-enter` from the "vault search" modal. Does this fulfill this feature request?

**Comment by FelipeRearden** [comment]
Hello @scambier !!

I update for the latest version and I really like the way that you add this FR !!!!

I'm gonna start to use the modals and give some feedback. 

But for me, this FR, which is about supporting multiples matches from the same note can be **closed** with a huge success !!!!

Let's wait for the @chrisgrieser feedback because I know that he will take a deep look at this new feature as well.

Thank you very much @scambier !!!!

I will continue to use this new version and I get to you with more FRs :)

**Comment by chrisgrieser** [comment]
> The latest update brings another modal to list search matches within a note. It's accessible with `alt-enter` from the "vault search" modal. Does this fulfill this feature request?

Thank you! yes, from my end, this does fulfill the request.
