### ISSUE TITLE
[Feature request] Add a sidebar button

### ISSUE THREAD

**Issue by scambier** [scambier/obsidian-omnisearch#60]
A sidebar button to display the vault search modal could be a nice feature, especially for mobile users.

**Comment by akay64** [comment]
Till a custom one is available people can use this plugin https://github.com/phibr0/obsidian-customizable-sidebar to add one themselves... In-fact it might even be sufficient, it works well on mobile as well.

Example of using it with "Templater" plugin that does not have its own sidebar icon option.
![image](https://user-images.githubusercontent.com/6232227/174493962-0887e6c9-b227-4f7a-9007-bf0f7ed4a59b.png)
