### ISSUE TITLE
[Feature request] Option disable search context.

### ISSUE THREAD

**Issue by isle9** [scambier/obsidian-omnisearch#70]
**Is your feature request related to a problem? Please describe.**
I feel like most of the time, I don't really need the context of what I'm looking for. It would be nice if there was a way to disable the search context.

**Describe the solution you'd like**
An option in the settings to disable the search context.

**Additional context**
Additionally, it would be nice if there was a toggle to quickly enable/disable the context while searching, and/or even if the context popped out if the file waas being hovered.

**Comment by scambier** [comment]
Somewhat related to https://github.com/scambier/obsidian-omnisearch/issues/36
