### ISSUE TITLE
[BUG] Many Japanese and Chinese cannot be found

### ISSUE THREAD

**Issue by Devon22** [scambier/obsidian-omnisearch#75]
For example, "やばい" and "そうだよ" cannot be found.

**Your environment:**

- Omnisearch version: 1.4.1
- Obsidian version: 0.14.15
- Operating system: Windows7
- Number of notes in your vault (approx.): 3800
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Support for Chinese & Japanese depends on [this plugin](https://github.com/aidenlx/cm-chs-patch), that must be installed and activated. I forgot to document it properly and will fix this asap.

**Comment by scambier** [comment]
Fixed with https://github.com/scambier/obsidian-omnisearch/commit/0cc0199fd833c26845bca7b33343e650e4ba1d8a
