### ISSUE TITLE
[Feature request] Allow opening an already open note in a different pane

### ISSUE THREAD

**Issue by gavinmn** [scambier/obsidian-omnisearch#80]
**Is your feature request related to a problem? Please describe.**

I often use the quick switcher to open a second copy of a file in a new pane so I can scroll or zoom into a different portion of it. When I try and open a new pane with an already open note in Omnisearch, it looks like Omnisearch instead opens the first result that is not open.

**Describe the solution you'd like**

Allow me to open a second instance of a note that is already open in the same way I can open a note that is not already open. 

**Additional context**

You can see this functionality in action by using the default quick switcher.

**Comment by scambier** [comment]
`ctrl+enter` on a selected result should open it in a new pane. Is it what you're looking for?

**Comment by gavinmn** [comment]
> `ctrl+enter` on a selected result should open it in a new pane. Is it what you're looking for?

What I'm running into in particular is this example:

- `Note 1` is open
- open omnisearch
- search "note 1"
- hit command enter to open a _second pane with the same note_

Expected result: I now have two panes each with `Note 1` open in them

Actual result: Omnisearch either doesn't do anything, or opens the next matched result (might be `Note 2`) in a new pane

**Comment by scambier** [comment]
Could you try https://github.com/scambier/obsidian-omnisearch/releases/tag/1.5.0-beta1 please?

It should work, but I don't have a Mac to confirm 100%
