### ISSUE TITLE
[Feature request] Is there a more prominent display?

### ISSUE THREAD

**Issue by zhl111** [scambier/obsidian-omnisearch#82]
The weight has been added to the maximum, but it is still not obvious. Is there a more prominent display?
![image](https://user-images.githubusercontent.com/29135984/178952461-bd1bf5e6-942c-4419-bdff-5b9da02f0f40.png)

![image](https://user-images.githubusercontent.com/29135984/178952327-4dded695-1909-467f-bf13-e086ca15f15c.png)

**Comment by scambier** [comment]
The weightings in settings refer to the scoring algorithm, not to the font weights. If you wish to customize the visuals, you can write a CSS snippet to use the different CSS classes: https://github.com/scambier/obsidian-omnisearch#css-customization
