### ISSUE TITLE
In-file search does not work

### ISSUE THREAD

**Issue by Missionary2112** [scambier/obsidian-omnisearch#84]
**Problem description:**
### Details
 The Omnisearch: In-file search cannot be activated by hotkey nor does it work properly. I mainly use Omnisearch: vault search and when I use `tab` to switch to In-file search, I cannot open to the exact line but at the file level. 
### Console Logs
app.js:1 Obsidian Developer Console
plugin:obsidian-focus-mode:145 Loading Focus Mode plugin ...
plugin:obsidian-admonition:479 Obsidian Admonition loaded
plugin:advanced-toolbar:2716 Loading Advanced Mobile Toolbar plugin.
plugin:advanced-toolbar:2722 Advanced Mobile Toolbar detected desktop Obsidian and is aborting. You still have access to change the settings.
plugin:file-explorer-note-count:935 loading FileExplorerNoteCount
plugin:recent-files-obsidian:209 Recent Files: Loading plugin v1.3.3
plugin:recent-files-obsidian:247 Recent Files: maxLength is not set, using default (50)
plugin:obsidian-sort-and-permute-lines:93 loading Sort & Permute lines
plugin:table-editor-obsidian:23703 loading markdown-table-editor plugin
plugin:oz-image-plugin:180 Image in Editor Plugin is loaded
plugin:better-fn:4113 loading BetterFn
plugin:dataview:20361 Dataview: version 0.5.41 (requires obsidian 0.13.11)
plugin:metadata-extractor:33 loading Metadata Extractor plugin
plugin:customizable-page-header-buttons:60 loading Customizable Page Header Plugin
plugin:block-reference-count:845 loading plugin: Block Reference Counter
plugin:obsidian-gallery:15166 Loaded Gallery Plugin
plugin:mousewheel-image-zoom:99 Loaded: Mousewheel image zoom
plugin:obsidian-leaflet-plugin:2 Loading Obsidian Leaflet v5.0.3
plugin:note-refactor-obsidian:6488 Loading Note Refactor plugin
plugin:obsidian-outliner:2499 Loading obsidian-outliner
plugin:obsidian-banners:28 Loading Banners...
plugin:highlightr-plugin:3516 Highlightr v1.2.1 loaded
plugin:find-unlinked-files:495 loading Find unlinked files and unresolved links plugin
plugin:obsidian-image-toolkit:3148 loading obsidian-image-toolkit plugin v1.3.1 ...
plugin:obsidian-sortable:157 Sortable: loading plugin...
plugin:obsidian-sortable:160 Sortable: loaded plugin.
plugin:quickadd:16120 Loading QuickAdd
plugin:breadcrumbs:62381 loading breadcrumbs plugin
plugin:omnisearch:11 Omnisearch - indexing 653 notes
plugin:dataview:13917 Dataview: all 653 files have been indexed in 1.558s (653 cached, 0 skipped).
31Failed to decode downloaded font: <URL>
31OTS parsing error: overlapping tables
index.html:1 Uncaught (in promise) DOMException: A network error occurred.
plugin:omnisearch:11 Omnisearch - Indexed 653 notes in 7420ms
app.js:1 Received URL action Object
app.js:1 Received URL action Object
app.js:1 Received URL action Object
app.js:1 Received URL action Object
app.js:1 Received URL action Object
app.js:1 Received URL action Object
2app.js:1 TypeError: buttons2 is not iterable
    at buttons (plugin:block-reference-count:723:26)
    at new import_view2.ViewPlugin.fromClass.decorations (plugin:block-reference-count:748:26)
    at e.create (app.js:1:412132)
    at e.update (app.js:1:412562)
    at e.setState (app.js:1:497271)
    at e.set (app.js:1:1297242)
    at t.setViewData (app.js:1:1667228)
    at t.setData (app.js:1:1335676)
    at t.<anonymous> (app.js:1:1335579)
    at app.js:1:235078
ia @ app.js:1
raw.githubusercontent.com/HEmile/obsidian-search-on-internet/master/resources/external_link.png:1          Failed to load resource: the server responded with a status of 404 ()
app.js:1 TypeError: buttons2 is not iterable
    at buttons (plugin:block-reference-count:723:26)
    at new import_view2.ViewPlugin.fromClass.decorations (plugin:block-reference-count:748:26)
    at e.create (app.js:1:412132)
    at e.update (app.js:1:412562)
    at e.setState (app.js:1:497271)
    at e.set (app.js:1:1297242)
    at t.setViewData (app.js:1:1667228)
    at t.setData (app.js:1:1335676)
    at t.<anonymous> (app.js:1:1335579)
    at app.js:1:235078
ia @ app.js:1
8The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
### Attach Screenshot
 
I search at text level within the file but when I click on it, the file does open but not at exact location. 

![Screenshot - 2022-07-19 17 06 09 (Obsidian)](https://user-images.githubusercontent.com/98799613/179868386-93d512d1-ec6c-400e-942c-c078128b6a45.jpg)

---
**Your environment:**

- Omnisearch version: 1.5.0-beta2
- Obsidian version: v0.15.7
- Operating system: MacOS Monterey Version 12.4
- Number of notes in your vault (approx.): 550
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Should be fixed, you can update Omnisearch in Obsidian.

Regarding "In-file search cannot be activated by hotkey", the hotkey is only active when the active pan is a note, otherwise it is ignored.
