### ISSUE TITLE
[BUG] The search doesn't work well with query containing "."

### ISSUE THREAD

**Issue by laphylee** [scambier/obsidian-omnisearch#85]
**Problem description:**

The search doesn't work well with query containing ".", such as {azure.com}, {abc.xyz}. However, it works when I add quotes around the query. 

**Your environment:**

- Omnisearch version: 1.5.0-beta3
- Obsidian version: 0.15.8
- Operating system: Win11
- Number of notes in your vault (approx.): 200

**Comment by scambier** [comment]
Not a bug sorry, that's a limitation of the tokenizer. `.` is a word delimiter, like all punctuation. So `azure.com` is actually split into `azure` and `com` in the index

**Comment by laphylee** [comment]
Thanks @scambier! Thank you for your explanation. If {azure.com} equals to {azure com}, could the search results also highlight all the "azure" and "com" keywords?  Currently there are no highlights for any keywords. It's hard to tell which result is more relevant.

**Comment by scambier** [comment]
I'll check and fix this asap 👍
