### ISSUE TITLE
[Feature request] Option for disabling startup notification

### ISSUE THREAD

**Issue by scorchio** [scambier/obsidian-omnisearch#91]
**Is your feature request related to a problem? Please describe.**
Every time I start Obsidian, a notification about Omnisearch indexing pops up. That information is usually not really useful for me, as Omnisearch "just works" 🙂 

**Describe the solution you'd like**
I would like a setting for disabling this notification.

**Comment by scambier** [comment]
Right there in the settings :)

![image](https://user-images.githubusercontent.com/3216752/185918893-bd7675fd-bbd8-434d-932f-b47080412189.png)

**Comment by scorchio** [comment]
Ah, sorry, I was using a way too old version which didn't even have settings yet... 🤣
