### ISSUE TITLE
Reimplement the cache in IndexedDB

### ISSUE THREAD

**Issue by scambier** [scambier/obsidian-omnisearch#92]
By default, Obsidian Sync will sync Omnisearch cache files, unless you manually exclude them on all your devices. This is slow, unnecessary, and will eventually corrupt those files, making Omnisearch unusable.

Saving those files _outside_ of the .obsidian folder will solve this issue. Check the feasibility for the mobile app too.

**Comment by Oblique82** [comment]
this makes sense - was going to ask if there was a guide for end-users on how NOT to sync the cache - but I don't know how to manually exclude it in the present circumstance

**Comment by scambier** [comment]
As of 1.7, I completely removed the caching feature:

- It could become corrupt and render Omnisearch useless
- It was writing big files on the disk that some users were unnecessarily syncing (thing augmenting the risk of corruption)
- It did not scale well
- These issues were made worse with the refactor for PDF indexing

I'll reimplement it later with IndexedDB

**Comment by scambier** [comment]
As of 1.7, I completely removed the caching feature:

- It could become corrupt and render Omnisearch useless
- It was writing big files on the disk that some users were unnecessarily syncing (thing augmenting the risk of corruption)
- It did not scale well
- These issues were made worse with the refactor for PDF indexing

I'll reimplement it later with IndexedDB
