### ISSUE TITLE
[Feature request] Search for synonyms

### ISSUE THREAD

**Issue by Sanqui** [scambier/obsidian-omnisearch#94]
This may be a bit of a pie-in-the-sky idea, but I wonder, if I search for e.g. `shop`, if it would be possible to also search for words like `store` and `market` with a very low score.  This would especially be helpful when there are no results for the given search term.

**Comment by scambier** [comment]
It's definitely possible, [there are different solutions to solve this](https://medium.com/@nikhilbd/how-to-use-machine-learning-to-find-synonyms-6380c0c6106b). Those solutions all have trade-offs: a synonyms approach is easy but you need to embed an exhaustive dictionary for each supported language, the NLP approach is context-aware but will only work with words that are present in your corpus.

I'll take a deeper look when I have more free time 👍

**Comment by scambier** [comment]
Good news: I had more free time this evening.

Work in progress, yadda yadda. It uses OpenAI so you'll have to provide your own key :) Truly an incredible tool.

![omnisearch-ai](https://user-images.githubusercontent.com/3216752/205160774-e1e93227-4e28-4572-b0c6-f1c54c6f7695.gif)
