### ISSUE TITLE
[Feature request] Results weighting adjustment by path

### ISSUE THREAD

**Issue by cyc115** [scambier/obsidian-omnisearch#95]
**Is your feature request related to a problem? Please describe.**

I sync web annotation to the same vault as hand written notes. I would love to deprioritize web annotation notes that lives under an `annotation` path. 

**Describe the solution you'd like**

Allow to set results weighting for custom path.

**Describe alternatives you've considered**

Excluding a directory via Obsidian's exclude Files is undesirable because I would still like to surface results from a deprioritized path.

**Comment by scambier** [comment]
> Excluding a directory via Obsidian's exclude Files is undesirable because I would still like to surface results from a deprioritized path.

That's already how it works; notes in the excluded list are not hidden in Omnisearch, just downranked. Is it an acceptable solution?

![image](https://user-images.githubusercontent.com/3216752/189598312-f0fcf11e-3f2d-44e3-ab67-f5db85bce854.png)
