### ISSUE TITLE
[Feature request] Creating a new note on mobile

### ISSUE THREAD

**Issue by sohanglal** [scambier/obsidian-omnisearch#96]
**Is your feature request related to a problem? Please describe.**
It would be great to have the ability to create a new note on mobile right from within the OmniSearch modal

**Describe the solution you'd like**
Option to create a new note similar to the way it is on desktop

**Describe alternatives you've considered**
Using the both the omnisearch modal as well as the Quick switcher++ plugin.
I first look for a note using omnisearch. If I am not able to find it, I then switch to Quick swticher to create a new note

**Comment by scambier** [comment]
I just checked Quick Switcher++. Do you want to be able to create a new note with `Enter` when there is no result, or is there something else?

**Comment by sohanglal** [comment]
> I just checked Quick Switcher++. Do you want to be able to create a new note with `Enter` when there is no result, or is there something else?

![Screenshot_20220919-161247_Obsidian](https://user-images.githubusercontent.com/29398628/191001481-b8ea2fc0-6f36-45cd-b131-d9e4c8472454.png)
Yes that is what I had in mind.

**Comment by sohanglal** [comment]
I don't know if this is possible but in case there are suggestions to what I am typing but I still want to create a new note, could I scroll to the bottom of those suggestions to find the option to create a new note?

**Comment by sohanglal** [comment]
Thanks a lot!

**Comment by sohanglal** [comment]
![image](https://user-images.githubusercontent.com/29398628/191772468-9784ffce-0864-4978-967f-312335b13c3c.png)
This is working really well on version: 1.6.0-beta2!

**Comment by scambier** [comment]
:D ha, almost!

I'll fix the layout asap, thanks for the feedback.

**Comment by scambier** [comment]
Deployed in 1.6.0-beta3. I'll keep this issue open until the final release, if there's anything else to fix.
